[quote.epigraph, , Prov. 10:7]
____
The memory of the just is blessed.
____

[quote.epigraph, , Ps. 112:6]
____
The righteous shall be in everlasting remembrance.
____

== Selection from the Journal of John Burnyeat

In the year 1653,
it pleased the Lord in His love and mercy to send to us His faithful servant George Fox,
with others of His faithful servants and messengers of
the Gospel of peace and glad-tidings.
He was a man furnished with the eternal power of His Word,
in the wisdom and power of which he proclaimed the Day of the Lord unto us,
in this county of Cumberland, and the northern parts of England,
uncovering the right path of life unto thousands that were in error, who sought the Lord,
but knew not where to find Him, nor how to become acquainted with Him,
although He was not far from us.
This blessed man, George Fox, one of a thousand many may say,
and chosen before many thousands, was sent among us, in the power of the Most High,
filled with the strength of His Word.
In the wisdom of God he directed thousands unto the light and
appearance of Christ Jesus their Savior in their own hearts,
that they might come to know Him,
and the glory of the Father through Him in His appearance,
and so come to believe in Him with the heart,
and with the mouth to confess Him unto salvation.

Blessed be the Lord for the day of mercy in which He visited us,
for He was pleased to make this labor of love effectual
unto thousands where His servants were sent to labor.
And among these,
it pleased the Lord to grant me the favor to keep a
share of the benefit of this blessed visitation,
whereby I came to be informed concerning the right way of the Lord,
and directed to the true light which the apostle Paul was sent
to turn people unto in his day--from the darkness and the
power of Satan unto God and His blessed power--which,
in my waiting in the light, I received.

Through this light, deep judgment sprang in my soul,
and great affliction grew in my heart,
by which I was brought into great tribulation and sorrow,
such as I had never known before in all my profession of religion.
Indeed,
I could say in spirit that it was "`the day of Jacob`'s trouble,`" for the God of Heaven,
by the light of His blessed Son which enlightened me and shone in my heart,
let me see the body of death and power of sin which reigned in me,
and brought me to feel the guilt of it upon my conscience,
so that I could say He made me, even as it were, "`possess the sins of my youth.`"

Notwithstanding all my lofty profession of an imputed righteousness, and a belief that,
though I lived in the act of sin, the guilt of it should not be charged upon me,
but imputed to Christ, and His righteousness imputed to me,
yet I found it otherwise when I was turned unto the
light which did manifest all reprovable things.
For I came to see that the guilt remained while the body of death remained,
and while we are still led into the act of sin through its power.
Then I saw there was need of a savior to save from sin,
as well as of the blood of a sacrificed Christ to blot out sin,
and of faith in His name for the remission of sins past.
Then began the warfare of true striving to enter the kingdom.
Then I knew Paul`'s state--to will was present, but power was many times lacking to do.
Then was that cry known, "`O wretched man that I am,
who shall deliver me from the body of this death,`" and free me from
the prevailing power of the law which remained in the members,
warring against the law of my mind, and bringing me into captivity to the law of sin?

When this war had truly begun, all my proud conceit in my invented notional faith,
and my pretenses and hopes of justification thereby, were overthrown.
Indeed, all that I had built for several years in my profession,
since the days of my youth (during which time tender stirrings
were in me after true acquaintance with the Lord,
and the knowledge of Him, and peace with Him), was seen to be but a tower of Babel,
upon which God brought confusion.
I saw that such a tower could never be made to reach unto heaven,
being outside of the faith of His covenant;
nor could it bring the heart to truly trust and rely upon His word,
but rather led out into inventions, self-willing and self-acting,
though true things were spoken of.

Then, seeing all my works confounded by the visitations of God,
and by the springing of the Day from on high which discovered things as they were,
and seeing them all end at Babel, and the God of heaven bringing confusion upon them,
I was amazed, and fear beset me on every side.
I began sometimes to fear I was undone forever;
for something had entered my heart which turned the fruitful field into a wilderness,
and turned what I thought was as the Garden of Eden into a forest.
The Day of God discovered all to be desolation, dryness, and death,
and brought my soul to a deep lamentation, to such sorrows as I had never known before.
Then I lamented and bewailed myself many times,
and my weakness was such that I wished myself in a wilderness where I
would neither meet with temptation or provocation from without.
For all the notions I talked about regarding Christ`'s imputed righteousness to be my own,
were not confirmed by His Spirit`'s seal, and so my righteousness was only a presumption.
I saw clearly that my supposed righteousness was my own invention,
and so it was only like Adam`'s fig-leaf covering,
in which he could not abide God`'s coming.

Оh the woe that overtook me!
The distress that seized me!
The horror and terror that sprung in my bosom!
The poverty and lack that my soul saw itself in,
through the springing up of the discovering light,
towards which the eye of my soul was turned!
And as this light sprung up, of which the apostle of old wrote,
it manifested all things--not only the lack that I was in,
but also the things which God reproved.
Then "`sin became exceedingly sinful,`" and the load
and burden of it became exceedingly grievous,
and all the pleasure of it was taken away from me (and many others) in that day.
Then we began to mourn after a savior, and to look for a deliverer,
and to cry for a helper and a healer.
For the Day of the Lord that makes desolate had overtaken us,
and the fire and sword that Christ brings upon the
earth (by which He takes away peace) had reached to us.
Yet we knew not the one from whom all of this came,
though His burning and judgment had begun, by which the filth was to be taken away.

And now in this distress, deep were our groans and our cries unto the Lord,
which reached unto Him, and He was pleased to hear and show mercy.
We often assembled together,
as the Lord`'s messengers (whom He had sent among us) exhorted us,
and we minded the light of Christ in our hearts, and whatever it uncovered.
And in our spirits (through the assistance of His light)
we warred and watched against the evil found there;
and with the understanding we received,
we waited upon the Lord to see what He would further make manifest,
always with a holy resolution to obey His will so far as we were able,
whatsoever it cost us.

And this I can testify was the condition of many in that day: We did not value the world,
or any glory or pleasure in it,
in comparison with our soul`'s redemption out of that fallen state.
Indeed we longed for freedom from the horror and
terror we felt under the indignation of the Lord,
which we saw ourselves to be in because of the guilt of sin that was upon us.
So we gave up to bear the indignation of the Lord (because we had sinned),
and we endeavored to wait until the indignation was over,
and the Lord in mercy would blot out the guilt that remained (which occasioned wrath),
and would sprinkle our hearts from an evil conscience, and wash us with pure water,
that we would be enabled to draw near with a true heart, in full assurance of faith,
as the Christians of old did.
(Heb. 10:22)

But alas, we had no boldness, for the living faith was lacking!
And we did not have a true heart by which to draw near,
and therefore could not have full assurance, but instead were surrounded by fears,
horrors, and amazement.
And yet we came to know that there was no other way except to dwell in these judgments,
"`to wait in the way of His judgments`" (Isa. 26:8),
understanding that we must "`be redeemed with judgment,`" as was said of Zion, Isaiah 1:27.
So waiting therein, we began to learn righteousness,
and strongly desired to walk in it, for we were no longer satisfied with a talk thereof.
Thus waiting for and seeking after the Lord (though greatly ignorant of Him),
in a deep sense of our own unworthiness and unpreparedness to meet Him because of
the pollution of our hearts (which was seen by His light that did shine there),
we remained bowed down in spirit, afflicted and tossed in soul, and not comforted.
Indeed, our hearts were unstable like water--the waves going over our heads,
and our souls in jeopardy every moment.
Our faith was so little that, like Peter, we were ready to sink,
often crying out in the danger.

In this distress and veil of tears through which we walked,
our hearts became quite dead to the world, and all its pleasure and glory.
We became dead also to all our former religious professions,
for we saw there was no life in them, nor help or salvation,
though some of us had tried them thoroughly.
We saw it was in vain to look to such hills or mountains for salvation.
So we began to forsake all on both hands, seeing the emptiness of all--both the glory,
vanity, and pleasure of the world,
and the dead image of religious profession which
we had set up in our imaginations and inventions,
and had worshipped with our unprepared hearts and unsanctified
spirits (being still slaves and captives to sin,
as all are who obey its lusts, according to Romans 6:15-16). Yes,
when we had a true sight and sense of the insufficiency
of all that we either had or could do to give us ease,
help, or salvation, we then denied them all.
And as we had been directed,
we turned our minds unto the light of Christ shining in our hearts,
and believed in Him (according to His command, John 12:36),
and met together to wait upon the Lord in the light.

The lofty professors of our days were ignorant of the Holy Spirit,
through their resisting of it.
They blasphemed the life and power, and at best, did but feed upon the tree of knowledge.
I still remember well,
that in my waiting upon the Lord in the deep distress
and weighty judgment that was upon my soul,
to see if He would appear and break through and give relief
from that which kept me down like bars of iron... I say,
I remember that in the very first notable breaking in of the power of
God upon my soul (or pouring forth of the Holy Spirit upon me),
I came to a true discovery of the mystery of the tree of knowledge.
In the light I clearly saw on what tree I had been feeding (along
with all the carnal professors of religion),
and how we had made a profession of that which we did not possess.
Indeed, our souls were still in death,
feeding upon the mere talk of that which the saints of old did enjoy.
Here I saw that there was no getting to the Tree of
Life (so that our souls might be healed by its leaves,
and feed upon its fruit, and live forever) unless I first came under the wounding,
slaying sword that Christ brings, by which the life of the old man comes to be destroyed.
And I saw how this man desires to remain in sin, and serve it,
and yet profess faith in Christ, and claim to be His servant (which is impossible,
according to Christ`'s own saying,
"`No man can serve two masters`" Matt. 6:24). It clearly
opened to me that there was no other remedy--I must either be
buried by that fiery baptism of Christ with Him into death,
or else there could be no rising with Him into newness of life.
There might be a rising into a newness of profession, notions, and words,
but that would not do, for it was newness of life that I needed;
the other I had tried over and over.
I saw I must die with Him, or be planted with Him in the likeness of death--that is,
truly die unto sin--if ever I would come to be united
with Him in the likeness of His resurrection,
and so live unto God, according to Romans 6.

When these things thus opened in me,
I clearly saw we had all been deceived in thinking that while we lived in the flesh,
after the flesh, and so in the death (feeding upon the tree of knowledge,
which was forbidden for food), we might profess to reap life everlasting.
For I soon saw that, as a man lived, and as a man sowed, _that_ would he reap,
and not what a man professed or talked of.

Then I was willing to bow to the cross, and come under the fiery baptism of the Spirit,
and let that which was consumable be destroyed, that my soul might be saved,
and come to possess that which would endure and abide and could not be shaken.
Thus were the heavens shaken also, as well as the earth,
so that what could not be shaken might remain (according to Heb. 12:27).
For the light and true witness
(as it was acknowledged by us in our hearts)
condemned the evil fruits of the flesh,
both in our loose conduct and in the lusts and desires of our hearts,
and did also discover and condemn our fleshly profession of
religion (which was in that same nature and mind),
so that our false covering and garment was taken away, and we were comfortless and naked,
destitute and without a habitation.

Then we saw clearly that our worship and our sinning were alike in the sight of God.
Indeed, even our prayers were rejected and despised, because all was done in one nature,
and from one and the same seed and corrupt heart.
Therefore, it came to be with us as it was with Judah of old (read Isa. 1 and Isa. 66:3)
that their killing an ox, sacrificing a lamb, offering an oblation,
and burning incense was like the slaying of a man, cutting a dog`'s neck,
offering swine`'s blood, and blessing an idol.
Thus we saw that, for lack of righteousness and keeping the commandments of the Lord,
and not forsaking of our own ways and all that was evil,
so our religion was loathed by the Lord, and we were rejected in all our doings,
and left in desolation and barrenness.
For regardless what we did pretend, that truth of Christ`'s saying does stand,
"`A good tree cannot bring forth bad fruit, nor a bad tree good fruit;
the tree is known by its fruit.`"

These things opened wonderfully in us, and we discerned not only common sins,
which all confess to be sinful (though they live in them),
but also the hypocrisy and sinfulness in religion which is
performed outside the true Spirit of grace and life (which is
the salt with which every gospel sacrifice is to be seasoned,
according to the old covenant figure).
Therefore we were required of the Lord to withdraw and be separate in our worship,
and to wait to have our hearts sanctified, and the spirit of our minds renewed,
that we might come before Him with prepared vessels.
And we soon learned that it must be true in the
substance even as it was in the figure--namely,
that all the vessels of the tabernacle were to be sanctified, consecrated, or made holy.
Therefore we came out from among all who claimed to worship
but who lived in uncleanness and pleaded for sin.^
footnote:[The prevalent thought among Protestants (both then and now) is
that true freedom from sin is an impossibility on this side of the grave.
Quakers referred to such teaching as "`pleading for sin,`" that is,
arguing for the continuance and dominion of sin term of life.]

Then the profane began to mock, scoff, and abuse us,
and our very relations and old familiar friends became strangers to us,
and were offended at us.
Indeed they did hate us, and began to speak evil of us,
and "`thought it strange that we would not run with them into
the same flood of dissipation,`" as it was of old, 1 Pet. 4:4.
Also the professors of religion,
even those with whom we had formerly walked in fellowship in our lifeless profession,
began to reproach and vilify us, and to speak evil against us,
and charge us with error and schism, and departing from the faith.
They also began to reproach the light of Christ, calling it natural and insufficient,
a false light, and a false guide.
In this way, Christ, in His spiritual appearance, was reproached, vilified, slighted,
undervalued, and rejected by the carnal professors of Christianity in our day,
just as He was by the Jews in the day of His appearance in the
flesh (who could not see through the veil unto the end).

In this our weak state, we were beset on every side, and greatly distressed, tossed,
and afflicted.
We were like poor Israel, when the sea was before them, and the Egyptians behind,
and their hope was so little that they looked for nothing but death, and said to Moses,
"`Because there were no graves in Egypt,
have you taken us away to die in the wilderness?`" Ex. 14:11.
Thus we found that through many tribulations the kingdom must
be entered by all who strive rightly to enter it (Acts 14:22,
Luke 13:24).

But when we were sunk deep in our fears,
and our minds were not well acquainted with either the true striving (not of self,
but in the light and seed of life that does prevail),
or with the true waiting or standing still (apart from our own thoughts, wills,
and running,
which do not obtain) then the Lord sent us His servants who had learned of Him.
These showed us in what we should wait,
and directed us how to stand still out of our own thoughts and self-strivings,
in the light that does uncover all things,
and exhorted us to abide and dwell in the judgments that we received therein.
And as we turned to the light, so our understandings were by degrees informed,
and we got to a measure of staidness in our minds,
which before had been like a troubled sea.
Indeed, a hope began to appear in us, and we met together,
and waited to see the salvation of God (of which we had only heard),
longing that He would work by His own power.

In those days, we learned to meet and wait together in silence.
Sometimes, not a word was uttered in our meetings for months,
but everyone that was faithful waited upon the living Word in their own heart,
in order to experience sanctification and a thorough
cleansing and renewing of the heart and inward man.
And as we were cleansed and made fit,
we came to have a greater delight in waiting upon the Word in our hearts,
to receive its pure milk (of which Peter speaks, 1 Pet. 2:2). And indeed,
in our waiting, we received its virtue and grew thereby,
and were fed with the heavenly food that rightly nourished our souls.

So we came to receive more and more of the
Spirit of grace and life from Christ our Savior,
who is full of it, and in whom the fullness dwells.
He taught us thereby to "`deny ungodliness and worldly lusts, and to live righteously,
godly, and soberly in this present evil world.`"
By this we came to know the true Teacher,
which the saints of old did witness (as said the apostle in Tit. 2:12). Therefore,
though we had left the hireling priests, and also other lofty notionists,
and sat down together in silence,
still we did not lack a teacher or true divine instructions.
For this was our desire: to have all flesh silenced before the Lord and His power,
both within us and without.
And as we thus came into true silence and inward stillness,
we began to hear the voice of Him who said, "`I am the resurrection and the life.`"
Indeed He said unto us, "`Live,`" and gave unto our souls life,
and this holy gift which He has given has been in us as
a well of water springing up into eternal life,
according to His promise.
Therefore, it has been our delight all along to wait upon Him,
and to draw near with our spirits unto Him, both in our meetings and also at other times,
that we might both be taught and saved by Him.

So we met together in this way for some time, as often as we found opportunity,
and were exercised in the living judgments that sprung in the light in our souls,
and continued looking for the salvation of God.
We also sought the Lord with travailing spirits
both night and day when at our earthly callings,
and upon our beds (for we could not cease, our souls were so afflicted).

Then, the wonderful power from on high was revealed among us,
and many hearts were reached by it, and broken,
and melted before the God of the whole earth!
Great dread and trembling fell upon many,
and the very chains of death were broken by Him, and the bonds were loosed,
and many souls were eased and set at liberty.
The prisoners of hope began to come forth,
and those who had sat in darkness began to show themselves.
And many promises of the Lord, spoken of by Isaiah the prophet,
came to be fulfilled unto many.
Some witnessed the oil of joy, and a heavenly gladness entered their hearts,
and in the joy of their souls they broke forth in praises unto the Lord.
Yes, the tongue of the dumb was loosed by Christ, the healer of our infirmities,
and many began to speak and utter the wonderful things of God.

Great was the dread and glory of that power,
which in one meeting after another was graciously and richly manifested among us,
breaking, tendering, and melting our souls and spirits before the Lord.
Then our hearts began to delight in the Lord and
in His way (which He had cast up before us),
and with great fervency and zeal we began to seek after Him,
and to meet together more often than before.
Truly our hearts were affected with the presence of that blessed power,
which daily broke forth among us in our meetings,
and through it we were greatly comforted, strengthened, and edified.
For this was that same Comforter that our Lord promised to send from the Father, John 14:
26-27, John 16:13-15. And this Comforter, now having come and been received,
did teach us to know the Father and the Son.
Yes, as we came into acquaintance with it, and into the unity of it,
we came to be taught by it, and so were taught of the Lord,
according to that new covenant promise--"`They shall be
all taught of the Lord`" (Isa. 54:1,13 John 2:27).

Then our hearts were inclined to hearken unto the Lord,
and our ears (which He had opened to hear) were bent to hear the Spirit`'s teaching.
Indeed we heard what He said unto the church,
and found Him to be the chief Shepherd and Bishop of our souls,
who gathered us into a right gospel exercise and true gospel worship.
Through His name we received remission of sins past,
and through His blood we had our hearts sprinkled from an evil conscience,
and were given the pure water that washed and made us clean.
So that with true hearts many began to draw near unto God in the full assurance of faith,
as the ancient saints had done, and were accepted.
We found access by that one Spirit, and came to be baptized into one body,
and made to drink into one Spirit, and so we were refreshed, greatly comforted,
and grew up together in the mystery of the gospel fellowship.
Thus we worshipped God, who is a Spirit,
in the Spirit received from Him (which is the gospel worship, according to Christ,
John 4:24).

Then we came to see even more clearly over all the worships in
the world which were set up either by imitation,
or by man`'s invention.
We saw that it was in vain to worship God in invented and traditional worship,
and to teach for doctrines the commandments of men (as our Lord had said, Matt. 15:9,
Isa. 29:13). Therefore we were constrained not only to withdraw from them,
but (many of us) to go and bear witness against all
worship that was without the life and power of God.

Thus, having been gathered by the Lord Jesus Christ (that
great Shepherd of our souls) we became His sheep,
and learned to know His voice, and to follow Him.
He taught us, and led us forth into green pastures,
where we did feed and rest together with great delight.
He gave unto us eternal life, and manifested the riches of His grace in our hearts,
by which we were saved through faith and delivered from that wrath, fear,
and terror which had been so weighty upon our souls.
Truly, we came to partake of that life in which the blessing does consist,
and so in measure we were freed from the power of that death which had reigned,
and had made us miserable and wretched.

Oh the joy, the pleasure,
and the great delight with which our hearts were
overcome many times in our reverent and holy assemblies!
How were our hearts melted like wax, and our souls poured out like water before the Lord,
and our spirits were offered up to the Lord like sweet incense of oil,
frankincense and myrrh, when not even one word was uttered in all our assembly!
Then the Lord did delight to come down into His garden,
and to walk in the midst of the beds of spices.
Yes, He caused "`the north winds to awake,
and the south winds to blow upon His garden,`" and the pleasant
showers to descend for the refreshing of His tender plants,
that they might grow still more and more.
To those who had known the night of sorrow,
now the joyful morning had come (according to that ancient experience of David.
Ps. 30:5). And those who had formerly passed through deep afflictions, tosses,
and distresses, came to witness the fulfilling of that great gospel promise:

[quote.scripture, , Isa. 54:11-14]
____
O you afflicted one, tossed with tempest, and not comforted, behold,
I will lay your stones with colorful gems, and lay your foundations with sapphires.
I will make your pinnacles of rubies, your gates of crystal,
and all your walls of precious stones.
All your children shall be taught by the Lord,
and great shall be the peace of your children.
In righteousness you shall be established; you shall be far from oppression,
for you shall not fear; and from terror, for it shall not come near you.
____

Thus, we came to be gathered into covenant with God,
and to witness in Christ the fulfilling of the promises of God,
in whom all the promises are yes and amen.
We came to sit together in heavenly places in Him, and to feed upon the heavenly food,
the bread of life that came down from heaven,
which Christ (the heavenly Shepherd) gave unto us.
For He gathered us out from under those shepherds that
fed themselves with temporal things from the flock,
but knew not how to feed the flock with spiritual food, for they did not have it.

So we came to be acquainted with the power of the Lord Jesus Christ in our hearts,
and became great lovers of it, and delighted in the enjoyment of it.
We counted all things but dross and dung in comparison
with the excellence that we found here,
and we were therefore willing to suffer the loss of all that
we might win Him (as it was with the apostle of old).
Blessed be the Lord, for many obtained their desire, and found their beloved,
and met with their Savior,
and so witnessed His saving health by which their souls were healed.
In this way we became His flock and family, or His household of faith.
And as His children and blessed family,
we continued to meet together twice or more in the week,
and being gathered together in His name and holy fear,
we witnessed His promise (according to Matt. 18:20) that He was in the midst of us,
honoring our assemblies with His heavenly power and presence.
This was our great delight,
and the sweetness of His presence did wonderfully constrain our souls to love Him,
and our hearts to wait upon Him;
for we found the ancient experience of the Church to be true,
"`Because of the savor of Your good ointments, Your name is as ointment poured forth;
therefore do the virgins love You.`"

Thus growing into this experience of the goodness of the Lord, and of the sweetness,
glory, and excellence of His power in our assemblies,
we grew in strength and zeal for our meetings more and more,
and valued the benefit of them more than any worldly gain.
Yes, these times were to some of us more than our necessary food.
Continuing thus,
we grew more into an understanding of divine things and heavenly mysteries,
through the openings of the power which was daily among us,
and which worked sweetly in our hearts, uniting us more and more unto God,
and knitting us together in the perfect bond of love and fellowship.
So we became a united body, made up of many members,
of which Christ Himself became the head.
Indeed, He was with us, and did rule over us, and further gave gifts unto us,
by which we grew in capacity and understanding in order
to answer the end for which He had raised us up,
and blessed and sanctified us through His Word which dwelt in our souls.

As we kept to our first love, and continued in our meetings,
not forsaking the assembling of ourselves together (as was the manner of some of old,
whose example the apostle exhorted the saints not to follow),
the Lord`'s power continued with us.
Many, through the favor of God, grew in their gifts, and had their mouths opened,
and so became instruments in the Lord`'s hand to bear witness to the
world of the Day of the Lord which had broken forth again,
even of the great and notable Day of which Joel had prophesied and Peter bore witness.
Some were also sent to bear witness against the world, and its evil deeds,
and all the false religions with which mankind had covered himself in
the darkness and apostasy which had spread over them,
but which now was seen and discovered by the light and Day of God.

Thus the Truth grew, and so did the faithful in it, and many were turned unto God.
His name, fame, glory, and power spread abroad,
and the enemy`'s work and kingdom were discovered
and struck at by the Lamb and His followers.
This made the enemy begin to rage,
and to stir up his instruments to oppose the Lord`'s work,
and with all his subtlety to hinder people from
following the Lamb or believing in His light.

So with pen, and tongue, and hands also, the beast and his followers began to war.
They resorted to whipping, scourging, imprisoning, and seizing property.
They reproached, opposed, and slandered the way of truth,
doing whatever they could to hinder the exaltation of
the kingdom of the Lord Jesus Christ.
They blasphemed His light and His power, calling His light
"`natural, insufficient, and a false guide,`"
with many other reproachful names.
They called His power and operation "`demonic,`" which power indeed
worked in many toward the renewing of the spirit of the mind,
and also to the reformation of the conduct from all debauchery, wickedness,
unrighteousness, and witchcraft.
These were like the Pharisees of old who said of Christ,
"`By the ruler of the demons He casts out demons.`"

However, by this time,
those who had kept faithful to the Lord (and His light and
Spirit in their hearts) and who had come forth through the
deep tribulation (as before related) were already confirmed,
settled, satisfied, and established in the life that was manifested.
In this life they saw over death, and through all men`'s professions,
and could discern where men were and what they fed upon.
And they saw that those who cried out against the light and power of
Christ were like the mockers in the second chapter of Acts,
when they thought the Apostles were drunk with new wine.

From the year 1653 (in which year I was convinced of the
blessed truth and the way of life eternal) unto the year 1657,
I was not much concerned to travel abroad on account of the Truth,
save only to visit Friends that were prisoners for the Truth`'s testimony.
During this time I was mostly at home, following my outward calling.
I was very diligent to keep to our meetings,
being given up in my heart to attend faithfully,
and indeed I found great delight in them.
Many times, when a meeting was over,
and I was at my outward labor (in which I was also very diligent),
I did long in my spirit for the next meeting day,
that I might meet with the rest of the Lord`'s people to wait upon Him.
I can also with safety say, that when I was there, I was not slothful,
but in true diligence I set my heart to wait upon the Lord for a
visitation from Him by the revelation of His power in my soul.
And I can say this for the Lord, and on His behalf (with many other witnesses),
that as we waited in diligence, patience, and faith, we did not wait in vain.
He did not allow our expectations to fail; everlasting glory, and honor,
and praise be to His worthy and honorable name forever!
The very remembrance of His goodness and glorious power,
revealed and renewed in those days, overcomes my soul.

Thus, in diligent waiting, the Lord in mercy did visit our hearts by His power,
and my soul was daily more and more affected with the glory, excellence,
and sweetness of it, and also with a holy dread which filled my heart.
This became pleasant to me, and so my spirit was bent to keep near unto this power,
and to dwell in that holy fear which the Father placed in my heart.
I came to see what David exhorted to in the second Psalm,
when he told the kings and judges of the earth "`Be wise and learned`" and further said,
"`Serve the Lord with fear, and rejoice with trembling.`"
Oh the bowings of my soul!
Oh the pleasant dread that dwelt upon my spirit,
and the reverent tremblings that came over my heart,
which filled it with living joy as with marrow and fatness!
Then I could say in my heart with David, "`I will wash my hands in innocence,
and go about Your altar, О Lord.`"
Oh how pleasant it is to draw near unto the altar of the Lord,
having hearts prepared and filled,
and souls and spirits anointed with the true anointing from the Holy One,
of which John speaks (1 John 2:27). This anointing is
the substance of the figure in Ex. 30:25,
with which Moses was commanded to anoint the vessels of the tabernacle.

Our hearts were thus fitted, filled,
and furnished many a time in our holy assemblies as we
sat together under the same dread and power,
for the temple or tabernacle in which we worshipped
(as children of the new Jerusalem) was but one--
"`even the Lord God and the Lamb`" (Rev. 21:22).
And as my heart was thus fitted and filled,
I endeavored to keep my spirit down to the melting sense of the power;
and great was the care of my soul that I might in no way miss or abuse this power,
or let up a wrong thing into my mind, and so be betrayed by it.
I found that if I was careful to keep down all that was wrong,
then I would grow into sound wisdom and a true understanding,
even of those mysteries of which the world was ignorant.
For the Son of God had come,
and it was He that "`gave the understanding to
know Him that is true`" (as John had said),
and "`He was made unto us wisdom`" (as Paul said in 1 Cor. 1:30). I often
observed with great care and diligence how it was with my own spirit in those
blessed and pleasant seasons in which the Lord did so wonderfully appear among us,
filling our hearts with the glorious majesty of His power.
I kept watch to see whether my spirit was subject to Him, as it ought to be;
for I clearly saw that the enemy might beguile and lead up into the heights,
and into pride and vainglory.
For if the soul was not kept humble, it would soon be deprived of the power, for,
"`The meek will He guide in judgment, and the meek will He teach His way.`"

Thus, even in the greatest enjoyments,
I saw there was a constant need of carefulness and fear.
For those that grew sluggish, idle, and careless in waiting for the power in a meeting,
sat without the sense of it in a dead, dry, barren state.
These were not diligent to keep low, humble, and tender,
and so to mind the nature of the working of the power,
and the state of their own spirits under the power`'s exercise,
and also to watch against the enemy`'s subtlety (who lays in wait to betray).
Indeed these were easily led aside (out of the way of the power) by the stranger,
even while the power was working and the joy was in the hearts of others.
I found that, for lack of true fear and care,
the soul could come to a loss before it was aware.
I believe that some have fallen here, and can scarcely find the reason of it.
Oh, it may truly be said,
"`Great is the mystery of godliness,`" even the great mystery which
Paul writes of in Colossians--"`Christ in you the hope of glory.`"
And as He is there (in us), great is the mystery of His working in us by His Spirit,
to the opening and clearing of the understandings of all who rightly wait upon Him.
For it is the _soul_ of man that experiences the sanctification,
and the oneness with the life, and the true unction.
Indeed, it is the soul that comes to be a priest of the royal priesthood,
chosen and elected in God`'s covenant,
and so comes rightly and lawfully to eat the holy things,
and to partake of the sanctified holy food.
Therefore, the stranger is not to come near this place;
and this was signified in the figure--"`The stranger
was not to eat of the Passover`" (Ex. 12:43),
and "`No stranger should eat of the holy things`" (Lev. 22:10),
and again Solomon said, "`The heart knows its own bitterness,
and a stranger doesn`'t meddle with his joy`" (Prov. 14:10). Much more might be said,
but this is the point of the matter:
The heart that has known its own bitterness in judgment and distress,
and has come through this unto peace and joy, must keep therein,
and not let that which has no share with it to come and meddle with the joy;
for if it does, this will soon overthrow the joy of the soul,
and bring it to another state.
Then the soul will find no more pity in the day of distress
than Judas had from the Jews after he had betrayed his Master,
when they told him, "`What is that to us? You see to it!`"

As I have said before,
I continued for these four years mostly following my outward calling,
and attending and waiting upon the Lord in the workings of His holy power in my heart,
both in meetings and at other times.
Wherever I was, or whatever I had to do,
I found that as my heart was kept near to the power, it kept me tender, soft, and living.
And besides this, I found that as I was diligent in eyeing it,
there was a constant sweet stream of divine peace, pleasure,
and joy that ran softly in my soul,
which far exceeded all other delights and satisfactions.
This became the great engager of my soul to keep watch with great diligence,
for I found the love of God to constrain me.
And furthermore, I observed that if I neglected it,
or let my mind out after anything else more than I ought, and so forgot this,
I began to be like a stranger,
and I saw that I soon might lose my interest in these riches and treasures,
and in the true inheritance of God`'s spiritual Israel, which Christ had purchased for me,
and given me the taste of to inherit.

Thus I went on in the holy fellowship of the gospel of life and salvation,
with the rest of my brethren and sisters,
and many joyful days we had together in the power of the Holy Spirit,
which was richly and graciously continued among us, and daily poured out upon us.
We continued to grow in favor with God, and in unity one with another,
and received daily strength from the Lord,
and an increase of His divine wisdom and Spirit, which did greatly comfort us.
I do well remember how my heart was satisfied in this pleasant state,
and I became settled in a contentment where I was willing to abide.
And because of the blessings and rich mercies of the Lord which my soul enjoyed,
I became willing to serve Him in whatever I might,
and I willingly received a share of His concern for the church,
that I might be helpful in all necessary things.

So the Lord began to stir in my heart by His Spirit,
to arise and go forth in the strength of His word,
and declare against the hirelings who fed themselves and not the people,
and who kept the people ignorant of these good things.
But when the word of the Lord came unto me with a message to declare,
it became a great exercise to me, and I would willingly have shunned it,
and instead continued in that ease, peace,
and pleasure into which the Lord had brought me.
But I soon came to know there was no peace but in obeying the Lord and
giving up to do His will (for I was sure it was the word of the Lord).
So then I yielded in spirit, and began to long for the day that I might clear myself,
and be eased of the charge that was upon me.
Indeed, I could not keep back,
for weighty was the dread and majesty of the power of the word
of life that lived and burned as a fire in my heart.

When the first day of the week came,
I was moved by the Spirit of the Lord to go to Lorton, to speak to a priest named Fogoe,
who was preaching to the people in their worship house.
I stayed until he had finished,
and heard him affirm in his preaching that both he and they
were without the life of both the law and the gospel.
Then I spoke to him and said, "`With what then do you preach or pray,
since you are without the life of both the law and gospel?`"
But after a few words, he fell into a rage and stirred up the people,
and they fell upon me, and haled me out of the house, and beat me,
and the priest threatened to put me in the stocks.

Two weeks after this I was moved to go again to speak to the same priest at Loweswater,
the parish where I then lived.
When I came in, the people began to look at me and take notice,
but the priest bid them let me alone, and said that if I would be quiet,
he would discourse with me when he had finished.
So I stood still and quiet, waiting upon the Lord.
The priest prepared to go to prayer,
but when he saw that I did not put off my hat (for I could not join with him in his dead,
lifeless prayers), instead of going to prayer he fell a railing against me,
and said I should not stand there in that posture.
At last I spoke to him and asked him again, "`With what do you pray,
since you say you are without the life of both the law and the gospel?`"
But he continued calling out to the people to take me away.
At last, my father (who was present,
and was displeased with me for troubling their minister)
came himself and haled me out of the house,
and was very angry with me.
I stayed in the graveyard until the priest and people came out,
and then I got to him and spoke to him again.
But he soon began to be in a rage, and to threaten me with the stocks, and then got away.
Then I cleared my conscience to the people of what I had to say,
and so came away in great peace with the Lord.

Not long after, in the same year, I was moved of the Lord by His Spirit to go to Brigham,
to speak to a priest named Denton.
He was preaching in the steeple-house^
footnote:[Knowing the true church to be the spiritual body of Jesus Christ,
early Quakers were unwilling to use the term "`church`" to refer to a physical building,
and instead used the term "`steeple-house.`"]
to the people,
and his sermon (which he had prepared beforehand) had many false accusations, lies,
and slanders against Friends, and against the principles of truth.
I stayed until he was finished, and then spoke to him.
But I got little answer before some of his hearers fell upon me,
and beat me with their bibles and with their staffs all along out of the house,
and also out of the graveyard, so that the next day I was sore with the blows.
Then the priest commanded the constable to secure me and a Friend who was with me.
So the next day we were carried to Launcelot Fletcher of Tallentire,
who ordered a warrant to be written for us, and we were sent from constable to constable,
and then to the common jail in Carlisle, where I was prisoner twenty-three weeks.

While I was in prison, a burden came upon me for Scotland; but being a prisoner,
and not yet deeply acquainted with the way and work of the
Lord`'s power and Spirit in relation to such a service,
great was the exercise of my spirit which I was under.
For lack of experience and a clear understanding, I was swallowed up,
and for a time quite lost in the deep,
where great was the distress of my soul beyond utterance.
But the merciful God, by His powerful arm and the healing, saving Word of life,
did restore and bring up my soul out of the deep, where it was for a time buried.
Indeed, He renewed life and understanding,
and caused the light of His countenance to shine,
and the sweetness of His peace to spring up, so that I may truly say,
"`He caused the bones that He had broken to rejoice.`"
And when He had thus crushed and humbled me,
and let me see how He could make all things become as nothing again,
and so hide all glory from man, then in His goodness He revealed His own glory, power,
presence, and reviving life.
Yes, He so opened to my understanding His good pleasure,
that I gave up to it willingly in heart and spirit,
with all readiness and willingness of mind.

After being kept about twenty-three weeks in prison, I was given my liberty,
and came home and followed my outward calling that summer.
I grew more and more into the understanding of the mind and will of the Lord,
concerning those things which I had a sight of while I was in prison.
I kept to meetings,
and continued waiting upon the Lord in a true
travail of spirit for more acquaintance with Him,
and more enjoyment of His power and Word.
Thus I grew not only into an understanding,
but also into a degree of strength and ability fit to
answer that service to which the Lord had called me.

So, in the faith that stands in God`'s power, about the beginning of the eighth month,
1658, I took my journey into Scotland; and traveled in that nation about three months.
I was both in the north and west of it, as far north as Aberdeen,
and back again to Edinburgh, and down west to Linlithgow, Hamilton, Ayr,
and as far as Port Patrick; and back to Ayr and Douglass.
Our service was at their steeple-houses, their markets,
and other places where we met with people,
and sometimes at Friends`' meetings wherever there were any.
Our work was to call people to repentance,
out of their lifeless hypocritical profession and dead formalities (in which
they had settled in the ignorance of the true and living God),
and so to turn them unto the true light of Christ Jesus in their hearts,
that therein they might come to know the power of God,
and so come to know remission of sins, and receive an inheritance among the sanctified.
Feeling clear of that nation, we returned to England,
and came over the water to Bowstead Hill the first day of the eleventh month, 1658.

After my return home, I followed my trade again,
and kept to meetings until the third month, 1659,
after which I took shipping for Ireland.
For while I had been in Scotland,
a concern opened unto me in the truth to visit that nation, and while at home,
it grew mightily in me through the strength of the word of life.
For the Lord often filled and enriched my heart and soul with His glorious power,
and so sanctified and prepared me for whatever He set before me.
Often in spirit was I carried to Ireland,
and I had it sealed unto me that it was my place
to go into that nation to serve the Lord,
and to bear witness unto the Truth, and to call people to repentance,
and hold forth the way of life and salvation unto them.

I waited until the full season came (according to the blessed counsel of God,
in which I found His leading power with me, and also going before me),
and at the time before mentioned, I took shipping at Whitehaven,
and landed at Donaghadee in the north of Ireland.
I traveled to Lisburn, and so up to Lurgan, and to Kilmore in the county of Armagh,
and so up and down in the north for some time among Friends, and I had meetings.
Many people came to meetings,
and many were convinced and turned to God from the evil and vanity of their ways.
From there I traveled to Dublin, and then to Mountmellick, and so forward to Kilkenny,
and to Caperqueen, and Tullow, and to Cork, and Bandon; and back to Cork,
and then to Youghal, Waterford, Ross, and to Wexford.
I had meetings along the way as I traveled,
and according to that ability I received of God,
I was faithful and preached the truth and the true faith of Jesus Christ.

Having gone through the country,
and in the fear of God having published His name and truth as I had opportunity,
I was willing to return home to England.
For that purpose I came down to Carrickfergus; but before I got there,
it came upon me that I should return back again to Lurgan and Kilmore,
and from there to Londonderry.
So I sent word to appoint a meeting at Lurgan, and went on to Carrickfergus,
and got a meeting, where many people attended.
I cleared my conscience to them in the fear of the Lord, and then returned to Lurgan,
as I had appointed.
There I met with Robert Lodge, newly come out of England,
who also had it in his heart to go to Londonderry.
So Robert Lodge and I became concerned in one work, service, and travel together,
and were truly united in spirit, in the unity of the faith and life of Christ.
In the blessed unity and fellowship of the gospel of the Son of God,
we labored and traveled in that nation of Ireland for twelve months,
not often parting (though sometimes we were moved to
part for the service`'s sake for a little time,
and then to come together again).
The Lord gave us sweet concord and peace in all our travels,
and I do not remember that we were ever angry or grieved at one another all that time.

Thus we spent our time with diligent labor and hard travel, often in cold, hunger,
and hardships in that country, which was then uninhabited in many parts.
We were in prison several times--once in Armagh, once in Dublin, twice in Cork;
besides other abuses we received from many because of
our testimony which we had to bear for the Lord.
Having traveled and labored in the gospel together for twelve months,
and seeing many convinced and gathered to the Truth, we were clear of our service there,
and in the seventh month 1660, we took shipping for England at Carrickfergus.

At home I again returned to my outward calling, and kept diligently to meetings;
for it was still my delight to do so,
and while there to be diligent in waiting upon the Lord.
For I always found that therein I received an increase of strength, life,
and wisdom from the Lord.
And as I found any motion upon me from the Lord to go to any meeting abroad,
either in our county or any other, I went and cleared myself as the Lord gave ability,
and then returned again to my outward calling, and so to our own meeting,
where I delighted to wait in silence upon the Lord.
I loved our meetings very much because I found an inward growth thereby,
through the teachings and openings of His Spirit in my heart.
And when something did open in me to speak in our meeting, I gave up to it.
And though I was sometimes ready to quench the Spirit
through slowness or fear to speak in the Lord`'s name,
yet I grew over this by degrees,
and increased in faith and holy confidence more and more.

[.offset]
+++[+++The following epistle was written while in Ireland,
and is one of many such epistles that can be found in the unabridged
_Journal of the Life and Gospel Labors of John Burnyeat._]

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

In dear and tender love I do salute you all, who are faithful to the Lord,
without respect of persons.
In His life and love I feel you,
in which my heart is opened towards you--those with
whom I am daily refreshed and comforted in Christ Jesus,
the fountain and well-spring of life and refreshment.
Indeed, He is our Rock and daily refuge,
unto whom we flee and are safe in the day of storms and tempest, when the floods arise,
and the raging waves of the sea swell and beat.
Yet in the Light we have a safe hiding-place, and a sure and peaceable habitation,
against which these cannot prevail, as we abide faithful to the Lord therein.
His love towards us has abounded, and will abound,
as we abide in that to which His love does reach, which is His own Seed.
This Seed He has raised in us by His own power and outstretched arm,
and in it the issues of life and love are known and received.

Therefore, my dear friends, keep to it, and feel it continually!
Keep fresh and living and open-hearted, so that you may always be in the Life,
and that nothing may enter that would veil the Seed and oppress it.
As one who (with you) has been made a partaker of the rich and endless love of God,
I exhort you, dearly beloved ones, to continue in His love,
and to abide faithful in the Life, that death may not again pass over anyone.
Rather, may the Life which God has raised be felt, and may it rule in every one of us,
over him that has the power of death,
to the praise and glory of the One who has redeemed us.
In Him all comfort, strength, and refreshment are daily received,
for He is the life and strength of all who wait upon Him,
and is near to preserve all who are upright in their love towards Him.
In Him we have boldness, believing that neither tribulation, affliction, persecution,
nor distress shall be able to separate us from
the love of God which we enjoy in Christ Jesus.
And though the Lord may allow great difficulties
to come upon us (as it is at this day) to try us,
yet these cannot separate us from one another,
nor break our unity in the Spirit in which we feel and enjoy one another.

In this unity, my dear Friends, I have you often in my remembrance,
to my joy and gladness of heart.
For truly, you are often my rejoicing in the Lord,
when all other comforts are taken from me;
but only by that Seed in which I feel and enjoy you, in which our unity,
life and love stand, and in which I remain,

[.signed-section-closing]
Your brother in my measure received,

[.signed-section-signature]
John Burnyeat

[.signed-section-context-close]
Clanbrassil, Ireland, 4th of the Fourth month, 1660

--

[.asterism]
'''

[.emphasized]
It would be difficult to overstate the influence that John Burnyeat`'s
life and ministry had in the early Society of Friends.
After his death in 1690, George Fox wrote of him: "`He was a faithful friend and brother,
and an able minister of Jesus Christ... a true apostle of Jesus Christ,
who preached Him freely, both by sea and land.
He was an elder and a pillar in the house of God,
and a man much endued with the wisdom of God,
and in it had a care for the welfare of the church of Christ.`"

[.emphasized]
Like many of the early laborers that the Lord sent into His harvest,
John Burnyeat traveled and ministered unremittingly,
preaching to and encouraging the flock of Christ all over England, Scotland, Ireland,
Barbados, and the American colonies.
He was imprisoned many times for his testimony,
and suffered great injustices at the hands of persecuting priests and magistrates.
The last years of his life were spent in Ireland,
where he strengthened the hearts of Friends during what is now called the Williamite War,
a time of great chaos and bloodshed in the nation.
Those who knew him best described him as "`a precious instrument in the Lord`'s hand,
able and skillful in the ministry for the comforting of
His people... a cheerful encourager of them,
a dear friend and true brother, a diligent overseer and tender father,
a perfect and upright man in his day.`"
