[quote.epigraph, , Prov. 10:7]
____
The memory of the just is blessed.
____

[quote.epigraph, , Ps. 112:6]
____
The righteous shall be in everlasting remembrance.
____


== Chapter I.

[.chapter-synopsis]
* Account of John Burnyeat`'s convincement, 1653
* The various deep exercises of mind, which he and his early companions in religious profession passed through
* The gospel worship into which they were gathered, etc.

In the year 1653,
it pleased the Lord in his love and mercy to send his faithful servant George Fox,
with others of his faithful servants and messengers of
the Gospel of peace and glad-tidings,
whom he furnished with the eternal power of his word;
in the wisdom and power of which he proclaimed the day of the Lord unto us,
in this county of Cumberland, and the northern parts of England,
and discovered the right path of life unto thousands that were in error;
who sought the Lord, but knew not where to find him,
nor how to become acquainted with him, although he was not far from us.
But this blessed man George Fox, one of a thousand may many say,
and chosen before many thousands, was sent amongst us, in the power of the Most High,
filled with the strength of his word;
in the wisdom whereof he directed thousands unto the light and
appearance of Christ Jesus their Saviour in their own hearts,
that they might come to know him, and the glory of the Father through him,
in his appearance, and so come to believe in him with the heart,
and with the mouth to confess him unto salvation.
And blessed be the Lord, and the day of mercy in which he visited;
for he was pleased to make this labour of love effectual unto thousands,
amongst whom he sent his servants to labour,
and amongst whom it pleased the Lord to grant me the favour to
keep a share of the benefit of this blessed visitation;
whereby I came to be informed concerning the right way of the Lord,
and directed to the true light,
which the apostle was sent to turn people unto in his day,
and so from the darkness and from the power of Satan unto God and his blessed power,
which in my waiting in the light I received.
Through which deep judgment did spring in my soul,
and great affliction did grow in my heart;
by which I was brought into great tribulation and sorrow,
such as I had never known before in all my profession of religion,
so that I might say in spirit, it was the day of Jacob`'s trouble; for the God of Heaven,
by the light of his blessed Son which he had lighted me withal, which shined in my heart,
let me see the body of death and power of sin which reigned in me,
and brought me to feel the guilt of it upon my conscience:
so that I could say he made me, even as it were, to possess the sins of my youth.
And notwithstanding all my high profession of an imputative righteousness, and that,
though I lived in the act of sin, the guilt of it should not be charged upon me,
but imputed to Christ, and his righteousness imputed to me,
yet I found it otherwise when I was turned unto
the light which did manifest all reproved things.
Then I came to see that the guilt remained, while the body of death remained,
and while through the power thereof +++[+++we are]
led into the act of sin.

Then I saw there was need of a Saviour to save from sin,
as well as of the blood of a sacrificed Christ to blot out sin,
and of faith in his name for the remission of sins past.
Then began the warfare of true striving to enter the kingdom;
then Paul`'s state was seen,--to will was present, but to do,
power was many times wanting; then was that cry known,--
"`O! wretched man that I am, who shall deliver me from the body of this death,`"
and free me from the prevailing power of the law which remained in the members,
warring against the law of my mind, and which brought into captivity to the law of sin.
Then, when this war was truly begun, all my high conceit in my invented notional faith,
and my pretence and hopes of justification thereby, were overthrown;
so that all that I had builded for several years in my profession,
after the days of my youth,
(in which tender stirrings were in me after acquaintance with the Lord,
and the knowledge of him, and peace with him,) was seen to be but a Babel tower,
upon which God brought confusion; and so could it never be perfected to reach to heaven,
being out of the faith of his covenant,
and which never could bring truly to trust in his word, and rely thereupon;
but which led out into inventions, willing and self-acting,
though another thing was talked of.

Then seeing all my works confounded by the visitations of God,
and by the springing of the day from on high, which discovered things as they were,
seeing them all end at Babel, and the God of heaven bringing confusion upon them,
I was amazed, and fear beset me on every side;
and I began sometimes to fear I was undone for ever:
for that had entered my heart which had turned the fruitful field into a wilderness,
and made that, which I thought had been as the garden of Eden, a forest;
and so the day of God discovered all to be desolation, dryness, and a heath,
and brought my soul to a deep lamentation,
to the beginning of such sorrows as had never been known by me before.

Then did I lament and bewail myself many a time, and wish myself in a wilderness,
where I might neither meet with temptation nor
provocation from without to withstand in my spirit,
such was my weakness; for all the notion I had to talk of,
respecting imputation of the righteousness of Christ, being but my own,
which by his Spirit I had no seal for, and so was but a presumption,
I saw clearly it was my own invention; and so was but like Adam`'s fig-leaf apron,
in which he could not abide God`'s coming.
O! the woe that overtook me! the distress that seized me! the horror and terror
that sprung in my bosom! the poverty and want that my soul saw itself in,
through the springings up of the discovering light,
towards which the eye of my soul was turned!
And as this light did spring up, which the apostle of old wrote of,
it manifested all things,--not only the want that I was in, but also the reproved things;
and then sin became exceedingly sinful,
and the load and burthen of it became exceedingly grievous,
and all the pleasure of it was taken away from me and many more in that day.
Then we began to mourn after a Saviour, and to look for a deliverer,
and to cry for a helper and a healer: for the day of the Lord that made desolate,
had overtaken us, and the fire and sword that Christ brings upon the earth,
by which he takes away peace, had reached unto us;
and yet we knew not from whence it came,
though the burning and the judgment thereby were begun,
by which the filth was to be taken away.

And now in this distress, deep were our groanings and our cries unto the Lord,
which reached unto him; and he was pleased to hear, and show mercy:
for we often assembled together,
as the Lord`'s messengers (whom he sent amongst us) had exhorted us;
and we minded the light of Christ in our hearts, and what that discovered;
and in our spirits, we, through its assistance,
warred and watched against the evil seen therein;
and according to the understanding received, we waited therein upon the Lord,
to see what he would farther manifest, with a holy resolution to obey his will,
so far as we were able, whatsoever it cost us;
for this I know was the condition of many in that day.
We valued not the world, or any glory or pleasure therein,
in comparison of our soul`'s redemption out of that state,
and freedom from that horror and terror under
the indignation of the Lord which we were in,
because of the guilt of sin that was upon us;
and so being given up to bear the indignation of the Lord, because we had sinned,
we endeavoured to wait till the indignation would be over,
and the Lord in mercy would blot out the guilt which remained (that
occasioned wrath,) and would sprinkle our hearts from an evil conscience,
and wash us with pure water; that we might draw near with a true heart,
in full assurance of faith, as the Christians of old did. Heb. 10:22.

But, alas! we had not boldness,--for the living faith was wanting;
and a true heart we had not to draw near with,
and therefore could not have full assurance; but we were compassed with fears,
horrors and amazement: and yet we came to know that there was no other way,
but to dwell in these judgments, and wait in the way thereof;
understanding that we must be redeemed with judgment, as was said of Zion.
Isaiah 1:27: and so waiting therein, we began to learn righteousness,
and strongly to desire to walk therein,
and could no longer be satisfied with a talk thereof Thus waiting for
and seeking after the Lord (though greatly ignorant of him) in a deep
sense of our own unworthiness and unpreparedness to meet him,
because of the pollution of our hearts,
(which was seen by his light that did shine therein,) we were still bowed down in spirit,
and afflicted and tossed in soul, and not comforted; and our hearts were unstable,
like water,--the waves going over our heads, and our souls in jeopardy every moment,
and our faith so little, that we were ready to sink, like Peter,
often crying out in the danger.
In that distress and vale of tears wherein we walked,
our hearts became quite dead to the world, and all its pleasure and glory,
and also to all our former dead profession; for we saw there was no life in it,
nor help nor salvation from it, though some of us had tried it thoroughly.
We saw it was in vain to look to such hills or mountains for salvation.

And when we began to forsake all on both hands, seeing the emptiness of all,
both the glory, vanity, and pleasure of the world, and the dead image of profession,
which we had set up in our imaginations and inventions,
and had worshipped with our unprepared hearts and unsanctified spirits,
being slaves and captives to sin,
(as all must needs be that obey it in the lust thereof, according to Romans 6:16,)
I say, when we thus had a sight and sense of the insufficiency
of all we either had or could do to give ease,
help, or salvation, then we denied all; and as we had been directed,
we turned our minds unto the light of Christ shining in our hearts, and believed therein,
according to Christ`'s command, John 12:36:
and so we met together to wait upon the Lord therein.

Then began the profane to mock, scoff, and abuse us; and our very relations,
and old familiars, to be strange to us, and to be offended at us; and they did hate us,
and began to speak evil of us,
and did think it strange that we would not run with them to the former excess of riot,
as it was of old, 1 Pet. 4:4. Also the professors,
even such as we had formerly walked in fellowship with in our lifeless profession,
began to reproach and vilify us, and speak evil against us,
and charged us with error and schism, and departing from the faith;
and also began to reproach the light of Christ, as natural and insufficient,
and a false light, and a false guide.
Thus Christ, in his spiritual appearance, was reproached, vilified, slighted,
and undervalued, and was set at naught by the carnal professors of Christianity,
as he was in his appearance in the flesh by the Jews, the carnal professors of the law,
who saw not through the vail unto the end.
In this our weak state we were beset on every hand, and greatly distressed, tossed,
and afflicted, as poor Israel were, when the sea was before them,
and the Egyptians behind,--and their hope so little,
that they looked for nothing but death, and said to Moses,
"`Because there were no graves in Egypt,
hast thou taken us away to die in the wilderness,`" etc. Ex. 14:11.
Thus through many tribulations must the
kingdom be entered by all that strive rightly to enter,
according to Christ`'s command. Luke 13:24.

When we were thus in our deep fears,
and our minds not well acquainted with either striving,
(out of self,) in the light and seed of life that doth prevail,
or with true waiting or standing still out of our own thoughts, willings, and runnings,
which do not obtain, the Lord sent his servants, who had learned of him,
to direct us in what to wait, and how to stand still,
out of our own thoughts and self-strivings, in the light that doth discover;
who often did exhort us to abide and dwell in the judgment that we received therein.
And as we had been turned to the light, so were our understandings informed,
and we got to some degree of staidness in our minds,
Which before had been as the troubled sea,--and a hope began to appear in us;
and we met together often, and waited to see the salvation of God, which we had heard of,
that he would work by his own power.
After we had met together for some time, as we had seasons and opportunities,
and also sought the Lord with travailing spirits both night and day,
when we were at our callings, and upon our beds, (for we could not cease,
our souls were so afflicted,) when in our assemblies we were exercised in
the living judgment that sprung in the light in our souls,
and were looking for the salvation of God,--the
wonderful power from on high was revealed amongst us;
and many hearts were reached therewith, and broken, and melted,
before the God of the whole earth; and great dread and trembling fell upon many,
and the very chains of death were broken thereby, the bonds loosed,
and many souls eased and set at liberty; and the prisoners of hope began to come forth,
and they that had sat in darkness to show themselves.
And the promises of the Lord came to be fulfilled unto many,
spoken of by Isaiah the prophet.
Isa. 49:9, and Isa. 62:7, and 61:23;
and some taste of the oil of joy came to be witnessed,
and a heavenly gladness entered the hearts of many,
who in the joy of their souls broke forth in praises unto the Lord;
so that the tongue of the dumb, which Christ the healer of our infirmities did unloose,
began to speak and utter the wonderful things of God.
Great was the dread and glory of that power,
which in one meeting after another was graciously and richly manifested amongst us,
breaking, tendering, and melting our souls and spirits before the Lord.
Then our hearts began to delight in the Lord and in his way that he had cast up;
and with great fervency and zeal we began to seek after him,
and to meet oftener together than before,--our hearts
being affected with the presence of that blessed power,
which daily broke forth amongst us in our meetings,
through which we were greatly comforted, strengthened and edified;
for it was that same Comforter our blessed Lord promised he would pray the Father for,
and which the Father should send.
John 14:16 and 16:26.
This +++[+++Comforter] being come and received,
did teach us to know the Father and the Son;
and as we came into acquaintance with it, and into the unity of it,
we came to be taught by it, and so taught of the Lord,
according to that new covenant promise,--They shall be all taught of the Lord.
Isa. 54:13; John 6:4-5.

Then were our hearts inclined to hearken unto the Lord, and our ears,
which he had opened to hear, were bent to hear what the Spirit`'s teaching was,
and what He said unto the Church, who is the chief Shepherd and Bishop of the soul.
Thus were we gathered into a right gospel exercise and gospel worship by Him,
through whose name we had received remission of sins past,
and whose blood had sprinkled our hearts from an evil conscience,
and who gave the pure water that washed and made clean.
So that with true hearts many began to draw nigh unto God in the full assurance of faith,
as the ancient saints did and were accepted, and had access by that one Spirit,
by which we came to be baptized into one body, and so came to drink into one Spirit,
and were refreshed, and greatly comforted;
and grew up together in the mystery of the gospel fellowship; and so we worshipped God,
who is a Spirit, in the Spirit received from him, which is the gospel worship,
according to Christ`'s appointment. John 4:24.
Then we came to see over all the worships in the world,
which were set up either by imitation, or man`'s invention;
and we saw it to be in vain to worship God,
and teach for doctrines the commandments of men, as our Lord had said.
Matt. 15:9; and therefore were we constrained to withdraw from them,
and also (many of us) to go and bear witness against
them in their invented and traditional worships,
where they were ignorant of the life and power of God.

Thus being gathered by the Lord Jesus Christ,
that great Shepherd and Bishop of our souls, we became his sheep,
and did learn to know his voice, and to follow him; and he gave unto us eternal life,
and manifested the riches of his grace in our hearts,
by which we were saved through faith, and delivered from that wrath, fear, and terror,
which had been so weighty upon our souls,
and in measure from the power of that death which had reigned,
and made us miserable and wretched; and we came to partake of that life,
wherein the blessedness doth consist.
So then the Lord becoming our Shepherd, he taught us,
and led us forth into green pastures,
where we did feed and rest together with great delight.
O! the joy, the pleasure, and the great delight,
with which our hearts were overcome many times, in our reverent and holy assemblies!
How were our hearts melted as wax, and our souls poured out as water before the Lord,
and our spirits as oil, frankincense and myrrh,
offered up unto the Lord as sweet incense,
when not a word outwardly in all our assembly has been uttered!
And then did the Lord delight to come down into his garden,
and walk in the midst of the beds of spices; and he caused the north wind to awake,
and the south wind to blow upon his garden, and the pleasant showers to descend,
for the refreshing of his tender plants, that they might grow still more and more.

And now unto them that had known the night of sorrow, was the joyful morning come,
according to that ancient experience of David.
Ps. 30:5; and such as had been in the foregoing deep afflictions, tossings,
and distresses, came to witness the fulfilling of that great gospel promise;
"`O! thou afflicted, tossed with tempest, and not comforted;
behold I will lay thy stones with fair colours, and lay thy foundations with sapphires:
and I will make thy windows of agates, and thy gales of carbuncles,
and all thy borders of pleasant stones.
And all thy children shall be taught of the Lord;
and great shall be the peace of thy children.
In righteousness shall thou be established; thou shall be far from oppression;
for thou shall not fear, and from terror,
for it shall not come near thee,`" Isa. 54:11-14.

Thus came we by Him to be gathered into covenant with God,
and lowliness the fulfilling of the promises of God,
in whom all the promises are yea and amen;
and so came to sit together in heavenly places in him,
and to feed upon the heavenly food, the bread of life, that came down from heaven,
which Christ the heavenly Shepherd did give unto us;
who had gathered us from amongst the shepherds that fed
themselves with temporal things from the flock,
but knew not how to feed the flock with spiritual food, for they had it not.
Now we, coming to be acquainted with the power of the Lord Jesus Christ in our hearts,
became great lovers of it, and delighted in the enjoyment thereof;
having already counted all things but as dross and dung
in comparison of the excellency that we saw therein;,
and therefore were willing to suffer the loss of all, that we might win him,
as it was with the apostle of old.

And blessed be the Lord, many obtained their desire;
they found their beloved,--met with their Saviour,--witnessed his saving health,
by which their souls were healed; and so became his flock and family,
or household of faith.

Then as his children and blessed family,
we still continued to meet together twice in the week, or oftener;
and being gathered together in his name and holy fear, his promise we witnessed,
according to Matt. 17:20, that he was in the midst of us,
and did honour our assemblies with his heavenly power and presence;
and that was our great delight,
and the sweetness of it did wonderfully engage our souls to love him,
and our hearts to wail upon him;
for we found the ancient experience of the Church to be true,
as testified in the Scripture, "`Because of the savour of thy good ointments,
thy name is as ointment poured forth; therefore do the virgins love thee.`"

Thus growing into this experience of the goodness of the Lord, and of the sweetness,
glory, and excellency of his power in our assemblies,
we grew in strength and zeal for our meetings more and more,
and valued the benefit thereof more than any worldly gain; yea,
it was unto some more than our appointed food.

Thus continuing,
we grew more and more into an understanding of divine things and heavenly mysteries,
through the openings of the power which was daily amongst us,
which wrought sweetly in our hearts, which united us more and more unto God,
and knit us together in the perfect bond of love, of fellowship and membership.

So that we became a body compact, made up of many members,
whereof Christ himself became the head; who was with us, and did rule over us,
and further gave gifts unto us,
by which we came still to be enlarged and were further opened,
that we might answer the end for which he had raised us up, and had so far blessed us,
and sanctified us through his word which dwelt in our souls.
So we keeping still in our zeal, and unto our first love, and keeping up our meetings,
and not forsaking the assembling ourselves together, (as the manner of some was of old,
whose example the apostle exhorted the saints not to
follow,) the Lord`'s power continued with us,
and was renewed daily in our meetings; by the openings of which,
our understandings were still more enlarged in the
mysteries of life and the hidden things of God;
so that many through the favour of God, grew in their gifts, and had their mouths opened,
and thus became instruments in the Lord`'s hand to bear witness unto the world,
of the day of the Lord which was broken forth again,
even of the great and notable day Joel had prophesied of, and Peter bore witness unto.
And they were also sent to bear witness against the world, and its evil deeds,
with all the false religions with which mankind had
covered themselves in the darkness and apostacy,
which had spread over them, and now was seen and discovered by the light and day of God.

Thus the Truth grew, and the faithful in it, and many were turned unto God; and his name,
and fame, and glory, and power spread abroad,
and the enemy`'s work and kingdom were discovered,
and struck at by the Lamb and his followers.
This made him begin to rage, and stir up his instruments to oppose the Lord`'s work,
and with all subtlety to hinder people from following the Lamb,
or believing in his light.
So with pen, and tongue, and hands also, the beast and his followers began to war,
and +++[+++fell]
to whipping, and scourging, and prisoning, and spoiling of goods, with reproaching,
belying, and slandering the way of truth;
with all that they could do to hinder the exaltation of
the kingdom of the Lord Jesus Christ,
blaspheming his light and his power,--calling his light natural, insufficient,
a false guide, with many reproachful names; and calling his power diabolical,
and the operation and blessed work of it,
which was both to the renewing of the spirit of the mind,
and also to the reformation of the conversation from debauchery, wickedness,
unrighteousness, and witchcraft; even like them of old,
who said Christ cast out devils by Beelzebub the prince thereof But by this time,
they that kept faithful to the Lord, and his light and Spirit in their hearts,
who had come forth through the deep tribulation, as before related, were confirmed,
settled and satisfied, and established in the life that was manifested;
in which they saw over death, and all men`'s profession, and where they were,
and what they fed upon, who cried out so against the light and power of Christ,
which was thus with us, and wrought thus in us in our meetings;
and how they were but mocking at the same that those mocked at,
spoken of in the second of the Acts,
when they thought the Apostles were full of new wine, and so drunk.

The high professors of our days being ignorant of the Holy Ghost,
through their resisting of it, blasphemed the life and power, and at the best,
did but feed upon the tree of knowledge.
For this I still right well remember, that in my waiting upon the Lord,
in the deep distress and weighty judgment that was upon my soul,
to see if he would appear and break through,
and open and give relief from that which kept me down as "`bars of iron,
so that I could not arise or ascend, nor have access,
although out of the deep I cried unto him for deliverance; I say, I can remember,
that in the first notable in-breaking of the power of God upon my soul,
or pouring forth of the Holy Ghost upon me,
the first opening in the same unto me thereby, was,
a true discovery of the tree of knowledge in the mystery,
upon which I saw I had been feeding with all the carnal professors of religion;
and how we had made a profession of that which we had no possession of;
but our souls were in the death,
feeding upon the talk of that which the saints of old did enjoy;
and therein I saw there was no getting to the tree of life,
that our souls might be healed by the leaves of it, and so feed upon the fruit thereof,
that we might live for ever.
But as there was a coming under the wounding, slaying sword that Christ brings,
by which the life of the old man comes to be destroyed, who would still live in sin,
and serve it, and yet profess faith in Christ, and to be his servant,
(which is impossible, according to Christ`'s own saying,
"`No man can serve two masters,`" etc.
Matt. 6:24) I saw there was no remedy,--either I must be
buried by that fiery baptism of Christ with him into death,
or else there could be no rising with him into newness of life;
there might be a rising into newness of profession, notion and words;
but that would not do, it was newness of life I must come to,
the other I had tried over and over.
I saw I must die with him, or be planted with him in the likeness of death, that is,
die unto sin, if ever I came to be planted with him in the likeness of his resurrection,
and so live unto God, according to Romans the sixth.

Then when things thus opened in me, I clearly saw we had all been deceived,
in thinking while we lived in the flesh, and after the flesh, and so in the death,
and feeding upon the tree of knowledge, which was forbidden for food,
we might make such a profession as might bring us to reap life everlasting.
But I soon saw, such as a man lived after--such as a man sowed, such should he reap,
and not what a man professed, or what he talked of;
and then I was willing to bow to the cross,
and come under the fiery baptism of the Spirit,
and let that which was consumable be destroyed, that my soul might be saved,
and come to possess that which would endure and abide, and which could not be shaken.
Thus were the heavens shaken also, as well as the earth,
that that which could not be shaken might remain,
(according to Heb. 12:27) and so that which condemned the evil fruits of the flesh,
(as they were owned by us to be in our profession,) both in our loose conversation,
and also in the desires of our hearts, and fleshly lusts which therein sprang,
even the same light and true witness did discover and condemn our fleshly
profession of religion in that same nature and mind which brought forth evil,
or in which evil did dwell and rule; and so came our heaven to be shaken,
and our covering and garment to be taken away, and we left comfortless and naked,
destitute and without a habitation.
And then we saw our sacrificing and our sinning to be alike in the sight of God;
for our prayers were rejected, and all loathed,
because both were done in one nature and from one and the same seed and corrupt heart;
and, therefore, it came to be with us as with Judah of old,
as may be read Isa. 1 and Isa. 66:3.
where the Lord told Judah, their killing an ox, their sacrificing a lamb,
their offering an oblation and burning incense, was as the slaying of a man,
cutting off a dog`'s neck, offering swine`'s blood, and blessing an idol.
And thus we saw, for want of righteousness, and keeping the commandments of the Lord,
and forsaking of our own ways, and that which was evil,
our religion was loathed by the Lord, and we rejected in all our doings,
and left in desolation and barrenness; for whatever we might pretend,
that true saying must stand, a good tree cannot bring forth bad fruit,
nor a bad tree good fruit; the tree is known by its fruit.

Thus things opened wonderfully in us,
and we saw not only common sins which all confess so to be,
though they live in them,--but also the hypocrisy and
sinfulness of the professors of religion,
even in their religion, which was performed out of the true spirit of grace and life,
which in the mystery is the salt that every gospel sacrifice is to be seasoned withal,
according to the example in the figure.
Therefore were we commanded to withdraw, and be separated in our worship,
and to wait to have our hearts sanctified, and the spirit of our minds renewed,
that we might come before him with prepared vessels.
For we soon learned to see this, that it must be true in the substance, as in the figure;
all the vessels of the tabernacle were to be sanctified, consecrated, or made holy.

Therefore did we come out from among such in their worship, who lived in uncleanness,
and pleaded for sin, which made unholy; and we met together,
and waited together in silence: it may be, sometimes, not a word +++[+++was uttered]
in our meetings for months; but every one that was faithful,
waited upon the living word in our own hearts, to know sanctification thereby,
and a thorough cleansing and renewing of our hearts and inward man.
And being cleansed and made meet,
we came to have a great delight in waiting upon the word in our hearts,
for the milk thereof, which Peter speaks of 1 Pet. 2:2; in our so waiting,
we received the milk, or virtue thereof, and grew thereby,
and were fed with the heavenly food that rightly nourished our souls;
and so we came to receive more and more of the
Spirit of grace and life from Christ our Saviour,
who is full of it, in whom the fulness dwells.
In the power thereof we worshipped the Father, who is a Spirit,
and we waited upon the teachings of his grace in our hearts;
and he taught us thereby to deny ungodliness and worldly lusts, and to live righteously,
godly, and soberly in this present evil world.

Thus we came to know the true teacher, which the saints of old did witness,
as saith the Apostle, Titus 2:12, and therefore wanted not a teacher,
nor true divine instructions, though we had left the hireling priests,
and also other high-flown notionists, and sat down together in silence;
for this was our desire,
to have all flesh silenced before the Lord and his power both in our own hearts,
and from without.
And as we thus came into true silence and inward stillness,
we began to hear the voice of him, who said, he was the resurrection and the life;
and he said unto us, Live, and gave unto our souls life;
and this holy gift which he hath given,
has been in us as a well of water springing up into eternal life,
according to his promise; and, therefore,
hath it been our delight all along to wait upon it,
and draw nigh with our spirits unto it, both in our meetings, and also at other times;
that we might both be taught and saved by it,
for by it the saints were saved through faith, etc. as Paul wrote unto them. Eph. 2:8.
