== Chapter II.

[.chapter-synopsis]
* His diligence in attending meetings
* The delight and profit experienced in keeping near to the power of Truth
* Is moved to speak in the public places of worship at Aspetry, Lortont Brigham
* Is committed to Carlisle jail.
* In 1658 travels into Scotland; and in 1659 into Ireland.

From the year 1653, as before hinted,
in which year I was convinced of the blessed truth and way of life eternal,
unto the year 1657,
I was not much concerned abroad in travels upon the account of the Truth,
save only to visit Friends that were prisoners for the Truth`'s testimony;
but being mostly at home, followed my outward calling.
I was very diligent to keep to our meetings, being given up in my heart thereunto,
for I found great delight therein; and many times, when one meeting was over,
and I at my outward labour, in which I was very diligent also,
I did in my spirit long for the next meeting-day,
that I might get to the meeting to wait upon the Lord with the rest of his people.
I can also with safety say, that when I was there, I was not slothful,
but in true diligence set my heart to wait upon the Lord,
for a visitation from him by the revelation of his power in my soul;
and as I waited in diligence, patience, and faith, I can say this for the Lord,
and on his behalf, (with many more witnesses,) we did not wait in vain:
he suffered not our expectation to fail;--everlasting glory, and honour,
and praise be to his worthy and honourable name forever!
The very remembrance of his goodness and glorious power,
revealed and renewed in those days, overcomes my soul.

Thus in diligence waiting, and the Lord in mercy visiting by his power in our hearts,
my soul was daily more and more affected with the glory,
and excellency and sweetness of it,
and with the holy dread with which it filled my heart,--for that became pleasant;
and then my spirit was bent to keep near unto this power,
and to dwell in that holy fear which the Father thereby placed in my heart.
Then I came to see what David exhorted to, in the second Psalm,
when he bid the kings and judges of the earth be wise and learned; and further said,
"`serve the Lord with fear, and rejoice with trembling.`"
O! the bowings of my soul! the pleasant dread that dwelt upon my spirit,
and the reverent tremblings that came over my heart, which filled it with living joy,
as with marrow and fatness!
Then could I say in my heart with David, I will wash my hands in innocency,
and compass thine altar, O Lord.
O! the pleasant drawing near, and that not unprepared,
unto the altar of the Lord by many, whose hearts were filled,
and their souls and spirits anointed with the true anointing from the Holy One,
which John speaks of in his first epistle,
which is the substance of what was figured out in that
ointment which Moses was commanded to make.
Ex. 30:25, with which all the vessels of the tabernacle were to be anointed.

When my heart was thus fitted, filled, and furnished,
as it was many a time in our holy assemblies, with many others, I know,
who sat under the same dread and power with me, (for our temple and tabernacle,
in which we worshipped, as children of the new Jerusalem, was but one,
even the Lord God and the Lamb, as John says.
Rev. 21:22) I say, when my heart was thus fitted and filled,
then did I endeavour to keep down my spirit to the meltings of it;
and great was the care of my soul that I might in no ways miss or abuse this power,
nor let up a wrong thing into my mind, to be betrayed thereby.
I knew, if I kept down all that was wrong,
sound wisdom and a true understanding would be grown into,
even of those mysteries that the world was ignorant of; for the Son of God being come,
it was he that gave the understanding, to know him that is true, as John said of old,
in his first Epistle, and he was made unto us wisdom, as Paul said, 1 Cor. 1:30.
I often observed, and that with great care and diligence,
how it was with my own spirit in those blessed and pleasant seasons,
wherein the Lord did so wonderfully appear amongst us,
and filled our hearts with the glorious majesty of his power, whether +++[+++my spirit]
was subject, as it ought to be, or no: for I clearly saw the enemy might beguile,
and lead up into the heights, and into pride and vain-glorying in that,
which the soul might soon be deprived of, if it kept not humble;
for it is the humble the Lord teacheth, and the meek he guides in judgment.

Thus, in the greatest enjoyments, I saw there was need of a care and fear to be kept up;
for as those that grew sluggish, idle,
and careless in waiting for the power in a meeting,
did sit without the sense of it in a dead, dry, barren state;
even so such as were not diligent to keep low, humble, and tender,
and so to mind the nature of the working of the power,
and the state of their own spirits under the power`'s exercise,
and also to watch against the enemy`'s subtlety,
(who lays in wait to betray,) these might easily be led
aside out of the way of the power by the stranger,
even while the power was working, and the joy was in the heart.

Thus for want of true fear and care, might the soul come to a loss ere it be aware;
and I believe some have so done, and can scarcely find the reason of it.
Great is the mystery of godliness, it may truly be said,
even the great mystery which Paul writes of in the first of Colossians,
"`Christ in you the hope of glory;`" and as he is there,
great is the mystery of his working by his Spirit,
to the opening and clearing of the understandings of all who rightly wait upon him.
It is the soul which is in the sanctification and oneness with the life and true unction,
that comes to be a priest, and so of the royal priesthood,
chosen and elected in God`'s covenant,
and that comes rightly and lawfully to eat of those holy things,
and so to partake of the sanctified holy food.
This I did observe;
and therefore the stranger is not to come nigh and this was signified
in the figure--`" The stranger was not to eat of the passover.`"
Ex. 12:43; and the command of God was to Aaron by Moses,
"`That no stranger should eat of the holy things,`" etc.,
Lev. 22:10.

And again Solomon saith, "`The heart knoweth his own bitterness,
and a stranger doth not intermeddle with his joy.`" Prov. 14:10.
Much might be said further,
but this is the matter,--it is wisdom for the heart that hath
known its own bitterness in the judgment and distress,
and through it hath come to peace and joy,
to keep therein and not to let that which would have no share with it,
come to intermeddle with the joy; for if it do,
it will soon overthrow the joy of the soul, and bring to another state;
and then it will have no more pity in the day of distress, than the Jews had of Judas,
when they bade him to look to it, what was that to them,
after he had betrayed his Master.

I continued, as I have said before, for these four years,
mostly following my outward calling,
and attending and waiting upon the Lord in the workings of his holy power in my heart,
both in meetings and at other times, wherever I was or whatever I had to do,
I found that as my heart was kept near the power, it kept me tender, soft, and living.
And besides I found, as I was diligent in eyeing it, there "`was a constant sweet stream,
that ran softly in my soul, of divine peace, pleasure, and joy,
which far exceeded all other delights and satisfactions;
and this became the great engager of my soul to watch with such diligence,
for I found the love of God to constrain.
And furthermore, I observed, that if I neglected it,
or let my mind out after anything else more than I ought, and so forgot this,
I began to be like a stranger;
and I saw that I soon might lose my interest in these riches and treasure,
and in the true common-wealth of God`'s spiritual Israel,
which Christ had purchased for me, and given me the earnest of to inherit.
Thus being mindful of the opening wisdom of God, which was from above, and heavenly,
and not from below, earthly, I was preserved, and helped,
and succoured in the needful time.
And because of the blessings and rich mercies of the Lord which my soul enjoyed,
I was willing to serve him in what I might;
and willingly received upon me a share of that concern which became proper for me,
with others, to take upon us in the church;
that I might be helpful in all necessary things.

Thus I went on in the holy fellowship of the gospel of life and salvation,
with the rest of my brethren and sisters;
and many joyful days we had together in the power of the Holy Ghost,
which was richly and graciously continued amongst us, and daily poured out upon us;
so that we still grew in favour with God, and in unity one with another,
and received daily strength from the Lord,
and an increase of his Divine wisdom and Spirit, which did greatly comfort us.
In this our pleasant state I do well remember, my heart was satisfied,
and settled into content, where I was willing to abide.
But the Lord who had so dealt by me in mercy, as I have said,
began to stir in my heart by his Spirit,
to arise and go forth in the strength of his word,
and declare against the hirelings who fed themselves and not the people,
and who kept the people ignorant of those good things,
of which he had made me and others witnesses.
And when the word of the Lord came unto me with this message,
it became a great exercise to me; and I would willingly have shunned it,
and have dwelt in that ease, peace, and pleasure into which the Lord had brought me;
but there was none, but in obeying the Lord, and giving up to do his will.
This I soon came to know, for I was sure it was the word of the Lord:
and then I yielded in spirit, and longed for the day that I might clear myself,
and be eased of the charge that was upon me;
for weighty was the dread and majesty of the power of the word of life that lived and,
as a fire, burned in my heart, so that I could not stay.

When the first-day of the week came, in obedience to the word of the Lord,
I went to Aspetry, the place which the Lord set before me,
to speak to one Warwick a priest.
When I came, he was preaching in their bell-house, who,
soon after I came in with a friend with me,
began to put forth some subtle questions to provoke us to speak,
that he might have an opportunity to cause us to be haled out, and sent to prison;
but I resolved not to mind his temptation, but to wait upon the Lord.
When he could not prevail with his questions to get his end upon us,
he spoke to the constable to put us forth: who answering, bid him go on, and said,
"`they do not disturb us,`" etc.
Then the priest went on and finished with his sermon.

When he had done, I began to speak to the people; but the priest got away,
and the people hurried me out, and kept me and the priest asunder,
that I got not to speak to him that forenoon.
So I came away with my friend, and thought to have returned home;
but immediately after I got out of the town,
the wrath and displeasure of the Lord in his word sprung dreadfully in my heart,
and a dreadful cry was in me from the same,--cursed is
he that doeth the work of the Lord negligently, etc.
Then I saw how I had let in a fear upon me,
in which I had shunned the priest and spared him,
for fear I should be sent to prison for speaking to him, the law being such at that day,
that whosoever did disturb a minister, as they termed it, should be sent to prison.
When I found out my weakness in this, that I had spoken to the people,
and spared the priest, against whom I was sent to cry, then was I sorely afraid,
and my heart was filled with horror, and a sore cry +++[+++prevailed]
in me still, cursed is he that doeth the work of the Lord negligently, etc.
Then I knew not what to do, for the wrath of God was upon me;
and another cry from the same word was sounded in my heart, saying, Babylon hath sinned,
all ye that bend the bow, shoot at her; spare no arrows, for she hath sinned, etc.
When it was thus with me, and I saw that I had not been faithful,
but had missed my service, after I had come so far as the common above Plumland,
I sat me down, and there I mourned before the Lord, whom I had so grieved;
and humbly desired of the Lord,
that he would but grant me liberty to go again to clear myself,
that I might come into peace with him again; and then let outward life or liberty go,
I did not value.
So waiting upon him in this humble bowed frame of spirit,
the word of life arose in me again, and opened my heart,
and sealed to me that I might go.
Then I arose with boldness, and went with speed, till I came at the worship house:
and the priest was preaching again in the afternoon, so I went in and stood before him,
till he had done; and then was my heart filled with peace,
and I resolved in the name of the Lord not to spare,
but to speak the word of the Lord faithfully, whatever I might suffer for it;
for in comparison thereof, I valued neither life nor liberty.
So when he had done, I spoke unto him what the Lord put in my mouth;
he immediately got away and gave me no answer, but I followed him so quickly,
and cried out after him, that he turned again to me in the graveyard;
and then I cleared my conscience to him, and a great dispute we had,
for I did not spare him; at last he went away, and would stay no longer.
Then I spoke to the people, and cleared my conscience amongst them;
after which I came away in peace, and my heart was filled with unspeakable joy,
and my soul with gladness.

Then I saw it was good to be faithful to the Lord, and to trust in him,
and to obey his voice;
and I came to feel and see more and more the woeful and
dreadful state that the priests and hirelings were in,
who for their own earthly gain made merchandise of people.
Although they were defended by the laws of men,
yet I found they were in the transgression of the laws of God, and so were in Cain`'s,
Korah`'s and Balaam`'s ways, in envy, and even gainsayers of the truth,
and lovers of the wages of unrighteousness, such as Peter and Jude wrote of,
and Jude cried woe against.
2 Peter 2:15, Jude 10, 11, 12.

Sometime after, I was moved by the Spirit of the Lord to go to Lorton,
to speak to one Fogoe, a priest, who was preaching to the people in their worship house;
and I stayed till he had done.
He affirmed in his preaching to the people,
that both he and they were without the life of both the law and the gospel.
Then I spoke to him, and questioned him what he had to preach, or to pray with,
who was without the life of both the law and gospel?
But after a few words, he fell into a rage and stirred up the people,
and they fell upon me, and haled me out of the house, and beat me,
and the priest threatened to put me in the stocks.
So I came away;
and that day two weeks I was moved to go again
to speak to the same priest at Loweswater,
the parish where I then dwelt.

When I came in, the people beginning to look at me, and take notice,
the priest bid them let me alone; if I would be quiet he would discourse with me,
when he had done.
So I stood still and quiet, waiting upon the Lord: the priest prepared to go to prayer,
but when he saw that I did not put off my hat (for I could not so do,
because I could not join with him in his dead lifeless prayers,)
instead of going to prayer he fell a railing against me,
and said I should not stand there in that posture.

At last I spoke to him, and asked him, what he had to pray with,
who was without the life of both the law and the gospel;
but he continued calling out to the people, to take me away; so that at last,
my father being there, and displeased with me for troubling their minister,
came himself and haled me out of the house, and was very angry with me.
I stayed in the graveyard till the priest and people came out,
and then I got to him and spoke to him again; but he soon began to be in a rage,
and to threaten me with the stocks, and got away.
Then I cleared my conscience to the people, of what I had to say,
and so came away in great peace with the Lord.

Not long after, in the same year, I was moved of the Lord by his Spirit to go to Brigham,
to speak to one priest Denton; he was preaching in the steeple-house to the people,
and his sermon, which he had beforehand prepared, had many false accusations,
lies and slanders against Friends, and the principles of truth.
I stayed till he had done, and then spoke to him, but got little answer;
but immediately some of his hearers fell upon me, and beat me with their bibles,
and with a staff or staves, all along out of the house, and also out of the graveyard,
so that the next day I was sore with the blows;
and then the priest commanded the constable to secure me and a Friend that was with me,
and next day did cause him to carry us to Launcelot Fletcher of Tallentire,
who ordered a warrant to be written for us, and so sent us from constable to constable,
to the common jail, in Carlisle, where I was prisoner three-and-twenty weeks.^
footnote:[In the year 1657. [.book-title]#Besse`'s Sufferings,# vol. i. fol. 128]
And when I wrote a paper to the priest, wherein I answered his false accusation,
and sent it to him by a Friend, he would not read it, but, as I was told,
put it in the fire and burnt it.

+++[+++The following appears to be the Address alluded to.]

[.embedded-content-document.address]
--

=== For the Priests in Carlisle, and their followers.

Ye which stand up to teach the people, behold your flock which ye teach,
and see what is brought forth among them; such fruits,
as were never brought forth among them that were taught of God, nor by any that he sent.
But the small effect your teaching doth bring forth for God, evidences to your face,
that ye are not sent by him, but run, and the Lord doth not send you;
therefore the people profit nothing by you,
but the fruits of unrighteousness still remain among them,
and they are not turned to God, and out of their sins by all your teaching.
For persecution is found in some, and pride and drunkenness, and mocking, and scorning,
and reproaching of them who fear God, who appear among them that follow you.
Oh consider it, you who take in hand to teach these people;
did ever any of the ministers of Christ own such for Christians?
Consider it; was persecution found among the saints?
Or did they imprison any?
Show one example in the Scriptures for it, if there be any.
Or did the apostles own them for Christians who did persecute?
were not they enemies to the truth, who did persecute and imprison?
And was it not the saints, that the persecution rose against?
And did not the apostles suffer persecution?
Were not they enemies to Christ who persecuted them?
And are not they enemies to Christ who persecute now?
Oh! that you would but consider of it, and see what generation ye are of,
and what fruits ye bear! whether ye and your followers bear
the fruits of the ministers of Christ and the saints,
or ye bear the fruits of the false prophets,
and of the rude multitude and persecuting generation who persecuted the righteous.

For from the beginning the righteous were persecuted, even from Abel;
but we never read that the righteous persecuted any, but were always sufferers.
So it is evident, that they who persecute and imprison,
are shut out of the life of them who gave forth the Scriptures,
and are found in their steps who were enemies to the truth,
and persecuted those who lived in the life of it.
Ye, that take in hand to teach the people of this town, look upon your flock, and see,
what fruits are brought forth by some of them.
Yet for all this your teaching of them,
you have not brought them to so much moderation and love, as was in Felix,
who commanded a centurion to keep Paul, and to let him have liberty,
and that he should forbid none of his acquaintance to minister or come to him.
But we find not so much moderation or love among you, who say, ye are Christians;
for we are kept in prison, and our friends are hindered to come to us.
Oh be ashamed of your flock, ye teachers, that for all your teaching,
ye have not brought them so far into moderation and love, as they were,
who persecuted the apostles and saints;
and so they must needs be far short of being true Christians.

But you are bad examples to them herein; for many of you, who are teachers,
do cause the innocent to be cast into prison, and persecuted;
and so manifest yourselves by your fruits,
not to be in the same life the apostles were in, who always suffered,
and never persecuted any.
So consider well of this, ye teachers, that your flock is not a flock of sheep and lambs;
but the nature of wolves appears among them,
whose mouths are open against the innocent, who live in the nature of the lamb.
Are ye not therefore of those, who run, and the Lord never sent you?
Who do not profit the people at all, who from time to time stand up to teach them,
and yet they remain in their old nature, not changed from their former conversation.
Oh cease!--seeing no fruit is brought forth to God by all your labour.
Is it not for the love of money that you teach?
And do ye not seek after the fleece more than the flock?
Do ye not go from one place to another for rewards?
Let that of God in your consciences answer.
Is not this it, which blinds your eyes, that ye do not see what generation you are of,
when you read the Scriptures?
Which testifies who they were who persecuted,
and who they were who suffered persecution then, in the apostle`'s days.
Search the Scriptures, and see whether the persecutors, or they that were persecuted,
were the saints of God in those days?
And whether the way be not the same now in these our days, yea or nay?

From a lover of your souls,
who is a sufferer in outward bonds in the common jail in Carlisle, for the Truth`'s sake.

[.signed-section-signature]
John Burnyeat.

--

While I was in prison, something came upon me for Scotland; but being a prisoner,
and not yet deeply acquainted with the way and work of the
Lord`'s power and Spirit in relation to such a service,
great was the exercise of my spirit which I went under;
and for want of experience and a clear understanding,
I was swallowed up and for a time quite lost in the deep;
where great was the distress of my soul beyond utterance.
But the merciful God by his powerful arm, and healing, saving Word of life,
did restore and bring up my soul out of the deep, where it was for a time buried;
and he renewed life and understanding, and caused the light of his countenance to shine,
and the sweetness of his peace to spring up; so that I may truly say,
he caused the bones that he had broken to rejoice.
And when he had thus crushed and humbled,
and let me see how he could make all things become as nothing again,
and so hide all glory from man, then in his goodness he revealed his own glory,
and power, and presence, and reviving life,
and so opened to my understanding his good pleasure,
which with all readiness and willingness of mind I gave up to, in my heart and spirit.

After being kept about three-and-twenty weeks in prison, I had my liberty;
and I came home, and followed my outward calling that summer,
and grew more and more into the understanding of the mind and will of the Lord,
in that which I had a sight of while I was in prison.
And keeping to meetings, and waiting upon the Lord in a true travail of spirit,
after more acquaintance with him, and more enjoyment of his power and word,
I grew not only into an understanding,
but also into a degree of strength and ability fit to answer that service,
which the Lord had called me unto.

So, in the faith that stood in God`'s power, about the beginning of the eighth month,
1658, I took my journey into Scotland; and travelled in that nation about three months,
and was both in the north and west of it, as far north as Aberdeen,
and back again to Edinburgh, and down west to Linlithgow, Hamilton, Ayr,
and as far as Port-Patrick; and back to Ayr and Douglass:
and our service was at their steeple-houses, and markets, and other places,
where we met with people; and sometimes at Friends`' meetings, where there were any.
Our work was, to call people to repentance,
out of their lifeless hypocritical profession and dead formalities,
wherein they were settled in the ignorance of the true and living God;
and so to turn them unto the true light of Christ Jesus in their hearts;
that therein they might come to know the power of God,
and so come to know remission of sins, and receive an inheritance amongst the sanctified.
Being clear of that nation, we returned into England,
and came over the water to Bowsteadhill the first day of the eleventh month 1658.

After my return home, I followed my trade again until the third month, 1659;
and then took shipping for Ireland,
according to what had been opened unto me in the truth, when I was in Scotland;
+++[+++which opening]
grew mightily in me through the strength of the power and word of life,
while I stayed at my calling at home, and kept to meetings.
For the Lord often filled and enriched my heart and soul with his glorious power,
and so sanctified and prepared me for that which he set before me:
for often in spirit was I carried thither, and had it sealed unto me,
that it was my place to go into that nation to serve the Lord,
and bear witness unto the Truth, and call people to repentance,
and hold forth the way of life and salvation unto them.
I waited till the full season came, according to the blessed counsel of God,
in which I found his leading power with me, and to go before me;
and at the time aforesaid, I took shipping at Whitehaven,
and landed at Donaghadee in the north of Ireland, and travelled to Lisburn,
and so up to Lurgan, and to Kilmore in the county of Armagh,
and so up and down in the north for some time amongst Friends, and I had meetings.
And many people came to meetings,
and many were convinced and turned to God from the evil and vanity of their ways.
From thence I travelled to Dublin, and thence to Mountmellick,
and so forward to Kilkenny, and to Caperqueen, and Tullow, and to Cork, and Bandon;
and back to Cork, and then to Youghal, Waterford, Ross, and to Wexford.
I had meetings along as I travelled; and according to that ability I received of God,
I was faithful and preached the truth and true faith of Jesus.
From Wexford I came to Carlow and Mountmellick, and so into the north,
where I spent some time.

Having gone through +++[+++the country,]
and in the fear of God published his name and truth, as I had opportunity,
I was willing to return home to England; and for that end as I intended,
came down to Carrickfergus; but before I got thither,
it came upon me that I should return back again to Lurgan and Kilmore,
and from thence to Londonderry.
So I sent word to appoint a meeting at Lurgan; and went on to Carrickfergus,
and got a meeting, where there were many people at it.
I cleared myself to them in the fear of the Lord, and then returned to Lurgan,
as I had appointed.
There I met with Robert Lodge, newly come out of England,
who had something in his heart also to go to Londonderry;
this was about or near the beginning of the seventh month 1659.
So Robert Lodge and I became concerned in one work, service, and travel together,
and were truly united in spirit, in the unity of the faith and life of Christ,
in which blessed unity and fellowship of the gospel of the Son of God
we laboured and travelled in that nation of Ireland for twelve months,
after we met together, not often parting;
though sometimes we were moved to part for the service`'s sake for a little time,
and came together again. The Lord gave us sweet concord and peace in all our travels;
for I do not remember that we ever were angry or
grieved one at the other in all that time.
"`We went down to Londonderry together; and when we came there,
it was soon discovered what we were, and the people were unwilling to receive us,
or to let us have lodging for our money.
We were at their great steeple-house on first-day,
and had a large time among the people to declare the Truth:
but at last the mayor sent his officers, who would not suffer us to stay any longer,
but forced us out of the city, and down to the boat,
and commanded the boatman to carry us over, and not to bring us back again.
Being clear, we took our journey towards Colerain, and then to the Grange,
and to Antrim and Lurgan, and so among Friends in the north.
After some time we took our journey into the south,
and travelled through a great part of the nation, as to Dublin, Mountmellick,
and to Athlone, and Galway, Limerick, Cork, and Bandon, and so through the south,
and again into the north.

Thus we spent our time with diligent labour and hard travel, often in cold, hunger,
and hardships in that country, which then was in many parts uninhabited:
and we were in prison several times; once in Armagh, once in Dublin, twice in Cork;
besides other abuses we received from many,
because of our testimony which we had to bear for the Lord,
in their towns and in their steeple-houses, and against their hireling priests,
who sought their rewards, and loved the wages of unrighteousness, like Balaam;
and worse than he, forced it from the people, like the sons of Eli,
whose sin was very great. 1 Sam. 2:16-17.

+++[+++The following epistle was written about this time.]

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
Clanbrasol, Ireland, 4th of the Fourth month, 1660.

[.salutation]
Dear Friends,

In dear and tender love do I salute you all, who are faithful to the Lord,
without respect of persons, in whose life and love I feel you,
wherein my heart is opened towards you,
and with whom I am daily refreshed and comforted in Christ Jesus,
the Fountain and Well-spring of life and refreshment; who is our Rock and daily refuge,
unto whom we flee and are safe in the day of storms and tempest, when the floods arise,
and the raging waves of the sea swell and beat.
Yet in the Light we have a safe hiding-place, and a sure and peaceable habitation,
against which they cannot prevail, as we abide faithful to the Lord therein,
whose love towards us hath abounded, and will abound, as we abide in that,
to which his love doth reach, which is his own seed;
and which he hath raised in us by his own power and outstretched arm;
wherein the issues of life and love are known and received.

Therefore, my dear friends, keep to it, and feel it continually; that fresh and lively,
and open-hearted, ye may always be in the Life,
that nothing may enter that would veil the seed, and oppress it;
for that will stop the issue of the love of God, which is shed abroad,
and shedding itself abroad in the hearts of all the faithful,
whereof we in the bountifulness of his love have richly been made partakers.
Therefore as one who with you has been partaker of the rich and endless love of God,
I exhort you, dearly beloved ones, to continue in his love,
and to abide faithful in the Life, that death may not again pass over any one;
but that the Life which God hath raised, may be felt, and may rule in every one of us,
over him that hath the power of death, to His praise and glory who hath redeemed us,
wherein comfort, strength and refreshment are received daily from Him,
who is the life and strength of all that wait upon him,
and who is near to preserve all them who are upright in their love towards him.
And herein have we boldness, believing, that neither tribulation, nor affliction,
persecution, nor distress shall be able to separate us from the love of God,
which we enjoy in Christ Jesus, although he may suffer great things to come upon us,
as it is at this day, to try us; nor yet to separate us one from another,
nor to break our unity in the Spirit, wherein we feel and enjoy one another.
In which, my dear Friends, I have you often in my remembrance,
to my joy and gladness of heart; for ye in the Lord are my rejoicing many times,
when all other comforts are taken from me; but only that, in which I feel and enjoy you,
wherein our unity, life and love stand, wherein I remain,

[.signed-section-closing]
Your brother in my measure received,

[.signed-section-signature]
John Burnyeat.

--

Having travelled and laboured in the gospel together for twelve months,
and many being convinced and gathered to the Truth, we were clear of our service there,
and in the seventh month 1660, we took shipping at Carrickfergus,
and intended for Whitehaven in England;
but by contrary wind we were driven to Kirkowbry in Scotland,
and from thence came over land into Cumberland, and to Cockermouth.

I again returned to my outward calling, and followed that,
and kept diligently to meetings; for it was still my delight so to do,
and there to be diligent in waiting upon the Lord;
for I always found that therein I received an increase of strength, life,
and wisdom from the Lord.
And as I found any motion upon me from the Lord to go to any meeting abroad,
either in our county or any other, I went and cleared myself, as the Lord gave ability;
and returned again to my calling, and so to our own meeting,
where I delighted to wait in silence upon the Lord: for I loved that much,
because I found an inward growth thereby,
through the teachings and openings of his Spirit in my heart;
and when something did open in me to speak in our meeting, I gave up for the most part,
though sometimes ready to quench through backwardness, but that was hurtful;
and I grew over it by degrees, and increased in faith and holy confidence more and more.
