== Chapter III.

[.chapter-synopsis]
* 1662+++.+++
* Proceeds for London by Yorkshire
* Is imprisoned at Ripon fourteen weeks
* In 1664 sails for Barbados
* John Perrots notions
* Visits Virginia, and New England
* In 1667 returns to Barbados, and thence to England
* Travels into various countries.

From the Seventh month 1660, to about the first or second month 1662,
I was very much at home at my calling;
and then I was moved of the Lord to go to London to see George Fox,
and others of the elders:
and to acquaint him with what was upon me from the Lord to go to America,
which came weightily upon me when I was in Ireland,
so that I had a great travail in spirit and deep exercise in mind before I gave up.
But when I had given up in the belief that it was the word of the Lord to me,
and submitted to his will, the weight and exercise were removed;
and I was with my former openness again restored into my service,
and no more remained but a remembrance of the prophecy or opening which I had received,
and faith in the word, which I was satisfied was sure forever.
And therein I rested as to that matter, until the time aforesaid,
when it came upon me to go and acquaint George Fox and also Edward Burrough,
who were then at London, and Richard Hubberthorne;
for I loved to have the counsel and countenance of my elder brethren,
who were in Christ before me.

Then I returned through Yorkshire home, and had some meetings, as I came along.
I stayed at home but a little time, and was moved to go again into Yorkshire,
and went to divers meetings to visit Friends.
Being, as I thought, clear to return home, I came to Ripon to see some Friends,
who were then prisoners for meeting together to worship God;
and going into the prison to see them,
and in the love of God speaking some words of exhortation to them, the jailer took me,
and had me to a house in the town,
where the mayor and the chancellor and several of the aldermen were together.
Then the chancellor chiefly took in hand to examine me, and sought to ensnare me,
that he might get occasion to commit me to prison.
First, he would have my going to prison to my friends to be an offence;
but I pleaded in so doing I had broken no law.
Then he said, I spoke in prison; I answered,
there was no law that forbad us to speak to our friends, when we came to visit them.
Then he asked me, when was I at church,
and when I took the sacrament according to the laws of England?
I answered, I knew no law I had broken, nor evil I had done to any man;
if any man had evil against me, let him bear witness of the evil.
Then he began to be in a rage, and said he would have an answer ere we had done, etc.
But when he could not get an advantage that way, he reached forth a book, and asked me,
if I would take the oath of allegiance and supremacy?
Then I answered, "`Not in contempt to the king, or his authority,
but in obedience to Christ`'s command, I could not swear.`"
Then he commanded the clerk to write a mittimus, and sent me to the prison,
to the rest of my friends, who were four and twenty before,
and there I was kept prisoner fourteen weeks.

When we sat down to wait upon the Lord (for we sat down once every day together,
and with us,
many times Friends that came to see us,) I spake something in exhortation to Friends,
and prayed unto the Lord, as he enlarged my heart,
that we might be comforted and edified together, and the magistrates were offended,
and sent the under-jailer to take me away,
and put me in the dungeon from among my fellow-prisoners; he came at three several times,
and each time haled me from my knees, when I was at prayer, and put me in the dungeon,
a little dark room, where I was one time two days and nights,
another time three days and nights, and the last time seven days and nights.
There was a bowling alley before the prison door,
where several of the magistrates and others used to come to their games;
and hearing my voice, they were offended, and sent to take me away.

[.embedded-content-document.epistle]
--

=== Epistle to Friends in Cumberland.

[.salutation]
Dear and well-beloved Friends,

Brethren and sisters in the holy covenant of life;
with you is my life bound up in the unspeakable bond of perfect unity,
and unfeigned love, wherein I feelingly reach unto you in this day of weighty trial,
wherein every one`'s faith and patience must come to be tried,
and every one`'s foundation made manifest whereon he stands.
Blessed are they whose foundation and standing is in the power of Christ Jesus,
the Rock of ages and foundation of many generations;
such shall stand immovable on the Rock in the day of tempest, and shall be at peace,
and kept in safety in the power, in the hour of temptation, and time of trial.

Therefore, my dear friends, as if I were present with you,
my life reacheth unto you in pure love,
even desiring that every one may truly abide in the feeling of
the precious life and pure invisible power of the blessed God,
which he hath made manifest in your hearts,
whereby every mind that hath been faithful to the Lord, is changed and renewed,
and redeemed, and made pure and sweet through the virtue and goodness of the same,
whereby our souls are refreshed continually,
as we abide in the sensible feeling of the Lord`'s presence.
O! therefore, my dear friends, ye who have tasted of the Lord`'s goodness,
and have been nourished by his mercies inwardly, who have felt his love,
and the value of his truth in your inward parts, mind that as your chiefest treasure;
that the sweet consolation,
and the precious spring of the Father`'s love ye
may feel opened in your hearts from day unto day,
and from time to time.
For truly friends, large is the Lord`'s goodness,
and exceedingly precious is the fountain of endless mercies,
which he hath opened in this day, for the refreshing of his own dear children,
whose whole trust and confidence is in him alone.
Therefore let none again incline in their minds after the things in the creation,
or desire further to enjoy it, or any thing in it,
than you may enjoy them in the covenant of God.

This, my dear friends, is truly in my heart from the Lord to lay before you,
and to warn you of in his name and fear; I say, friends, that ye,
who have tasted of the Lord`'s goodness in any measure,
and have felt the working of his heavenly power,
to the redeeming of your minds out of all visible things,
and to give you an entrance into the inheritance, that never fades away;
that ye may not look back again to the glory of the things of
this creation now in this day of trial of your faith,
but that all may be offered freely unto the will of the Lord; that whatsoever you enjoy,
it may be in his covenant;
that his blessed power may richly be felt and his peace sweetly enjoyed in your hearts.
Or else truly,
if any seek in the declining mind to hold any thing out of his covenant and pure fear,
the blessing will not be upon that heart, but it will be unto them,
as the spoil which the children of Israel fell upon contrary to the word of the Lord;
and like unto Achan`'s wedge of gold, which became a curse in the camp of Israel.

Therefore let all, with their all, be freely offered up unto the Lord in righteousness,
with an upright heart, which is but a reasonable service from us in this day,
who have so largely been made partakers of the
richness of his loving-kindness and mercies,
that so every heart may stand open, purely waiting for the heavenly virtue,
and for the renewing of the heavenly gift,
that every one may be strengthened by the same in the inward man;
that so we may all with one heart truly rejoice in the
salvation and consolation of the Lord our God,
which we feel and enjoy in spirit.

And furthermore, my dear friends,
that you who feel your hearts and all freely given up unto the Lord,
both you and yours to his will, mind the power which hath made you willing,
and abide in the sensible feeling of that continually;
that so every mind may be kept low and humble before the Lord,
sensible of the Rock of their salvation,
and of the arm of their strength and preservation;
that all fleshly boasting and glorying may forever be
excluded out of all the redeemed of the Lord;
that he alone, who is the salvation of his people, and the keeper of Israel,
may have the honour and glory, and the praise, from the work of his own hands,
who is God over all, blessed forever and ever,
whose works will forever praise him in all his children.

From your brother, who is now prisoner in the dungeon in Ripon common jail,
where I am separated from having liberty to be amongst the rest of my fellow-prisoners,
only because the Lord opened my mouth among them in our meeting,
when we were together waiting upon the Lord.

[.signed-section-signature]
John Burnyeat.

[.signed-section-closing]
Written the 4th day of the Sixth month, 1662.

--

After fourteen weeks I was set at liberty,
and in some little time I had freedom to return home; and then did, as at other times,
follow my outward calling, and kept to our meetings at home:
but when I was moved to go forth to visit Friends in our own county,
or into Yorkshire and Bishoprick, I was sometimes two months away, or thereabouts,
and then returned home to my calling or trade:
and thus it continued with me till about the forepart of summer, in the year 1664.
Then that which had been opened to me four years before,
began again to arise in my heart in that word which lives forever,
and the living motion of it began to press upon my spirit towards the fulfilling thereof;
and then I saw that the time drew near, and the season was coming upon me,
wherein the Lord would have me go and fulfill his word,
which I had yielded unto in spirit so long ago.
I therefore began to prepare, and set my heart to leave all things behind,
and give up all things else, that I might follow him:
and his power wrought my spirit into a right frame,
so that I could easily leave all things;
and he gave me time to settle and order my outward concerns, and leave all things clear.
That summer I took shipping for Ireland, and passed amongst most Friends,
and did visit them.

About the seventh month 1664, I took shipping at Galway in Ireland for Barbados;
and was seven weeks and two days in sailing to Barbados.
I stayed there about three or four months, and visited Friends,
and travelled and laboured in the work of the gospel,
both for the confirmation of those that were gathered,
and for the gathering of others to the Truth,
that they might partake with us of the like precious faith.
There I also met with many who had been hurt by John Perrot,
and carried away with his imaginations.
He was led out of the power and from the true cross, into high notions and vain conceits,
and so into a fleshly liberty and ease therein,
from the true spiritual travail and right exercise, both in spirit and outwardly,
pretending to be against forms;
and under that pretence led out of the faithful and
diligent practice which Friends had been gathered into,
as to their meeting together and waiting upon the Lord, counting that a form,
which he did lead into a slight of, and so caused many,
both there and in Virginia and other places, to neglect,
or in a great measure to forsake the assembling of themselves together,
contrary to Friends`' practice, and the counsel and advice of the faithful labourers,
who first laboured amongst us, as also contrary to the advice of the apostle. Heb. 10:25.
He also, in his new notion,
led many to keep on their hats in the time of prayer, when any Friends prayed,
and condemned our reverend practice of putting off our hats at such times:
and so in many things, such as were taken with his notions,
were led out of true order into looseness and such a liberty,
that the cross in most things was laid down by them, and their own wills followed,
and Truth`'s testimony let fall.
But he ran out of the Truth so far at last,
that many began to see him and what his spirit led to; and so came to see their own loss,
and returned back unto their first love;
and the power of the Lord went over that dark spirit,
with all the vain imaginations they had been led into thereby;
and so Friends were gathered into their former unity.
Now because of the prevalency of this spirit,
I had the greater travail and exercise among Friends in that island,
and in other places of America; both in withstanding such as were high and hard,
and also to gather back and preserve such, as had in some measure been betrayed,
and yet were more innocent and tender.

[.embedded-content-document.epistle]
--

=== To My Dear Friends in the north of Ireland about Kilmore, Lurgan, and that way.

[.signed-section-context-open]
Barbados, the third day of the First month, 1665.

[.salutation]
Dearly Beloved,

--Unto whom the pure love of my heart in the
covenant of life doth plenteously flow forth at this time,
my soul dearly salutes you all, who are faithful unto the Lord,
without respect of persons;
whose minds are kept faithful unto the unchangeable power of life,
wherein your souls have been refreshed,
and by which you have been gathered into the belief of the Truth,
and to the acknowledgment of the same;
which in a good degree hath been made manifest in and among you.
My exhortation, as a brother, in the bowels of love unfeigned unto you, is,
that as the Lord hath appeared, and made manifest his power in your hearts,
even so wait ye; that your dwelling ye may come to witness to be in the same.
For Friends, ye know, that it is not sufficient only to know that He hath appeared,
but that ye feel your dwelling to be in the power,
and in the daily sense of the renewing of his appearing in your hearts:
that by it your hearts may be kept open unto him,
and so you from day to day may know the renewing of his presence,
and the virtue of his own life in you.
O! my dear Friends, this is that by which every heart may be kept sweet and living,
and virtuous, and open unto the Lord;
so that the issues of his love will become as a refreshing river,
unto every soul that keeps faithful unto him.

Therefore, Friends, all mind your standing and your dwelling in the power,
and wait for the inward operation of it in your hearts; that, by its dwelling in you,
and living in you, your hearts may be kept tender, and contrite,
and broken before the Lord.
And Friends, beware of hardness of heart, I warn you in God`'s fear;
for therein the deceitful worker gets advantage, and unbelief comes to enter;
and so such will come short of the rest that God hath prepared for his people,
and through the deceitfulness of sin will come to be more hardened.
And so Friends, lest this should come upon any one of you, and ye fall short of the rest,
watch in the fear of God;
and keep down to the tender principle of life every one of you in your own particulars,
by which your hearts may be kept out of the hardness in
the tenderness and brokenness of heart;
in which state the Lord is witnessed to dwell with man and in man,
according to his promise.
And so will you know the growing of the holy seed in you into the pure dominion,
by which that which would darken or harden, will be subjected,
and kept in the subjection.

Therefore Friends, mind your standing in the seed Christ, the true vine,
that you may have life abundantly, and know its abounding in you.
For whosoever goes from him, the life, the seed, the vine, Christ Jesus the power of God,
shall wither, and decay, and die; and in the end be fit for nothing but the fire.
And this shall such know, who in the day of the Lord`'s gathering,
and tender visiting in mercy and loving-kindness,
will not be won and gained into faithfulness, but who slight the day of their visitation.

Therefore my dear Friends, be faithful unto the Lord every individual of you,
in that which you have received from him, and wait to be guided by that in your hearts.
And keep low and down to the principle of life in your own hearts,
that you may never become stiff-necked, nor hardened in your hearts again.
For this was Israel`'s sin of old, whose hearts were hardened,
and whose neck was become like an iron sinew, that it could not bend unto God`'s yoke.
For this he was wroth with his people, and cast off his inheritance in that day;
so that their enemies had power over them, and laid their dwellings desolate.
These things are left unto us for an example,
that we might not fall after the same manner of unbelief;
but fear lest a promise being left us of entering into his rest,
we should fall short through unbelief, and so lose the inheritance,
and so by the enemy have our habitations laid desolate,
and we be carried away captives out of our dwelling-place.

These things, my friends and brethren, I lay before you in the fear and love of God,
which is weighty in my heart towards you all:
and I desire that the Lord may preserve you all faithful unto himself,
in the feeling of his life and good presence,
by which your hearts may be kept open unto him,
and so open in true love one towards another;
that as a family in the love of God you may dwell together;
in which love my soul dearly salutes you all,
and in it I remain your brother and companion in
the tribulation and patience of Christ Jesus.

[.signed-section-signature]
John Burnyeat.

--

When I had travelled and laboured, as I said before,
about three or four months in that island, and was clear,
I took shipping for Maryland about the latter end of the first month,
and landed there about the latter end of the second month 1665.
I travelled and laboured in the work of the gospel in that province that summer,
and we had large meetings; and the Lord`'s power was with us,
and Friends were greatly comforted, and several were convinced.

But I had a sore exercise with one Thomas Thurston,
and a party he drew after him for a while;
so that both I and faithful Friends were greatly grieved, not only with his wickedness,
but also the opposition which he made against us,
and the disturbance he brought upon us in our meetings.
Great was the exercise and travail which was upon my spirit day and night,
both upon the Truth`'s account, which suffered by him, and also for the people,
who were betrayed by him to their hurt, and were under a great mistake.
But through much labour and travail in the Lord`'s wisdom and power,
I and other faithful Friends of that province had to search things out,
and to clear things to their understandings, both as to what related to the Truth,
and also matter of fact, which he was guilty of; it pleased the Lord so to assist us,
and bless our endeavours,
in manifesting the wrong and the wickedness of the heart and spirit of the man,
that most of the people came to see through him,
and in the love of God to be restored into the unity of the Truth again,
to our great comfort, Truth`'s honour, and their everlasting happiness.
But he himself was lost as to the Truth,
and became a vagabond and fugitive as to his spiritual condition,
and little otherwise as to the outward.

In the winter following I went down to Virginia, and +++[+++I found]
Friends there, or the greatest part of them, were led aside by John Perrot,
who had led them into his notions, as before described:
and they had quite forsaken their meetings, and did not meet together once in a year,
and many of them had lost the very form and language of the truth,
and were become loose and careless, and much one with the world in many things;
so that the cross of Christ, for which they had suffered, was shunned by them,
and so sufferings were escaped, and they got into outward ease.
For they had endured very great sufferings for their meetings,
and stood faithful therein, till he came among them, and preached up this notion of his;
by which he judged Friends`' practice and testimony in and for the Truth,
to be but forms: and so pretending to live above such things,
he drew them from their zeal for the Truth, and their testimony therein so far,
that they avoided everything that might occasion sufferings.

Thus they being seduced or bewitched, as the Galatians were, into a fleshly liberty,
the offence of the cross ceased, and the power was lost; and when I came there,
it was hard to get a meeting among them.
Much discourse I had with some of the chief of them;
and through much labour and travail with them, and among them,
to maintain the principles of Truth and our testimony and practice therein,
I obtained a meeting: and the Lord`'s power was with us and amongst us,
and several were revived and refreshed,
and through the Lord`'s goodness and his renewed visitations,
raised up into a service of life, and in time came to see over the wiles of the enemy.
After some time I returned again to Maryland, and passed amongst Friends,
and visited their meetings, and in the first month I came to Virginia,
and did visit them; and so returning again to Maryland,
I landed at New York in the fourth month, 1666,
and spent some time there amongst Friends, in going through their meetings.

[.embedded-content-document.epistle]
--

=== Epistle to Friends in Long-Island,

[.signed-section-context-open]
Long-Island, 23rd of Fifth month, 1666.

Dearly Beloved, who are called to be saints,
and to believe in the only Begotten of God the Father,
whom he hath raised to be the horn of salvation in the house of his servant David,
to rule over the redeemed in Israel forever; unto you is my +++[+++heart]
opened in pure, unfeigned love,
and in the plentiful flowing of the same at this time doth my soul dearly salute you all,
who keep faithful unto the Beloved,
and live in the power of his salvation over all the fallen spirits,
which are in the world, which bring into bondage.
With you my soul hath unity in the life, which was before transgression and the fall;
and in that, my Friends, are you written in my heart, and often in my remembrance,
even when my supplication is poured forth unto the Lord in the behalf of his people,
that you in that place,
among the rest of his heavenly flock and sheep of his own pasture,
may be safely kept by the right hand of his power from the devourer,
and from the deceitful snares of the enemy,
which are laid as traps by the cunning sleight of Satan to ensnare the simple,
and betray the innocent from the simplicity of the gospel,
which ye have received in Christ Jesus our Lord; in which as ye have believed,
ye have found salvation, and peace and rest unto your immortal souls.
I even as a brother, and one that entirely loves you with that unfeigned love,
which thinks no evil, do at this time beseech you all in the fear of God,
to see that ye walk circumspectly, answerable unto the gospel of Christ Jesus,
in which ye have believed; that ye may adorn the same in your lives and conversations,
as children of the light and of the day,
bringing forth the fruits of the Spirit in righteousness and true holiness,
and not the fruits of the flesh in the night and in the darkness, in which they walk,
who follow not the Lord Jesus Christ.

Therefore stand fast in your liberty, in which Christ Jesus hath made you free;
and be not entangled with the yoke of bondage,
but mind purely the operation of the eternal Spirit and
invisible power of the everlasting God,
which he hath made manifest and revealed in your hearts,
by which you have in measure known liberty from the bondage of corruption,
(the corruptible bond,) and have tasted of the glorious liberty of the sons of God,
in which your souls have found pleasure.
All mind its lively operation in your hearts, and wait upon it with diligence,
that your hearts may be kept clear, and the eye of your understandings single,
that you may purely distinguish and put a difference between the precious and the vile,
between that in which the Lord is to be worshipped,
and that in which there is no acceptance with God.
And so you will come more and more to know how to choose the good, and refuse the evil.
In the freedom of God`'s Spirit, and in his fear I warn you all,
take heed of a fleshly liberty beyond or above the pure fear,
which keeps the heart clean; for that will let in pollutions,
and bring the just into bondage, and your souls into death again,
where there will be a want of the pure presence of God to refresh them,
although the boaster may boast of liberty,
and promise it as they did in the apostles days,
who themselves were the servants of corruption.

And so, my dear Friends, whom my soul loves with the heavenly love,
that seeks the good of all,
you who have tasted of the love of God and of the power of the world which is to come,
and of the power of that life which is without end, keep constant in the faith,
unto the beloved of your soul, and gad not abroad to change your way, like her,
whose feet abide not in her house, but run out after other lovers,
and so lose the first love.
For this the Lord reproved the Church in the days of the entrance of the apostacy,
when they began to decline from the purity of the gospel.
As ye have received that which is unchangeable, live in it,
that your souls may never die from the sense of God`'s love,
and the feeling of his virtuous presence;
that in the joy and peace that is unspeakable and full of glory,
you may abide and forever live;
where your souls may be refreshed from day unto day and from time unto time,
through the multiplying of his numberless mercies,
by which he nourisheth all them that fear him, and wait upon him.
And so will you all keep lively and virtuous in a growing and flourishing condition,
fruitful, bringing forth fruit to his praise, who hath called you.
And as you keep to the power of God--which is the cross
to that part which would be out--and dwell in it,
your mind will be settled, and steady and kept clear, and the understanding open,
whereby you may behold the glory of God and be kept in covenant with him;
and so feed upon his mercies with all his lambs and children,
and lie down in the fold of rest and safety with the sheep of his pasture,
in covenant with him forevermore: in which I remain your friend and brother,

[.signed-section-signature]
John Burnyeat.

--

Then I took shipping for Rhode Island in New England,
and there spent some time in visiting Friends and their meetings;
where I had comfortable service.
About the latter end of the sixth month, I took my journey towards Sandwich;
and when I was clear there, I took my journey by Plymouth to Tewkesbury,
and so to Marshfield and Scituate, and to Boston, and I visited Friends and had meetings.
From Boston I went to Salem, and so on to Piscataqua.
When I was clear there, I returned back through the meetings, and came to Hampton, Salem,
Boston, Scituate, Marshfield, and so by Tewkesbury and Plymouth to Sandwich,
and from thence through the woods to Ponyganset, and from thence over unto Rhode Island.
After some time spent there, I took shipping for Long Island,
to visit Friends in those parts;
and when I was clear I returned again to Rhode Island in the winter,
and stayed for some time; for there was no going off the Island to the main,
the snow was so deep.

About the latter end of the first month, I took shipping for Barbados,
and landed there in the second month, 1667, and spent that summer there,
and had blessed and comfortable service among Friends, with large and full meetings;
and the Lord`'s power and presence were with us,
and several were gathered to the love of the Truth.
In the seventh month I took shipping for Bristol, in England;
and after we had been ten weeks at sea, except one day or two,
being beat off the coast with an easterly storm, and kept out at sea in a great tempest,
for the most part of two weeks, we got, at last, into Milford Haven, where I landed,
about the 27th of the ninth month, 1667.

[.embedded-content-document.epistle]
--

=== For Friends in Barbados, New England, Virginia and Maryland, the signification of my purest love unto you all, amongst whom I have travelled in those parts.

[.salutation]
Friends,

--In the eternal truth and power of the Lord God dwell,
and keep your habitations in that which changes not; in the power of an endless life,
where there is no shadow of turning.
All you that have known the Lord,
and have been sensible of the word of his eternal power in your hearts,
by which you have been quickened unto him, so that with the rest of his beloved ones,
you have been made partakers of that heavenly treasure of life and virtue,
which is in him, and through his Son is manifested unto us,
by whom life and immortality is brought to light; unto you all,
without respect of persons, doth the love of my soul reach,
and the salutation of my life at this time, having you fresh in my remembrance.

In true love is my heart opened,
and my spirit drawn forth in this word of exhortation unto you all,
who have tasted that the Lord is gracious;
that you all take heed of turning from the grace of God into wantonness,
lasciviousness or any vanity whatsoever, by which your hearts may be defiled;
but that ye all watch unto the Truth, and wait upon the preserving power of the Lord God,
that ye may reign in the dominion of the same over all the evil lusts of the flesh,
which would arise in your hearts to war against the Spirit of holiness,
and so would hinder your sanctification.
This of a truth.
Friends, you ought to take heed unto,
the Spirit of holiness and power of the Lord our God,
which in this latter age he hath largely manifested to sanctify his people;
that so your hearts may be kept clean and preserved, according to Christ`'s command,
out of the surfeiting with the cares of this life,
and from being overcome with and drowned in the pleasures and vanities of this world,
that you may never lose the excellency and glory of these heavenly things,
which God the Father,
in the bountifulness of his lovingkindness hath been pleased to manifest,
with which all the glory of this present world is not to be compared.

And so, my dear Friends, you that feel the Lord and his goodness in your hearts,
walk circumspectly as before Him, with reverence and godly fear in the holy awe,
that you may not provoke him at any time, nor grieve his Holy Spirit,
by which you are sealed;
but with tenderness of heart and pureness of mind wait upon him at all times.
So will your peace spring up as a river, and your righteousness be multiplied,
as the waves of the sea; and over all the choking cares of this life,
and drowning pleasures of this present vain world you will be preserved,
to have a being in the power of that life, which is without end;
in which as there is a dwelling faithfully,
you will all grow and increase in the dominion over all hurtful lusts,
that war against the soul in your own particulars.
And also there will be a growing over all hurtful spirits,
that have entered since the beginning, whose life is in the fall,
and not in the pure redemption, nor in the redeeming power, that brings out of the fall.
And so to the Lord God, be ye all faithful in your places,
that you may be a blessing in your generation in
those countries and places where ye dwell;
that the nations may be seasoned, that your savoury life may sweeten the people.
And Friends, have an eye to the glory of God,
and the honour of his Truth in all your undertakings; I even command you in his fear,
it being upon me by his Spirit,
that the Lord`'s name may not be blasphemed
among the heathen through your unfaithfulness.
For truly, my love being great towards you, I am jealous over you with a godly jealousy,
and therefore am constrained to use great plainness, as having a sense of your state.
And therefore be ye provoked unto love and to good works, in a faithful obedience,
and serving of the power; for it is in that all are accepted.

Lay aside all wrath and clamour, and evil speaking, with all bitterness;
and receive with meekness the ingrafted Word, which is able to save your souls.
In the power of that dwell, and it will divide aright between the precious and the vile,
and so will cut off all that is not of God, not regarding what may be professed,
where the living virtue is wanting.
This pure, living Word is your preserver, who keep faithful in it,
and will keep you from all deceivableness and lying spirits, which are not of the Father,
but of the world, and from the god of the same in the dark power,
beguiling the unstable soul through his lying signs and wonders in the power of darkness,
without living virtue.
This Word, which you have received, will live in your hearts,
and minister daily of its own virtue unto your souls for their refreshment,
if you keep faithful to the same.
But if the thorny cares of this life,
and the choking pleasures of this vain world take root and place in your hearts,
then the freshness is lost, the issue of living virtue is stopped;
the ministering word and power is withdrawn; the fountain is again sealed up,
and the dry winds and the scorching heat come
and dry up and cause to wither the green blade,
before the corn comes to perfection;
so that the harvest and time of gathering never come.
Therefore, O my friends, be faithful unto the Lord,
and be not drawn aside from the steadfastness of the gospel,
neither on the one hand nor on the other; but step in the straight path of life,
peace and salvation, which the Lord hath prepared for your feet,
that the weak may be strengthened and the lame recovered, and none turned out of the way.

For truly, there is much upon you; I feel it in this matter,
even you that feel the Lord in any measure,
that you all be vigilant and diligent in your places,
that you may be a strength to the weak.
Therefore am I moved once more to warn you now, even you that know the Lord,
to take heed unto the power of the Lord God in your hearts,
and with that keep down the earthly, worldly spirit,
that so you may live over it in the Spirit and power of the Lord,
and may draw more unto you; or else I feel it,
you will not only be guilty of your own blood, but the blood of others also,
which stumble at your unfaithfulness,
who have been called and accounted as the first fruits unto God,
and unto the Lamb in those parts of the world, in this blessed day of the Lord;
in which he hath appeared and gathered by his power,
and also doth preserve and nourish by the virtue of the same,
all that he hath gathered whose trust and confidence are in him.

And so, my friends, this may give you to understand, that I am safely arrived in England,
and am perfectly well every way.
Friends here are generally well, meetings very large,
and the Truth in good esteem among many people, who are not yet of us.
And great openness in all places, where I have been, in the hearts of all people,
and great desires to hear the Truth, for it is of good report.
This from me, who remain your friend and brother,

[.signed-section-signature]
John Burnyeat.

--

Thence I went up to Haverfordwest, in Pembrokeshire, in Wales,
where I met with a meeting of Friends the same day;
and I stayed four weeks in that county, and had many blessed meetings.
Being clear, I took my journey towards Swansea, and visited Friends there;
and came up towards Cardiff, and so on into Monmouthshire;
and after I had visited Friends there, I passed over the water and came to Bristol,
and stayed there some meetings; and thence passed into Gloucestershire and Berkshire,
and so up to London, where I stayed some time.

+++[+++The following Epistle is without any specific address.]

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
Bristol, the 25th day of the Eleventh month, 1667.

[.salutation]
Dearly Beloved,

--With whom in the covenant of life, light and peace I am one,
wherein I am with you,
and in spirit do reach unto you in that love which many waters cannot quench;
in which my soul at this time doth very dearly salute you all,
who have been born again of the Immortal Word, and in the life of the true seed remain.
In which my desire is, that the Lord may preserve you all;
that as living plants in the vineyard of God you may flourish,
and bring forth righteous fruits, and so be an honour unto the Lord in your generation,
and then you need not doubt, but the Lord will honour you in the glory of his kingdom,
that is without end.

Therefore, Friends, the life of righteousness in the power that is without end,
do you all mind to live in;
that fruits of holiness in a godly conversation may be brought forth by you all;
by which the gospel of peace and salvation comes to be adorned:
and so all will come to know the effect of righteousness,
which is peace and assurance forever.
This is that you ought all to be mindful of, that the evidence of peace,
by the testimony of the living Spirit in all your hearts, ye may feel renewed daily;
which will not be without an abiding and living in the life of righteousness,
whatsoever notion of profession may be held in the wrong mind,
and not in the power and life of righteousness.
For this testimony is true and living, searching narrowly under all coverings,
and breaking through all veils, entering into the inner court,
and breaking through into the secret chambers to see what may have a being there,
or be worshipped.
So that it is in vain to cover any thing in this day,
wherein the Searcher of all hearts hath appeared; and he is come,
whose fan is in his hand, who sits as refiner`'s fire and as fuller`'s soap,
to cleanse and purify his chosen tribe, that they may be a peculiar people,
a chosen generation, and a royal priesthood, to show forth the praises of him,
who hath called out of darkness into his marvellous light.
Therefore, my dear friends,
with open hearts and nakedness of spirit do you all walk before the Lord,
not seeking any covering, but that of the Spirit in the life of righteousness,
that its testimony and witness you may all have in your hearts,
to bear witness with you unto justification;
that so ye may be clothed with the white robe of righteousness in the power of the Lamb,
and become kings and priests unto God, reigning, in the power of the Lamb`'s Spirit,
over that which can never offer an acceptable sacrifice.

And so in the life of him that is a priest forever after the order of Melchizedek
according to the word of the promise and of the oath)
you will be a royal priesthood, offering up an acceptable sacrifice unto the Lord,
And my dearly beloved, unto whom my heart in pure love is opened,
keep your habitations in the life of the Son,
in the life of the Priest that lives forever, that you may never be rejected.
In him is the Father well pleased, in him are all our offerings accepted,
and without him ye can do nothing.
All coverings and robes without him are but as filthy rags,
and all garments without his power and life of righteousness
are no better than an abomination in the sight of the Lord.

Therefore keep your garments clean, your hearts pure before the Lord,
that the acceptance you may never lose: and mind the living of the power in your hearts,
and your living in it unto God the Father,
that as we have been quickened together in the resurrection of the life,
even so in the same we may worship the Father forevermore.
And so in this, my soul once more very dearly salutes you all,
ye children of the covenant and of the blessed day of God Almighty,
who walk in the light.
I have not been unmindful of you, though outwardly we have been separated;
but the ancient love hath lived in my heart,
which draws forth strong desires in me unto the Lord,
that in his will I might see your faces; which I hope, will be answered in his time:
and until then I am freely given up to his will,
being satisfied with the invisible union and fellowship in the Spirit,
that I have with you, which time or distance of places can never wear out,
because that life and power, which is eternal, is known; and that love which changes not,
is enjoyed, in which I am one with you, and remain Your brother in the covenant,
where sin is blotted out, and everlasting righteousness is brought forth,
in which we worship the Father acceptably,

[.signed-section-signature]
John Burnyeat.

--

After I was clear of that city, I was moved to return again into Berkshire,
and Gloucestershire, and so to Bristol, and over into South Wales and Pembrokeshire,
all along visiting Friends; and I had blessed service.
When I was clear of those parts,
I was moved to return again through the meetings in South Wales, and to Gloucester,
and through Gloucestershire and Berkshire, into Buckinghamshire, and so up to London,
where I spent some time that summer, in the year 1668.

After that I went over into Surrey to see George Fox,
who was then travelling among Friends in those parts,
to assist Friends in the settling of their men`'s meetings,
and also to stir them up to visit such as were
fallen away from the Truth and had drawn back,
and to see if they could be restored and brought
back again to a sense of the love of God,
and so to salvation and life;
which work did prove very effectual for the gaining of many.
After I had been a little with him,
and at Horsham (with some Friends who went from London with me,) to
visit some Friends who were prisoners there for Truth`'s testimony,
I returned back again to London, and took my journey for the north of England,
through Herefordshire and Huntingdonshire, and then down into Yorkshire.
I spent some time in visiting the meetings about Knaresborough, Netherdale, Masham,
Thirsk, and thereaway; and then was moved to go down towards Crake and Malton,
and so on to Killam and Burlington, Scarborough and Whitby, and into Cleaveland,
and so qver into Bishoprick.
After some time spent there, I passed over Stainmore, and into Cumberland,
and came home to see my friends and relations.
I stayed there but about a week, or a few days more,
and then took my journey for London to the yearly meeting,
which was appointed to be about the beginning of the tenth month,
and I was there about a week or two.

Then I took my journey again into the west, through Berkshire and Gloucestershire,
and into South Wales, down as far as Pembrokeshire, visiting the meetings,
and serving the Lord and his people with faithfulness in the
labours and travels of the gospel of Christ Jesus.
When I was clear of those parts, I returned back again through South Wales to Bristol,
and so through the counties, visiting the churches up to London, that spring,
in the year 1669.
I stayed about two months time in and about the city,
and then I was moved again to go into Buckinghamshire, and so through the country,
visiting meetings in divers places, till I came to Bristol;
and was at Bristol about the 25th of the fifth month, 1669.

From thence I went over into Wales again, and passed through South Wales,
as far as Pembrokeshire;
and from thence I took my journey through the mountains towards North Wales,
and visited Friends in Radnorshire; and from thence came to Shrewsbury,
and so into Cheshire, and through Lancashire and Westmoreland home into Cumberland,
where I stayed a little, and visited Friends.
I took shipping at Whitehaven for Ireland, and landed at Belfast in the north,
and spent that winter in
Ireland in the travels and labour of the gospel;
and I had blessed service for the Lord and his people in that nation,
and was richly comforted and refreshed amongst them in the gracious presence of the Lord,
who was with us,
who is the recompenser and rich rewarder of all
who are given up in faithfulness to serve him.
So that now none do lose their reward under the ministration of the gospel,
no more than they did under the law in the figure, when he said,
"`Who is there among you, that would shut the doors for naught?
neither do ye kindle fire on mine altar for naught.`"
Mal. 1:10: to him be glory, and honour, and praise over all forever; for he is worthy!
When I was clear of that nation, I took shipping at Dublin,
and landed at Whitehaven in Cumberland.
I stayed a little time in Cumberland,
and then took my journey for London to the yearly meeting,
which was in the spring of the year 1670:
and I spent a part of that summer in London and thereabouts, in the service of Truth,
until I could have a conveniency to go for Barbados, that being upon me.^
footnote:[In this year, 1670,
the act against seditious conventicles began to be in force, which Sir Samuel Starling,
then Lord Mayor of London, immediately exerted his authority to put into execution.
Watchmen and soldiers were placed in guard at our several meeting-houses in the city,
either to keep Friends out of their meetinghouses, or to prevent preaching, etc.
John Burnyeat being at Devonshire-house, on the 15th of the month called May,
and having begun to speak, was quickly pulled down, and had before the Mayor,
who fined him £20; on the 29th of the same month,
John Burnyeat attempting to preach at the same meeting-house, was taken away by soldiers,
and sent by the Mayor to Newgate.--[.book-title]#Besse`'s Sufferings of Friends,# vol. i. p. 409.]
