== Chapter VI.

[.chapter-synopsis]
* Abstract of some of the letters of John Burnyeat, in continuation of his travels, from 1673 to 1690
* His marriage in 1683
* His imprisonment in Dublin
* Death of his wife 1688.

From Galway I travelled to Limerick, and so to Charleville, Mallow, and to Cork,
and Bandon, and as far almost as Baltimore, visiting Friends and having meetings.
I then returned back to Cork, and took my journey to Youghal, and so on to Tallagh,
and to Kilcomin, and to Waterford, and so on into the county of Wexford,
having meetings in all the places: and the Lord`'s good presence`' was with us,
to our comfort;--glory, and honour, and praise to him for ever!

Then I came up through the county of Catherlough, +++[+++Carlow]
and the Queen`'s County, and so on into the county of Westmeath,
having meetings all along, and visiting Friends; and there George Pattison left me,
and took his journey for Dublin, and from thence to London,
but I took my journey for Cavan.
When I had seen Friends, and had a meeting or two, I took my journey for the north,
the county of Armagh and the county of Antrim, and those parts; and I visited Friends,
and had many precious meetings, and the Lord was with us,
and his gracious presence was our daily comfort;--to him be the glory for ever!

When I had spent some time in the north of Ireland in the service of the Truth,
I took my journey for Dublin.
And after some meetings there, I took my journey into the county of Wicklow,
and so through the province of Munster a second time, and also took Friends in Leinster,
and in the north; so that I travelled through most meetings a second time in that nation.
Then being clear of the nation,
I took shipping at Belfast the twenty-fifth day of the tenth month 1673,
and the twenty-sixth we set sail out of the Lough,
and arrived at Whitehaven in Cumberland in England the twenty-seventh of the same month,
and stayed about three months in Cumberland for the most part.
Then I took my journey out of Cumberland towards Newcastle,
visiting Friends and their meetings, as I went along:
and from Newcastle I went on into Bishoprick, and through their meetings,
and so into Yorkshire, through Cleveland to Whitby, and Scarborough, Malton, and York,
and had many precious meetings.

I went up to Masham, and from thence Robert Lodge and I, with James Hall,
took our journey towards London to the yearly meeting in the year 1674,
and stayed some time in that city,
labouring in the word and testimony which God had committed unto me.
Afterwards I took my journey into the country, and went down into Buckinghamshire,
through their meetings; and so on into Oxfordshire, Worcestershire, and Gloucestershire,
and to Bristol, and then back again, and to Shrewsbury,
and on as far as Wrexham in Wales, visiting the Churches of Christ;
and the good presence of the Lord in his heavenly power accompanying,
we were often refreshed and sweetly comforted together, to our joy and his praise,
who is our God for evermore.

From Wrexham in North Wales, I took my journey with John ap John,
who accompanied me towards South Wales; we visited Friends,
and had many meetings as we went along, in Montgomeryshire, Merionethshire,
and Cardiganshire; and we passed on by the west sea into Pembrokeshire,
there we visited the Lord`'s people, and spent some time amongst them.

Then we took our journey through Carmarthenshire to Swansea;
and having a meeting or two we passed on towards Cardiff,
visiting Friends in Glamorganshire, and then into Monmouthshire,
and having visited Friends in that county, we parted; he returned home,
and I passed over the water into Gloucestershire, and so to Bristol.
I continued travelling through several counties, visiting the churches, and so to London,
where I spent some time; and then I went down into Essex,
and visited Friends in that county,
and returned again to London to the yearly meeting in the year 1675.

From London I took my journey to Hartford, and so northward,
with John Graves and James Hall, to York, and there we parted.
I went from York to Malton, and so to Scarborough, and Whitby,
taking Friends in Cleveland, and so to Stockton in Bishoprick, visiting Friends,
and having many precious meetings.
I then passed through several meetings in that county;
and being clear I took my journey for Cumberland; and being there,
I with several brethren was desired to come over into Westmoreland,
to a meeting appointed by Friends at their quarterly meeting, which was to be at Powbank.
So I went thither against the day appointed, with John Graves, John Tiffin, Hugh Tickell,
and Thomas Laithes, where we met with several brethren, who were come out of Yorkshire,
at the request of the aforesaid quarterly meeting.

Upon this occasion many Friends of Westmoreland came together; who,
when we were sat together in the meeting,
did present before us several disorders in many things, which were contrary to the truth,
by which they had been grieved and sorely exercised for
a long time in their monthly and quarterly meetings;
so that the spirits of a loose company were set at liberty,
and so much borne up and countenanced by John Story and John Wilkinson,
that the blessed order of the truth brought forth amongst us by the power of God,
was greatly slighted, and endeavoured to be trodden under by that loose company,
which was thus encouraged by these two men, who looked upon themselves to be elders,
and like Diotrephes, loved to have the pre-eminence;
which brought great grief upon the honest and simple minded.
So we hearing what Friends had to say in that matter,
and observing what was charged and proved, we desired Friends to give us another meeting,
and let John Story and John Wilkinson be sent to, and desired to meet us,
that we might hear them face to face:
although they had been desired by the quarterly meeting, and several others,
to come to this meeting so appointed, they had refused; and withal they sent us a letter,
denying to come, and disowning our meeting.

Nevertheless, we were willing to have another meeting,
which Friends of Westmoreland freely assented unto;
and so it was appointed at Milthrop the next day.
And we (to wit) six or more of Cumberland and Yorkshire Friends,
did ourselves go to them as messengers,
and did entreat them to come with us to the meeting,
that we might hear them and the Friends of Westmoreland, who were aggrieved,
face to face, concerning those things that were in charge against them;
but they were so high and so obstinate, that they slighted us all,
or any advice we could give.
So after some hours`' discourse with them,
in which we thoroughly saw their spirits to be wrong, we left them,
and went to the meeting appointed at Milthrop, where Friends were waiting for us.

After we were settled a little in the meeting,
we gave an account how we had endeavoured to persuade them to come,
through all entreaty we could, but we could not prevail.
So we gave a hearing a second time to the Friends;
and then we of Yorkshire and Cumberland withdrew,
and amongst ourselves viewed the whole matter, for it was in writing,
and opened our hearts one unto another.
And waiting upon the Lord, there fell a weighty concern upon us for the Truth`'s sake,
and the blessed order thereof, with our holy testimony we had been raised up into,
which by them had been slighted, and scorned, and reproached:
so that we could not pass it by; but in the power of the Lord God,
which was dreadful amongst us, we gave judgment against that spirit,
which was grown so high, and loose, and fleshly,
as thus to undervalue the testimony of God,
and the bringings forth of his holy power in the churches of Christ,
by which all may be kept sweet, clean, and in good order.
And when we had cleared ourselves in the rising and springing up of the word of life,
and drawn up our testimony in writing, we gave it unto Friends there, and so departed.
Of the judgment given I shall say no more here, because it is in writing in many places.

I then went over to Swarthmore, and stayed a meeting there;
and then returned into Cumberland, and stayed there some weeks, and visited Friends.
Being clear, I returned again to Swarthmore, in order to go over the sands towards Wales,
which was before me.
When I was at Swarthmore, I was moved to go over first into Westmoreland,
to visit the meetings there.
So I went over to Sedberg, and had a meeting there; and I had a meeting at Grayrigg,
and then came to Kendal, where I met with Robert Lodge,
and we had a blessed meeting there.
The next day we were at Preston meeting; and then I was clear of that county.

After a little time I took my journey into Wales, through Lancashire and Cheshire,
and so coming to John ap John`'s, near Wrexham in North Wales,
he travelled along with me.
In the first place, we went to a quarterly meeting that was held at Dolobran,
at Charles Lloyd`'s, for two counties, viz. Merionethshire and Montgomeryshire;
and we had a blessed service for the truth there among Friends.
Afterwards we went down into Merionethshire, and visited the meetings:
and then to Mackynleth, and had a meeting.
We then returned up into Radnorshire, and visited the meetings in that county.
We next took our journey through Brecknockshire and Carmarthenshire, into Pembrokeshire,
where we spent some time amongst Friends, and had several precious meetings.
Being clear, we took our journey towards Swansea and Cardiff,
and had several precious meetings in Glamorganshire,
and then went over into Monmouthshire.
And after we had visited Friends, John went with me to the ferry,
and stayed to see me take boat, and then returned.

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
Bristol, 9th of Tenth month, 1675.

[.salutation]
Dearly Beloved,

Whom the Lord hath called and sanctified, and chosen in the Son of his love,
through whom he hath visited you in this generation,
as he did the people and the Gentiles in ancient days;
that you might partake of his salvation, and of the power of his life,
and of the glory of his kingdom, with those that are gone before you.
I say, for this end hath the God of wisdom in his love reached unto you in that country,
with the rest of this age, that have waited for his salvation,
and have sought the rich things of his kingdom in his own way.
And now I am satisfied, that many of you in your measures,
can seal to the truth of Christ`'s words, who said, Seek and ye shall find;
for as He is faithful that hath promised, even so we have found his words sure and true.
And now my Friends, seeing it is certainly so, as many can witness,
that they have found that which is eternal, which belongs to eternal life,
having been guided by that,
which the cloud and pillar of fire in the wilderness was a figure of;
every one with all diligence hold that fast, which you have received,
that you may grow in,
and be guided by it in your further travels in the heavenly journey,
towards the blessed heavenly Canaan, which is still before you,
as the prize of the high calling of God in Christ Jesus.
And therefore observe the true mark, and still press forward towards the same,
as the apostles and ancient saints did.
Take heed, I entreat you, unto yourselves, and the exercise of your minds,
lest your eye inwardly be drawn forth to look at another mark; for if you do,
then will not the prize be the same that was theirs who were faithful unto death,
and so continued unto the end, and obtained the crown.
Therefore be you all watchful, to keep the enemy of your souls out of your hearts,
that He may reign who is your friend, for ever, who seeks your good,
and brings life and peace unto your souls, under whose government and peaceable dominion,
you will find rest and pleasure for your inward man.

And now, my dear Friends, since it is the Lord`'s Truth you have received,
and his holy power that you have felt in these countries,
even as his people in other parts--dwell you with it and in it with careful minds,
that you may therein live unto God, as such who have part in the first resurrection,
that you may reign for ever and ever over the power of the second death.
And all take heed of the mysterious workings of the wicked one,
who works in deceit by guile, in every transformed appearance,
to draw the mind out of the pure centre in the true power,
to the likeness and image which hath no life in it,
where there can be no steadfastness nor true reigning
over the will that is unruly and foolish.
Therefore, my dear Friends, keep your watch every one in your hearts continually,
that you may not be betrayed from that pure life, that yields virtue unto your souls,
and nourisheth up unto eternal life.
For I know, that the wicked one, in his deceitful workings you have been acquainted with,
and his evil design the Lord by his power, in his light,
hath discovered unto many of you; so that you by the same,
have escaped his hurtful snares, and yet live in that which must reign at last over all.
Keep your habitation in the power that is unchangeable,
wherein you may live forever without fading; for the power fades not,
but abides in its glory for ever; so that the first is the last, the root and offspring.
Blessed are they that have kept their first love,
and have stayed in their righteous habitation, into which the power did redeem them;
they do still witness a growing from grace to grace, from strength to strength,
and from one degree of holiness unto another, until they come to be purely like him,
who is their Redeemer, who shall change them, and bring them from glory to glory,
till they bear the image of the heavenly Man,
and be like him that is altogether glorious,
who is putting of his glory richly upon his Church which is his people in this day.

And therefore you that have received the Spirit of the Lord, and are acquainted with it,
do you follow it in all its pure leadings with faithful hearts;
for it will certainly lead all the faithful to know an increase of glory.
And take heed of the spirit of the world, which is not of God, but leads from him;
that spirit where it prevails, causeth to wither and fade,
and brings barrenness upon the soul, and darkness and death, and then the glory is lost,
and the image of the heavenly then is not borne; nor no man in that,
is heir of the heavenly inheritance.
Therefore it doth behoove all to look to their standing, in that wherein the heirship is,
that none may come short of that crown, which Paul said, was laid up for him,
and all them that love the appearance of the Lord Jesus Christ.
And so the God of love and peace keep you all, in his love, fear and wisdom,
that your dwellings for ever may be in his peace, which the world cannot take away,
nor rob you of; that so with the rest of his heritage,
you may shine in the light of his glory,
and dwell in the richness of his kingdom for ever and ever.
Amen.

This is the desire of my soul for you all, whom I truly love, and in the Life salute,
wherein I am your friend and brother,

[.signed-section-signature]
John Burnyeat.

--

I went that same day to Bristol, and stayed some meetings there;
and then I went down into Somersetshire, and visited Friends there,
and had many blessed meetings.
I returned back to Bristol, and stayed some meetings there,
and then went into Wiltshire and Gloucestershire,
and through Berkshire and into Oxfordshire, and so into Worcestershire,
as far as Worcester, and visited Friends,
and had many precious meetings through those counties.
From Worcester I returned again through Gloucestershire, and had several meetings:
and came again to Bristol; from thence I took my journey through several counties,
visiting Friends: and so came to London,
and stayed there some time in the service and work of the gospel.

Being clear, I took my journey for the north, and did not make much stay at any place,
till I came into Cumberland.
The reason of my so travelling was, because of a meeting,
which was agreed upon by Friends to be held at Draw-well in Sedberg parish,
about the former difference, which had been heard at Powbank;
chiefly occasioned by the aforesaid John Story and John Wilkinson,
and a loose sort of people,
whom they did countenance in a liberty that the truth would not allow,
and therefore could not be borne with by such tender Friends,
as were zealous for the truth, who kept their first love.
These therein delighted to uphold that ancient testimony for the Lord,
against the priests and their tithes, hire, and maintenance,
with other things that were to be borne witness against through sufferings;
and also for meeting together to worship God,
which from the beginning had been our practice,
there being divers statutes with penalties upon us, for so doing; for fear of which,
the aforesaid John Story and John Wilkinson,
with such as had let in the same fear through fleshly reasoning, did shrink and hide;
and so let fall the nobility of that testimony,
which we had received and were raised up to stand for in the beginning.
And so because of a failure in divers things,
and pleading for a liberty from under the exercise of the cross,
that the offence thereof might cease,
the faithful became concerned to stand up against that spirit,
which thus was likely to weaken or overthrow the faith and testimony of many,
through its subtle workings in and through divers; who,
like those the apostle writes against in his Epistle to the Galatians,
that tu avoid persecution endeavoured to bring the believers under circumcision,
that so the offence of the cross might cease,
or suffering for the gospel might be avoided.

Now this difference still continuing, and they abiding obstinate,
and not willing to receive advice, or bear the judgment in the Truth placed upon them.
Friends in condescension, to see if they could be gained,
appointed a meeting at Draw-well near Sedberg, that they might have another opportunity,
and be heard what they could further say.
Then the matters were fully gone through before many ancient, faithful brethren,
who were there assembled;
who spent four days in hearing and going through the matters relating to that difference,
which was occasioned through the opposition of those to the blessed order of the Truth,
who withstood Friends`' godly care for the preservation
of the dominion thereof in righteousness.
And when all things were heard and gone through by the brethren,
the judgment was again given in the power of the
Lord upon that spirit which they had let in,
whereby they had been led into a separation and division,
and opposition to the Truth and the holy order and testimony thereof;
and they in the same power and love with great bowels and tenderness,
were sought to return back again unto that spirit of love and peace,
wherein the unity and fellowship of the true body doth consist.
But alas! many of them would not be wrought upon nor prevailed with;
but in that hardness the enemy had wrought their hearts into, did persist,
until they became open enemies to the Truth and the faithful witnesses of it,
even to the writing and printing publicly against them,
and what the Truth doth lead into: and so are become such as the apostle writes of,
that greatly withstood their words, and slighted them: of which Paul, Peter,
John and Jude wrote.
This meeting at Draw-well, was in the second month 1676.

After Friends had done what could be done at that time,
with holy endeavours for the reconciling and gathering into the heavenly unity,
and making up of the breach,
I returned from thence again into Cumberland with several brethren, to wit, J. T., J. B.,
Hugh Tickhill, Thomas Laythes, John Steele,^
footnote:[See [.book-title]#Pike and Oxley,# p. 43.]
and so spent a little time in Cumberland;
and then I took my journey with John Tiffin towards London.
In our journey we came into Westmoreland to visit Friends there,
where we met with some of those, with whom we had to do at Draw-well:
and then they were grown hard, through resisting the counsel of the Lord,
and had set up a separate meeting, and so ran into the self-separation,
and grew more into the enmity, and stronger in the opposition,
through resisting the love of God,
that so richly was reached forth unto them in the heavenly bowels, which,
by the power of the Lord Jesus Christ,
were opened in the brethren at the aforesaid meeting at Draw-well.
For the power of the eternal God in great majesty appeared,
and in a weighty dread was judgment set and sealed upon that spirit,
by which they had been betrayed;
and by the same power and word of life was a door opened unto them who had been betrayed,
and an entrance in the same was set before them, and they,
with much brokenness and tenderness, in the power of love, were sought to return,
and be reconciled unto God, and unto his people.
But this great visitation being rejected by them, they grew harder and harder,
until they grew, many of them, as before said, enemies unto the cross of Christ;
and so they withered as to their spiritual state, and became as some of old,
whom the apostle wrote of, as trees twice dead, and plucked up by the roots.

From Westmoreland I went over into Yorkshire, had a meeting at Sedberg,
and went through the Dales to Masham, visiting Friends there-a-ways.
And then J. T. and I, with Robert Lodge, took our journey to York,
and from thence towards London, visiting Friends by the way;
and so we came to the yearly meeting in the year 1676,
where there were many faithful brethren assembled together from most parts of the nation.
Amongst many things of concern relating to the truth and the churches of Christ,
that division in Westmoreland was laid before the meeting, and how they were hardened,
and had set up a separate meeting,
and so had withdrawn themselves from the rest of their brethren,
and broken the Christian fellowship: which thing,
when understood by the brethren there assembled, was a grief unto them.
Therefore under the sense thereof, and in that brotherly love,
with which their hearts were filled towards them,
were there two epistles written from the meeting, one to John Story and John Wilkinson,
warning and advising them, as heads and leaders in that sedition and schism,
to endeavour to break up that separate meeting, and to be reconciled unto their brethren,
before they went abroad to offer their gift: and the other was written to the meeting,
as advice unto them to return to their former fellowship with Friends,
and lay that separate meeting down,
and join with their brethren in the unity of the Truth, etc.

But all this did not prevail with them; but still they grew higher and harder,
and went on in the strong resolutions of their wills.
Only there were divers individuals who were for a time
concerned in that opposition and separation,
whose understandings the Lord opened, so that they saw the snare of the enemy,
and returned; and under a sense of the Lord`'s judgments,
they gave forth divers testimonies in writing against that spirit,
by which they had been seduced, with a confession of the error they were led into;
and so returned into the true fellowship and unity of the Church of Christ,
and were received with gladness.
Glory to the Lord, who is the Saviour and healer of his people,
who now heals and saves by his word, as he did of old!

[.embedded-content-document.epistle]
--

[.letter-heading]
Epistle to Friends in Cumberland.

[.signed-section-context-open]
Taunton, 7th of Second month, 1677.

[.salutation]
My Dear Friends,

Unto you my love and life reach, and purely flow forth in that which lives forever;
wherein I do in the innocency and life of righteousness truly salute you all,
whom the Lord hath raised and called to be a part of
the first fruits unto himself in this day of ours,
wherein the glory of his hidden life he hath revealed unto a remnant,
even that which from the wise and prudent of this world is still hid;
and from such as turn back into that wisdom, it comes again to be vailed,
so that the light of the glory of it they lose again, though they had a view thereof.
Blessed are all who keep their habitation in that power which never changes nor decays.
The glory of the heavenly things will be still in their view,
by which their hearts will be enlarged towards the Lord, both in love to him,
and a living people to his honour in all things, that his name may be exalted,
and the testimony of his Truth, in its own pure nature in everything kept up,
according to its brightness and glory;
as by the power thereof we were raised up in the beginning,
as the life of holiness grew in us, dear Friends,
that which quickened and raised us from the dead in years past,
through which we live unto God; and as we keep in the same,
we shall for ever be accepted by him, and be well pleasing in his sight.
But out of that you know, none shall be regarded by Him, though ye might do much;
for he did not regard them in the days old for all they could do,
that did not keep in the life of righteousness, though they might go far,
even to the covering of the altar with tears.

And therefore, as I said, that by which you were first quickened and raised,
is that in which for ever we must be accepted;
so that every one is to mind and wait for an increase,
and experience the growth of that wherein there is a coming upwards,
from a child`'s state, to a farther growth.
Still it is in the same nature, without degeneration from that which was first,
and so the first is witnessed to be last,
and ye grow more and more into the fulness of Christ, in whom all fulness dwells.
Therefore my dearly beloved, in all your meetings upon the Truth`'s account,
have an eye unto,
and wait for an enjoyment of the blessed and heavenly
and heart-breaking power of the Lord God among you;
that your hearts may be broken thereby,
and your spirits melted into true love and contriteness, and you preserved in that state.
Then will your hearts be enlarged in the heavenly wisdom that is pure, peaceable,
gentle and easy to be entreated; and in that wisdom and power in you all,
will all your works stand to the honour of God, and comfort one of another,
and your eyes will always be to the promotion of Truth in righteousness,
keeping up your ancient testimony, into which God raised you by his power in years past.

In the life and power of God you will keep under,
and weaken that which would arise to trample his holy testimony under foot,
and so keep the house and family of God in order, and keep to the cross to that,
which would be out in a fleshly liberty, to make void the cross of Christ,
by which we were crucified to the world, and the world to us.
For that which would be from under the cross,
is the same that would lead into the world again;
and so would make shipwreck of faith and a tender conscience, and lead into headiness,
hardness, stubbornness, and looseness again;
and then they apostatize from the life of God that is in them,
and become reprobates concerning the faith, and so through forsaking their first love,
lose their reward at last.

The true elders,
elder men and elder women, ought to have this care upon them over the younger,
that all may be preserved in the first love, and first zeal, that none may lose that,
nor draw back into a fleshly liberty, down into the wisdom that is from below,
which hath not its spring in, nor from that heavenly gift;
which cannot keep the hearts pure, as the heavenly doth.
You know it was the gift of the heavenly power, that first quickened us,
and made us to live to God;
and you know it is the same that keeps our hearts tender and lively,
by which we live for ever.
For our life that we now live, is by faith in Him who is the power of God;
and we feed upon Him, and his flesh is bread, according to his own words;
for He is the living bread that came down from God, and still comes down;
therefore mind it, wait for it, and stand up for it,
and be not starved again upon the barren mountains of your own imaginations,
where this bread of life is not to be found.

Dear Friends, keep your men`'s and women`'s meetings in the Lord`'s fear and power;
and keep in the holy care where you may have a sense of your concern in the body,
and feel your place and charge, every one of you;
be zealous for righteousness in the particular and in the general,
and the Lord will be with you, as he hath been, I am witness;
for none dwell longer in the Truth and love, than they dwell in righteousness,
though they may make a profession.
Be not at all discouraged in your work for the Lord and his Truth,
by that spirit that would bring a light esteem
upon your holy care and godly order in the Truth;
for it is the same in nature, that in all ages endeavoured to lay waste God`'s heritage,
and obstruct his work, and laid stumbling blocks in the way of God`'s travelling people,
to cause them to fall, and to turn back again.
The Lord will blast every desire,
that those go about in this matter who let in this spirit, and bring his life over it,
and preserve his people therein; that in this life and heavenly liberty,
they may serve him, and praise him, who lives for ever, who is everlastingly worthy;
to whom be glory and dominion, world without end.

Dear hearts, you being living in my remembrance,
as also the heavenly seasons we had together, when I was last with you,
my heart is filled with love towards you; and in that I send these few lines,
as a salutation and tender greeting unto you,
that you may know you rest in my remembrance, as I believe I do in yours.

So the God of love and peace keep you all in his love and fear unto the end,
that your portion may be with Him in his eternal kingdom, where there shall be no sorrow,
but you may dwell in pleasure for evermore.

[.signed-section-closing]
From your friend and brother in the fellowship of the gospel,

[.signed-section-signature]
John Burnyeat.

--

[.embedded-content-document.paper]
--

=== A paper of John Burnyeat`'s, that came to hand since his works were printed.

[.signed-section-context-open]
The twenty-seventh of the eighth month, 1667.

In the morning, as I was laying upon my bed,
and my soul greatly afflicted under the view and consideration of the state of things,
as it was among Friends in the city of Bristol and some parts adjacent,
because of the great contention and opposition; and when I was under the exercise,
and my life appeared grieved, even until my soul was brought into sore anguish, at times,
and grief, to see how hard some were, and unruly and obstinate.
In this travail of spirit my heart being bowed, I said within myself,
and before the Lord, and unto him; I matter not, what I be, nor how much I be abased,
for we must pass through good and bad report, as the faithful in former times did.
And then when I was thus gone down into the grave of self-denial,
where I thought I could lie and be trodden upon,
the Lord God signified unto me by his Holy Spirit on
this wise:--Though thou be willing so to be,
yet will not I be trodden under; and further said, there are some of them,
that are as dead men before me, because they have lifted up their heel against me,
and have rejected my word, and slighted or set at naught my reproof.

And further the Lord God signified unto me,
that the spirit of Core and Balaam had entered, which would shut truth out of doors,
and pluck Christ from his throne,
and lead away the minds of people after their own inventions,
to worship the works of their own hands.
And He further signified unto me,
how that the plague of leprosy and sore judgment of hardness of heart was upon them;
and they had lost their beauty, and were not fit to come nigh the altar of the Lord,
nor to be in the Lord`'s congregation: and that he would decide the matter.

And further he signified to my comfort,
there was a Priest to stand between the living and the dead,
with a holy censer and pure incense, to make an atonement;
and the eyes of all the tender and sensible were to be towards Him,
that they might receive the law from his mouth,
and that his lips might preserve their knowledge.
And further, there was something also of the spirit of Cain,
which did appear had entered, even that which did envy Abel`'s acceptance.

When I had seen these things from the Lord,
and it was showed me I could speak forth the matter unto the people,
my heart was wonderfully broken within me; and I cried and said,
"`Woe is me! Must I be the messenger to carry this message unto this people?`"
And when I was under this exercise the Lord did signify unto me:
If I delivered his word faithfully, then should I deliver my own soul; but if not,
I should die for it; my life should go for theirs.
Then did the dread of the Lord`'s word, and his majesty strike me down,
and made me willing to be given up, without any more reasoning:
blessed be the Lord for ever, who both gives the word, and power to deliver it!

[.signed-section-signature]
John Buenyeat.

--

[.embedded-content-document.epistle]
--

[.letter-heading]
To Friends in New England, Virginia, Maryland and Barbados.

[.salutation]
Dear and well-beloved,

Unto you who are the called of God in those parts,
unto whom the visitation of his day hath reached,
and upon whose hearts the heavenly light thereof hath shined,
in its pure spiritual breakings forth, so that you are become the children thereof,
and do walk therein;
unto you all doth the tender salutation of my soul reach in the love of God,
and in the fellowship, which is a mystery, which is held in a pure conscience,
and continued, as we walk and abide in the light,
in which we have fellowship with the Father, and with the Son, and also one with another,
and so are of one family and household, partakers of that one bread,
which all the sanctified in all ages did feed upon;
which is that which we are to wait for in this day, that we may live thereby unto God,
and grow through the divine nourishment thereof up into his nature,
and into his strength, wherein we may triumph over the adversary,
as the ancients did of old, and rejoice in the God of our salvation,
who is our strength and tower of safety forever.

Dear Friends, great and large hath the love and kindness of our God been unto us,
who where strangers, aliens and enemies in our minds unto him, in this,
that he hath called and chosen us to be his people,
and to bear witness unto his appearance, and the shinings forth of his light,
and of the glory of his presence, whereby he hath richly comforted our souls,
and lifted up our heads above all sorrow,
even when the enemy hath thought to sink us down into the pit.
Thus hath the Lord dealt bountifully with our souls,
and been a ready help in the needful time;
to him be the honour and glory for ever and ever!
So that now it behooves all, after so many deliverances, favours and mercies,
to stick close unto the Lord, and seek his glory above all,
and that with all their strength, that so he who is the good Husbandman,
may be glorified through every one`'s bringing forth fruit,
according to Christ`'s command.

Now my Friends, this all observe, that none can bring forth fruit unto God`'s glory,
but as they abide in Christ the living vine; from him is the life received,
by which every one lives unto God; and it is by the virtue of that life,
that every one must act to his praise.
And therefore, see that you all retain it in its own purity,
and live in subjection thereunto through your whole day;
that you may be as fruitful branches, abiding in the right nature,
and bearing holy fruit: and then will you feel the holy dew abide upon your spirit,
throughout your age, that will preserve you from withering, your leaf from fading;
and so your fruit shall be ripe in due season,
and not be untimely brought forth in that which will not endure:
for that in which we have believed, will endure for ever.
The heavenly power which God hath revealed in our hearts,
and made manifest for a standing foundation, that is sure for ever; upon which,
as you all abide steadfast, the gates of hell, with all the power of darkness,
shall not prevail against you, but you shall be able to withstand him,
and keep your habitations in the dominion thereof,
and dwell in peace upon the rock of safety, in the midst of all storms;
and sing for joy of heart, when those that forsake this rock,
shall howl and lament for vexation of spirit.
For the Lord God will bring his day and his power over all, and upon all,
that fly to any shelter, or seek any other defence, that have once known his Truth;
and he will be unto such as a moth, and as rottenness, and their strength he will waste,
and their garment and clothing he will destroy,
and their beauty and glory he will cause to fade;
though they have been as a beautiful flower in the head of the fat valley,
yet will fading come upon them, even dryness at the root,
and withering and decaying upon the beauty of their blossoms.
And therefore let all keep unto that, and in that, which will not decay, come to nothing,
nor ever be turned into darkness, but abide in its virtue and glory,
in and by which the Lord hath visited you,
and through which his day hath dawned upon your souls,
the morning whereof you have known bright and clear, as without clouds,
in which you have seen the Son in his glory to appear unto your souls,
with his heavenly healing, warmness and virtue.

Now Friends, this is that which for ever is to be kept to,
that the day may be known to increase in the light and glory of it, in its own clearness,
without mixture, not mixing with it your own wisdom, thoughts, or carnal imaginations,
which do prove such clouds, where they are suffered to arise,
that they bring darkness over the understanding, and make the day cloudy and dark,
and so occasion wandering,
and to some turn the very eyelids of the morning into the shadow of death.
And through such things hath the enemy so prevailed over some,
that he hath brought them again into the night of everlasting darkness and confusion,
ere they have been aware whither he would lead; and thus as a man void of understanding,
over whom the adulteress hath prevailed, and so led down to the chambers of death,
have many followed those steps, that have taken hold on hell,
where misery is sure to be met withal.

Dear Friends, that which preserves from these dangers,
is that arm and power which God revealed in the beginning, by which, as we are witnesses,
he redeemed our souls out of many afflictions.
And therefore let it be every one`'s care,
to wait for a clear and sensible feeling of that same power in its own pure nature,
to spring in all your hearts every day, and then will your delight be so in it,
and your acquaintance, in a clear understanding, will be so with it,
that you will never be deceived, so as to take any other for it.
Then to your comfort,
will your heavenly peace spring under the power and
government of him that is the prince of true peace,
and so will your hearts be made truly glad, and weighty, and ponderous,
and not to be carried about with every wind;
for in this is the true and pure establishment of the soul,
with grace in the covenant of life for ever;
and these are they whose peace is of a standing nature, who are not given to change.
But this I have always observed, that where there is an uncertain spirit or mind,
though in some states into which, at times they may come, they may have peace,
and feel some refreshment, yet for want of constancy and steadfastness,
which is preserved through a true,
watchful and diligent attendance upon that which doth not change, which is sure for ever,
they lose their habitation, and their state of peace,
and come to be tossed in their minds, and afflicted in their spirits;
and also are the occasion of tossing, affliction and distress unto others,
who not being aware, may sometimes be in danger to suffer with them,
when they fly from the word, that should uphold, as it was with Jonah in the days of old.
And therefore it is good for every one to have their hearts established with grace,
and in the grace wait for a settlement, that under the pure teachings thereof,
they may be preserved from going into those things that will procure woe;
and so shall every one`'s state in that which is good, be more and more constant,
and then will there be a growing, and going forward and not backward.
For that which doth occasion any to linger, or draw back, is carelessness,
unbelief and disobedience; and in such the Lord`'s soul doth take no pleasure.

And therefore in that which doth not change, all live,
by which all changeable and mutable thoughts, and imaginations,
and desires will be judged down, and the spring of life over all will flow;
and the first will be the last; for in that the beauty and glory doth stand for ever.
And all that abide not in it, to grow in the virtue thereof, whatever they have been,
at the best will be but as a fading flower in the head of the fat valley,
as it was with Ephraim; the Lord will take no delight in them, but reject them,
and cast them out, as such whose beauty is gone, whose gold is become dim,
and whose wine is mixed with water:
and so as reprobate silver shall they be esteemed even of men,
because the Lord hath rejected them.

So the Lord God keep and preserve you all in that which was from the beginning,
and will endure unto the end, that in that ye may flourish and grow,
as the lily of the valley, and the tree by the rivers of water.
This is the desire of my soul for you all, who truly loves you in the love of God,
wherein I remain one with you, and am your brother in the Truth,

[.signed-section-signature]
John Burnyeat.

[.signed-section-context-close]
London, the 10th of the third month, 1667.

--

Upon the second of the tenth month, 1677, Oliver Morris, an informer,
came into a meeting in Mahuntleth in Montgomery in Wales, where John Burnyeat,
in the fear of God was speaking to the people,
and preaching the gospel of peace and salvation unto them, for their good,
as he had received from the Lord; the said informer, with several constables,
and many other rude people came twice into the meeting to break it up,
and made a great disturbance: but Friends sitting still,
only one who reasoned the matter with him, he at last went out,
and all his company to the stable,
and there took all the Friends`' horses they could find in the town:
but after meeting we got them again, they being then taken without any colour of law.
But the next day, the said informer went to William Pugh of Mathauern,
a justice of peace, so called, who came along with him, and meeting John Burnyeat,
and Thomas Ellis upon the road, stopt them both,
and caused them to turn back to an ale house, where this informer,
and William Pugh`'s bailiff, swore against them for preaching at the aforesaid meeting,
for which the justice fined them, and wrote a warrant and sent for a constable,
who by the warrant seized upon John Burnyeat`'s and
Thomas Ellis`'s horses with saddles and bridles;
and so they were constrained to travel on their way on foot,
till they could get to an ale house to get lodging.
This reward the Lord`'s servants received at their hands,
for their love and good will to the souls of people.

John Burnyeat`'s horse died within an hour and an half after seizure;
and the other Friend`'s died in the informer`'s hands within six month time.

[.embedded-content-document.epistle]
--

[.letter-heading]
To the Women`'s meeting in Cumberland.

[.signed-section-context-open]
London, 20th of fourth month 1678.

[.salutation]
Dear and well-beloved in the Lord,

With you my soul hath precious unity in the spiritual fellowship,
and nearness and heavenly oneness, which stand in that life,
by which we were first quickened; in which we live,
and in the increase of which we grow into a heavenly
understanding and true soundness in discerning and judgment;
whereby the faithful come to be more and more accomplished for their places,
and fitted for every good work,
that so they may answer their office and membership in the true body,
whereof Christ Jesus is the head; of which body we are made living members,
through his love, who hath called us, and in his Son chosen us to be heirs of life.

Dear Friends, yourselves know that he,
who through his bounty hath blessed us with spiritual blessings in Christ Jesus,
so that we are made stewards of his manifold graces,
doth now require answerable service from us all,
according to our gifts received from him;
and whosoever is found faithful to their gifts and places,
shall certainly witness an increase,
and grow in grace and in the knowledge of our Lord and Saviour Jesus Christ;
and so come more and more into true soundness, to the spirit of a sound mind.
For you know,
how richly the power of Christ was manifested in us and among us in the beginning,
and how wonderfully it did work for the redeeming of our hearts out of the world,
the vanity and pleasures of it; that we might love and affect heavenly things,
and delight in the glory of that which comes from heaven.
But since that time many have been the exercises, and weighty have been the trials,
that have been met with in our spiritual progress, through which the Lord hath led us;
and many temptations hath the Lord delivered us from, and led us out of;
and many weaknesses hath he passed by,
and trespasses hath he in his great mercy forgiven; so that to this day we remain,
and that in covenant with him: therefore have we cause to praise him,
and to sing unto him.

Oh! my dear Friends,
methinks I am as if I were talking with you of the Lord`'s
mercies and former loving-kindnesses and dealings with us;
and being also under a sense of our present state and capacities,
to which he hath brought us,
my bowels within me are even melted with a holy love and tenderness towards you;
and in that love I send these lines, as the salutation of my soul,
in that which lives for ever, and as a signification of that entire love,
which in my heart lives towards you; wherein I desire,
that both you and I may so mind our present state, and our growth,
and the increase of the mercies of our God unto us,
as to answer them by a faithful serving of him,
and one another in that love which thinks no evil, and is never weary of doing good,
and yet will not vaunt itself.
Now this is that which lives in my view, the power of Christ;
which was so richly manifested in the beginning,
and which did then work to the preparing of us to be a people fit to do his will;
and so it wrought into a cleansing, washing, and sanctifying of us,
that we might be holy vessels fit for his use.
Now being prepared, the same power in the faithful works mightily,
to the fitting and furnishing of us unto every good work,
that we might be to the praise of his grace, who hath called us;
and if we so be to his praise, we must grow in grace,
and in the knowledge of our Lord and Saviour, Jesus Christ.
And if we grow in the knowledge of Him, as we have known him to save us from sin,
and to destroy the evil one, and so to be our sanctification and redemption;
even so we must wait to know him to be made of God unto us wisdom,
that he may be our wisdom,
and that the fountain of it unto us may be the gift of his holy power in our hearts.
And so then, as it did mightily work in our hearts to prepare us,
even so will the same gift be felt to work mightily to furnish us with wisdom,
and to enable for every good work;
and so you will know him to be made of God wisdom unto you.
For the holy dread of the power upon the heart in righteousness being felt,
guides in wisdom him or her who speaks;
the same holy fear and dread upon the heart guides him in silence,
who in silence sitteth, whose mouth is not opened, and so he is made still:
and Christ your head, who is one in the man, and in the woman, is wisdom unto you;
and so here all will be kept in your places,
as you keep in subjection unto Him who is the Head, the Husband of the true wife.

So dear Friends, mind His heavenly power, and keep under a holy reverence unto it;
and that will keep you savoury and reverent in your meetings,
and clear and in a good understanding, and subject one unto another;
and so you will be co-workers together, and helpers one of another,
and you will come to have the benefit of one another`'s gifts: and thus as members,
will you supply in a blessed unity every one your office in the body.
Therefore my counsel, as a brother in love, unto you is, let all be subject: let none,
in whom the tender life in a heavenly reverence doth move for counsel,
advice or otherwise, quench it, or stop the service;
for in so doing others may be wronged, as well as the individual,
unto whom the Lord intends benefit by the gift; for it is not good to stop:
only let all take heed, that their own spirits may be subject,
that Christ may be head in all, and that he may be your wisdom.
And be open and ready in your hearts to receive counsel,
help and instruction one from another; and keep down the forward, heady and rash spirit,
that would run without reverence, and speak without the true fear,
from which none will rightly understand,
or have a true sense of the weight of the service of this day.

O! it is fresh in my heart, the dread, the reverence, the fear,
that our hearts were filled with in the beginning,
in which we went about Truth`'s concerns; this same is still to be felt and minded,
and then all will be kept savoury: and in this will all your meetings, your care,
and labour of love be a sweet smelling sacrifice unto the Lord.

And Friends,
let your monthly and quarterly meetings be kept
orderly for the service determined and aimed at,
that you may be retired from the world,
and such not concerned in the service proposed for such meetings; that so all that come,
may be either capable of doing service in a reverent mind,
or learn that which may be for Truth`'s honour, their own good, and your comfort.
Then will all you who are concerned, get into your service without straitness;
and so will be a help one unto another in your particular gifts,
and the spring of life will be opened among you;
and your meetings will be delightful unto you;
and you in that will be a delight one to another: and then with one consent,
in the pleasant unity you will do the Lord`'s work together,
as his servants and hand-maids, and be a part of his pleasant heritage,
which he hath chosen, and upon whom he rains down his blessings daily.

And so the God of peace and love fill your assemblies with his presence, life and love;
that you may flourish as the plants of his right hand planting,
and be faithful through your whole day, is the desire of my heart and soul,
who remains your brother in the Lord Jesus Christ.

[.signed-section-signature]
John Burnyeat.

--

[.embedded-content-document.epistle]
--

[.letter-heading]
Epistle to Friends at Bristol in the time of their sufferings.

[.signed-section-context-open]
London, 20th of the Third month, 1682.

[.salutation]
Dear Friends,

The love of my heart and soul is richly extended forth unto you.
Surely my heart is affected with the exercise you are under, and endure in this day,
wherein the Lord seems to be pleased to try you as in a furnace of affliction,
and to prove your faith and patience, that you may come to know the value of it,
even of that which is more precious than gold that perisheth.
Truly my heart believes,
that the Lord doth not suffer it to come upon you to destroy you, but to try you;
and when his good will is fulfilled in that, and they have filled up their measure,
whose hearts are hardened in their cruelty,
he will find a way to deliver and bring forth his tried and proved people,
whose hearts are right before him, and whose souls are wisely set to seek him.
To such shall all things be rightly sanctified, and the blessing,
and the peace and glory shall rest upon their inward man,
with the richness of that life which comes from heaven, for which you suffer;
for it is your innocent suffering for this,
as you have the witness thereof in yourselves,
that brings the crown and diadem of glory to be put upon the head of your inward man.
So that the saying of the apostle comes to be witnessed,
the Spirit of God and of glory shall rest upon you.

Oh my most dearly beloved Friends!
How is my soul melted into tenderness,
and my heart broken in the love of God towards you,
and in the sense of your long and weighty trials, that you have endured and gone through;
and yet for all must they seem, as if they were but beginning.
Is the strength of the hard-hearted such, that they are resolved to make a full end,
or to try what the Lord can do?
Will they prove their arm to the utmost?
Well, the Lord in his own time will manifest, that it is but flesh, and not spirit,
and therefore that which must decay and wither, and be dried up,
and so prove weak at last, when the unseen arm of the Lord, which they know not,
shall be revealed, and stretched out, and made bare;
which you that look not at things that are seen, have a faith in;
which faith is that by which you live, and in which you have your victory,
and in which your hope doth fasten as an anchor, both sure and steadfast.
So that though the winds blow, and the raging waves swell high,
yet you are preserved from being overthrown and destroyed.

Dearly beloved, methinks I find a word of sweet exhortation in my heart unto you,
whom my soul loves, who may be,
or are tried in this exercising day with bonds or imprisonments.
In the first place, get into a quiet frame of spirit within yourselves, every one,
and into a resignedness freely to the will of God, out of time,
looking as little at that, as you can; for if you do,
it will make your exercises worse and harder.
For this I have experienced, that when a man is most freely resigned to the will of God,
and in a right spirit most given up to suffer for him, he is fittest to have his liberty,
and most commonly it is the nearest to him.
Dear lambs, I know there is sometimes a travail in spirit,
to get into a right place with the inward man, when the outward man is in bonds;
but when the heart once gets thither, all things are made easy and comfortable,
by him who said, _My yoke is easy, and my burden light._

And now be all concerned thus to get through in your spirits,
and then you will feel that the word of God is not bound, but free;
and your souls will be free in it and its holy power, and so be fed by the milk of it,
that your souls will draw spiritually from it, by which you have been born again.
Being thus in your inward man renewed unto God, and up into his life,
where the habitation of peace and quietness is for your souls,
that they cannot reach to bring a disturbance to--and there feeling your ease, joy,
peace and pleasure to be such,
that you can in your prison-house sing joyful praises unto the Lord; then my Friends,
be watchful, tender and kind one unto another, and over one another, that love,
peace and joy may be maintained among you all,
who suffer rightly and innocently for the Truth of our God;
that so you may be one another`'s joy and crown of rejoicing in the Lord Jesus Christ,
your life and strength.

And dear Friends, where there is innocency and simplicity, bear one with another,
and help one another, that in your sufferings you may have fellowship one with another;
and so keep in the fellowship of the sufferings of Jesus Christ,
where all may be humble and tender,
that so while others are striving to provoke you to come out of your places,
and to offend the Lord, you may not provoke one another,
nor be an occasion unto any one to go out of their place in the Truth,
and so to lose their peace with the Lord and in his Spirit.
For I have observed, that there is a care to be +++[+++exercised]
amongst Friends, at such times and in such conditions, when they are kept up together,
that all things may be kept sweet and pleasant,
and that they may even join together in bearing the burden that is laid upon them;
and those that are more grown, and deeper in their experience,
of what they are called unto, may help the weak, and so fulfil the law of love.

Let not unprofitable discourse be gone into, for it may lead into a striving,
which may hurt the unity that should be kept in the light,
and hath sometimes grown into a heat, which hath set some spirits against one another,
which should have been one, and kept in the unity, where the love and comfort is.
And so all watching in the light,
and waiting to feel the healing power and life in your souls,
there will be a sweetness and heavenly oil over your hearts,
in which you will have a delight one in another, and in one another`'s good;
and this will help you all,
and so the strong will be comforted in the innocent and reverent care of the weak,
and the weak comforted in the love, care,
gentleness and kindness of such that are strong.
This preserves as a pleasant family, to the honour of the great Lord and Father.
And so then shall you see, how he will delight in you, and appear among you,
and enrich you, and bless you every one with a portion from himself,
out of his heavenly bounty, and divine rich treasure, that none will want bread,
nor refreshing wine to nourish you in the inward man;
but the holy gift in you will be as a well, springing up unto eternal life.

And so, you dear suffering children of the Lord God Almighty,
my heart and soul most dearly salutes you all,
and in the love of God I have unity with you in your blessed testimony,
for which you suffer; in which the God of all grace and truth comfort your hearts,
and bear up your heads over all your hardships and deep sufferings, which,
as I understand, are renewed and increased upon you.
That through him, for whom you suffer, who is your God,
and the great Lord of heaven and earth, you may be strong to endure and abide to the end,
to his glory and honour, who is over all, and worthy of all, blessed for ever.
Amen.

From your friend and brother, in that which shall outlive all hardship,
in which we have believed.

[.signed-section-signature]
John Burnyeat.

--

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
London, 1680.

[.salutation]
Dear Friends,

You whom the Lord hath visited and reached unto by his own holy arm of heavenly power,
for that blessed end for which he hath visited many nations,
and appeared unto many people, viz., that he might show glory again unto mankind,
which through sin they were fallen short of;
that so in his visitation he might renew that heavenly image,
whereby he might be glorified again among the sons of men;
and now in this great day of visitation, which hath dawned upon the nations,
you in these countries have been visited and reached unto,
and graciously saved and delivered from the snares of death,
and opened unto the way of life; so that you have both seen into that hidden glory,
and tasted of, and been enjoyers of, the power of that life which hath no end.
Now the care which always ought to dwell upon your hearts, is this,
that you may keep in possession that which you have received; that, as was said of old,
none may take your crown from you, or none may fall short of that rest,
which is prepared for the visited and redeemed of the Lord.
The way you have known, God hath showed it unto you, and called you to walk therein;
and the mark you have seen, the Lord hath set that before you,
that you might press towards it, as the ancient Christians did,
for the prize of the high calling of God in Christ Jesus.

And now, dear Friends, that which I desire all may be concerned in, is,
that there may be a pressing forward towards the mark, and a going on in this way,
which the Lord hath cast up or revealed, and called you to walk in;
for it is he that travels on, that shall come to the blessed end,
and obtain the crown of glory; and not such as linger or sit down by the way,
either to take up a rest, or look for another inheritance besides what God hath promised.
He that continues unto the end shall be saved; and he that is faithful unto death,
shall have the crown of life.
Therefore, let a concern be always upon your minds in this weighty matter,
that you may see how it is with you,
and whether you are still in your journey upon
your travel towards the mark for the prize.
And as you must mind whether you are in your travel, pressing forwards or no;
even so you must mind also, that you press forwards towards the mark,
or else you may come short of the prize, the blessed inheritance;
and so be such as James speaks of, that ask and receive not, because they ask amiss.
For the heavenly wisdom is to be sought after and waited for,
which comes down from above, and which teacheth and guideth in the heavenly way,
the heavenly path of life and salvation, where every one`'s steps will be sure,
and their goings will be established, and their understandings will grow.
For the just man`'s path will be as the shining light,
that shines more and more unto the perfect day:
here none will be like those that beat the air, or run at an uncertainty;
the apostle said, they were not such, yet there may be such,
whose pains and travels may be great.

Therefore, still I say, let your pressing be towards the mark,
in the sense of the Lord`'s power, which is the true guide, and the true cross,
which mortifies and crucifies the flesh with its affections and lusts,
and keeps self down in the death, out of reputation, for there is none due unto it.
For whosoever gives and seeks reputation to self,
which ought to be made of no reputation, such can never rightly seek God`'s honour,
nor work his work, nor obtain the right prize, nor attain the crown,
but must fall short at last; for it is in him that crucifies self,
and makes it of no reputation, that the election stands,
and in whom the heirship is for ever.
Therefore, dear Friends, wait to feel his power in your hearts,
and diligently mind the blessed work thereof;
that you may feel how it purgeth your consciences from dead works,
and cleanseth your hearts from sin; for sin defileth the heart,
so that it is not prepared for the Lord, he will not dwell therein.
Therefore it must be washed, and dead works must be purged away;
for no man can serve the living God therein;
it must be the living works in the living power, wherein we can be accepted.

And so let all mind the living power, which is the living guide,
which doth guide in the living way, and keeps alive unto God;
and so you will all be kept a living people,
and grow up in the living wisdom that is from above,
which is inwardly taught by the living gift, that is received from the Father of lights,
with whom there is no variableness, or shadow of turning.

And as you grow up in this wisdom, you will be constant; there will be an establishing:
and such will show out of a good conversation their works, with meekness and wisdom.
But sayeth the apostle, "`If there be envying, and strife in your hearts, glory not,
and lie not against the Truth: this wisdom descendeth not from above, but is earthly,
sensual, and devilish: for where envying and strife is,
there is confusion and every evil work.
But the wisdom that is from above, is first pure, and then peaceable, gentle,
and easy to be entreated; full of mercy and good fruits, etc.:
and the fruit of righteousness is sown in peace of them that make peace;`" so that
you may see the fruits brought forth manifest the wisdom from whence it comes:
the heavenly peaceable wisdom brings forth the peaceable fruits of righteousness,
and is full of mercy, is gentle and easy to be entreated, and full of good works;
but the earthly brings forth the contrary.
Therefore, sayeth the apostle, if there be bitter envying and strife in your hearts,
glory not, and lie not against the Truth; say not, thou art in the heavenly wisdom,
while this lodgeth in thee; for this wisdom descendeth not from above,
but is earthly and sensual, and therefore can never establish, but brings confusion,
because he is the author of it, who can never work good.

Therefore dear Friends, let your hearts be always kept in subjection to that power,
which bridles your wills and crosses them, and keeps you lowly, humble and gentle,
where the daily dying, which the apostle was in, may be witnessed;
and so you will see the true pressing forward towards the mark,
and the true growing into dominion over him that would hinder.
And you know, that he, whom we ought to hear, saith, "`Learn of me,
for I am meek and lowly in heart:`" and so, as every one learns of him,
and minds the leadings of his power,
and the teachings of his Spirit of grace in their hearts,
they will grow more and more like him, and come into his nature and healing spirit,
and so in his grace and life be as healers and saviours:
and therefore was it said by the prophet, they should be as saviours upon Mount Zion.

Now Friends, every one mind this saving, healing power in yourselves,
and bow in your hearts unto it, and be still in your minds and calm;
and then you shall see how it will sweeten you, level your spirits,
and bring down that which is high, and lofty, and hard; and you shall see,
how the mountains will melt at the presence of the Lord,
at the presence of the God of Jacob; and you shall see,
how the winds and seas obey your Saviour,
and into what calmness he will bring your spirits; and then when all is still,
your ear being opened, which is the first work of his word, you will be swift to hear,
and hearing, your souls will live: and you will come down out of all the noises,
floatings and swellings, into the calmness and stillness,
where you will admire your Saviour, and say,
_What manner of man is this, that even the winds and seas obey him?_
And you will see, that though Jordan overflow its banks,
yet at the leadings on of our Joshua, and at the entrance of the feet of our High Priest,
it must be driven back; that the ransomed of the Lord may pass over dry shod.
Much of this nature may be read in spirit, as there is a hearkening and keeping low;
but the forward, rash and hasty, are often tossed upon the waters,
and are very uncertain in their ways and doings;
and therefore do produce unto themselves much affliction of soul and spirit;
for to them the promise doth not belong, where it is said,
_He will keep them in perfect peace, whose minds are stayed upon him,
because they trusted in him._

Now Friends,
methinks the way is plain. May every one be careful to
attend upon the power and its openings,
and give way thereunto, and be humble; for it is the humble he teacheth his ways,
and the meek he will guide in judgment, and the willing and obedient he will feed;
for the promise is, they shall eat of the good of the land.
Therefore I do beseech all, be mindful, be you all careful,
keep your hearts out of the world, and the drowning,
surfeiting cares and pleasures of it, that you may neither be choked,
nor surfeited with the excess thereof,
nor be so led up into the worldly pleasures and liberty out of the Truth,
which that draws into, as thereby and therein to forget the Lord,
and to overlook your inward state.
For if any so do, they lose the glory, the beauty,
and the sweetness of their heavenly condition;
and then they grow weary of the way of the Lord, and are ready to say, as some of old,
_What profit is there in serving God, or in keeping his ordinances?_
And therefore may the God of life stir you up,
and awaken all unto watchfulness and diligence, that you may grow rich in the inward man,
and be replenished with the virtues and graces of God;
that you may be a fruitful people in those parts of the world,
to the honour and glory of him who hath called and visited you;
who is worthy of all glory and honour, praise and dominion for ever!

And dear Friends, my heart`'s love reacheth unto you all, who love and fear the Lord;
and in the love of God I dearly salute you all,
and send this as a testimony of that love, which still lives in my heart unto you,
and therein I remain, your friend and brother.

[.signed-section-signature]
John Burnyeat.

--

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
Hartford, 19th of the Fourth month, 1682.

[.salutation]
Dear Friends,

Unto you, whom God hath visited in his love and mercy,
and unto whom he hath showed kindness through his Son our Saviour,
whom he hath given for salvation unto the ends of the earth; unto you, I say,
doth the real love of my heart reach forth, and for you in my heart there dwells a care,
that as God in the exceeding riches of his love and mercy hath visited you,
and called you to be saints, through the sanctification of the word,
and purifying through faith, that you being made holy,
might become heirs of eternal life through his Son Christ Jesus,
and of that eternal kingdom, into which no unholy thing must enter.

And now, seeing you are called with this holy calling,
thus to be heirs through faith in the Seed,
in whom the election and heirship doth stand for ever;
do you all mind the heavenly rule and government of this holy Seed in all your hearts,
that your spirits may be kept in their places, in subjection and reverence unto Him,
whom the Father hath anointed,
and whose Spirit the Father hath sent forth into your hearts, to lead you into all Truth,
even into Him, who said, I am the Truth, in whom the fulness dwells;
that you might be in Him that is true, even in the Son, in whom the heirship is:
that so you may be heirs, yea, joint-heirs with Him, that is true and holy for ever.

And now my Friends,
seeing the Lord in mercy hath called you unto this high and honourable calling,
to be saints and heirs in Christ, mind your calling, and what you are called unto;
and be careful to keep in him, and walk in him, as you have received him,
and to sit together in him, in heavenly places, as the saints of old did:
for the heavenly places are in him, the safe dwelling, and he is the way,
and in him is the safe walking;
and therefore did the apostle exhort the saints to walk in him, as they had received him.
Now my dear Friends, all learn to know what it is to walk in Christ,
the power and righteousness of God, and then your steps will be sure;
for he is the light, and day, where there is no occasion of stumbling.
And you are to mind your sitting together in heavenly places in Christ, not asunder,
not out of the unity, but together in him, who is but one in all,
and holds all in oneness, in life and fellowship that abide in him.
For he cannot be divided, his coat was without seam; that was the figure,
and so is his Spirit, that is the covering of his body now,
which he hath purchased with his own blood; it hath no division or seam in it,
but is one, although it differs in manifestation or gifts, as to degree or operation,
because of the many offices proper to the distinct members of one and the same body,
whereof Christ is the head; yet the life through the whole body,
by which every member is supplied with ability to answer its place, is but one,
and thereby is the body kept in unity.
For the life doth rule the members of the true body,
and therefore that member that goes from under the government of the life,
must needs die; death comes over it, and the power of death rules it:
and hence come the breach of unity, and the discord, and the strife, and the contention.

Let all your hearts be kept in the sense of the true life and power of God,
and in subjection thereunto in true love, lowliness of mind and humility of spirit.
In this right frame of spirit you will be ready to serve one another in love,
and not to rule over one another in lordship; for that is not proper, no,
nor is it natural to the living members of the living body, unto whom Christ is the head,
and over whom he rules.
And so dear Friends, you all keeping in the power, and that ruling in your hearts,
that keeps tender and lowly,
you will be full of an holy care and the living zeal for the Lord`'s
honour and for the preservation of his people in righteousness,
that the Truth may be kept atop, and righteousness lived in by all,
who make a profession of that honourable name and Truth, in which we have believed,
and through which we have been saved, and sanctified, and made holy.
Then will unity, love and peace spring and grow among you,
and you will be a joy and comfort one to another,
and strengtheners and helpers one of another in this great work and day of God.
The faithful keeping their places, and their care in every meeting,
and minding the order and government of Truth in themselves, to be kept in humility,
and the holy tenderness in their own hearts,
there will be that sweetness and peaceable reverence,
that will be savoury and comely in the eyes of all.
Living and walking under the government of this peaceable spirit,
you may come to be rightly concerned for God`'s glory,
in the blessed order which the Truth hath led into,
and by the power of God is now set up in the churches of Christ,
for the keeping of all out, that are unclean, unruly and unholy,
and preserving the camp of God in that purity, that is proper for it;
that He who is holy, may delight to dwell in the midst thereof.

And dear Friends, all you that keep your habitations in the Lord`'s power,
neglect not your gifts received from Christ; but be concerned in your places,
and according to your abilities for the honour of Truth;
that everything that would bring dishonour to that worthy name,
by which ye have been called, and give occasion of stumbling to the weak,
may be removed in the wisdom of God,
or at least by the tender power of God judged out from among you;
that the camp may be kept clean, and righteousness may run down,
and the glory of the Lord break forth upon you,
and you therein may shine to His praise and glory for ever more.

I was also willing to let you know,
that our meeting this year at London was very quiet and peaceable;
blessed unity and comfortable fellowship in the
power and love of God were witnessed among us,
and in that we were gathered together, into that care and concern,
which the state of the churches of Christ in this trying day requires.
For many of our Friends, in divers places in this nation,
are under great sufferings for their testimony:
but otherwise the Truth doth prevail and gain upon many hearts;
and through these trials God will magnify his power in the end,
and crown his people with dominion;
for through sufferings will the Lamb and his
humble and faithful followers have the victory.

We had also account from divers countries, of the prosperity of Truth,
and the state of Friends, at the yearly meeting now lately over, as Holland,
and the country that way, and from Ireland and Scotland;
and so had an account in letters to the yearly meeting of the state of things,
and the affairs of Truth, to our great comfort.
And therefore it is desired, that if the Lord should so order, that we may meet together,
as hitherto we have done, and intend, if he permit to do,
that you in America would endeavour to send over
against that time from your several countries,
an account of the prosperity of Truth, and how it is among you as to the affairs thereof,
that at that meeting Friends may have an account from you, as we have from other parts.
And for this end it was desired by dear George Fox,
whom many of you know hath a general care upon him for the good of the whole body,
that at your half-year`'s meeting in the latter part of the year,
you might draw up an epistle,
which might be sent to be at London at the yearly meeting every year,
and so from your half-year`'s meeting in every place,
there may be an account given yearly, which will be a refreshment and comfort to Friends.
Therefore it is desired, that if this come in time to your half-year`'s meeting,
you would be mindful of it, and answer the desire of Friends;
and let copies of this be sent to Virginia, Maryland, Pennsylvania, and New Jersey,
and to Long Island, and Rhode Island, and to Sandwich, and where there may be a service,
or to Scituate, if the half-year`'s meeting be there, and to Barbados,
or the Leeward Islands.

So with my love to you all, in that wherein all the faithful have fellowship,
I conclude and remain your friend and brother in the Truth,

[.signed-section-signature]
John Burnyeat.

--

[.embedded-content-document.epistle]
--

[.letter-heading]
An Epistle to Friends of Bristol, directed to a C. J.

[.signed-section-context-open]
Eaglesfield, Cumberland, 1st of the Sixth month, 1682.

[.salutation]
Dear C. J.,

In that everlasting Truth and seed of life,
through which the God of Truth hath visited us,
is the love and true endeared affection of my heart and spirit richly extended unto thee,
with thy dear wife, and your children;
as also to the faithful and true-hearted to the Lord in that city,
who in this trying day are given up to God, both to do and suffer for his name`'s sake.
My soul, I can still say, is deeply affected with your suffering state,
and you are many times livingly in my remembrance,
and that in the near approaches of my spirit unto the Lord: for in that,
in which the access unto him is experienced, you are brought very often into my view,
with the suffering under which it is the pleasure of
your Heavenly Father to prove your faith and confidence,
and to let you know the preciousness thereof in the time of need.
And now my dearly beloved, see that you keep in the faith that gives the victory,
and truly saves and defends; and know that ancient saying true for ever,
_The very hairs of your head are all numbered, and not one shall fall to the ground,
without your Father`'s providence._
Therefore let your eyes be unto him, for salvation and preservation,
and know that He can and will deliver, when he sees good;
for you know him that is the living God, that reigns, and will reign over all,
and in due time make all know that he can do whatsoever
he pleaseth in heaven and in the earth.

Mind your knowledge of him, in that which may be known of him in your hearts,
and your unity with his life in your souls, that you may all feel the peace thereof,
and the holy spring therein, which man by all his cruelty cannot put a stop to.
But when they that seek to destroy you, and to take all comfort from you,
have done all they can, this spring being open in your hearts, you have comfort,
peace and joy, that they neither know, nor can keep from you.
Oh! you dear suffering children and tender babes of the Almighty,
who are called to this day of temptation or trial,
how is my very heart`'s love let forth unto you at this time, as at many other times!
The Lord, the God of strength,
be with you and strengthen and fill your tender souls with the glory of his life,
and the sweetness of his presence,
that your spirits may praise him with gladness in the midst of all these exercises,
with which you are compassed.
And now my dear Friends,
methinks I see the wall with which the God of Israel doth compass you about,
over which the adversary cannot shoot an arrow;
though his boasting may be great what he will do, as it was of old.
Oh! happy are they that abide within it, and spread their cause before the Lord,
who is the living God.
Remember the king of old, who commanded silence, and said,
_Answer him not a word,_ and so returned to the temple and to the altar of the Lord,
and spread the cause before him,
and confessed the weakness of the daughter of Zion to bring forth;
and also his faith in the sufficiency of God`'s power, when he said,
_Thou art able to save,_ etc.

Live up to the Lord in your spirits, and be faithful,
and keep your peace with him in the inner man, and mind your unity with his Spirit,
and take heed of that which would obstruct your fellowship with his life;
let no fair pretences prevail over you,
that may have any tendency to bring you into bondage;
for that bondage will prove the greatest slavery: and this I believe you know right well.

And now my dear Friends, all of you minding your inward freedom, and your spiritual ease,
in the freedom and liberty given you of God through Christ your Saviour;
you will have a habitation filled with glory, riches and comfort, over
which the enemy`'s cloud cannot come: and in that you will see through to the end of all,
that would either darken, or bring distress.
You will see how good it is to trust in the Lord, and to rely upon his power,
and be given up freely to his will.

My love is truly unto you all, and in the love with which I have anciently loved you,
do I salute you all, you tender suffering children; and with my soul and spirit desire,
that God in mercy and kindness may bless you with spiritual blessings in Christ Jesus,
and enrich your souls with the Divine fatness of his house, and pleasure of his life,
that you may have joy every day, and delight in your bosoms;
that so your strength may be renewed, and your ability so increased,
that you may be able to bear what is upon you,
till the Lord see good to work your deliverance,
and ease you of the yoke and burden that you bear.
Which the Lord in mercy take off, if it be his pleasure,
is the desire of Your friend and brother in the
fellowship of the sufferings and tribulation,
and also of the consolation, which we are called unto through Christ Jesus our Lord.

[.signed-section-signature]
John Burnyeat.

--
