== The Testimony of Friends in Cumberland, concerning that faithful servant of the Lord John Burnyeat, belonging formerly to Pardsay meeting in Cumberland.

He was born at Crabtreebeck, in the parish of Lows-water, in the said county;
his parents were of good repute, and his education was according to his parentage.
The Lord visited him in his young and tender years,
and inclined his heart after good things;
whereupon he gave himself to reading the Scriptures,
that thereby he might be informed of those things that made for his soul`'s peace;
and going from one man to another, who were counted men of experience,
yet found no true satisfaction,
until it pleased the Lord to send his ministers
to turn his mind to the invisible word of life,
which he gladly received into his heart, and came to wait in humiliation,
to feel the operation of it.
So that he was brought forth early in the day of the
breaking forth of God`'s light and power in our age,
when it pleased God to visit many people in divers nations of the world,
and to make known his everlasting Truth in the North country;
which day of light and truth, and grace, many waited for,
and were in readiness to receive with joy and gladness of heart.
Amongst whom this our dear friend John Burnyeat,
being called by grace to the knowledge of the Lord, his truth and power,
and receiving the same in love, faith and obedience,
he came to witness the effectual working thereof to his sanctification,
and so became a vessel of honour fitted for his Master`'s use, even Christ,
and learned to rule his own house well, in washing first the inside,
and the outside appearing clean also.
Then his light began to shine before men, to the glory of God, that called him.
And this being first done in him, and for him,
to his particular peace and satisfaction in the Lord`'s eternal Truth,
then the Lord opened his mouth in a few words in much tenderness,
which tended greatly to the comforting of his people;
he always being careful to wait for the motion of the Word, and to keep close with it:
whereby he grew in his gift, and was drawn forth to visit Friends in this county,
where we dearly loved him.

He was faithful in the discharge of his duty,
when called to give testimony against the hireling priests in the steeple houses,
to gather people from the mouths of those greedy shepherds that feed themselves,
and not the flock, and did not profit the people at all.
And for these things he suffered imprisonment a long time under a severe jailer,
in a close, nasty place.
For the Lord sent him forth in his joyful opening power and spirit,
to preach glad tidings of salvation by Christ Jesus, sometimes to the spirits in prison,
and to them coming out of prison,
and entering into the glorious liberty of the sons of God;
and to them who walked steadfastly in that glorious, pure liberty;
"`he that hath an ear to hear,
let him hear;`" whereby he was a blessed instrument in the hand of the Lord,
both for convincing and converting to God, and for the refreshing,
comforting and strengthening of them in the faith, grace and truth,
that they might be built on the rock Christ,
the foundation for all the chosen of God in him throughout all generations,
that man might answer the end for which he was made, even to glorify God;
who is worthy of glory and praise forever!

He was a man of an excellent spirit,
and of deep experience in the things of God and mysteries of his kingdom,
which were richly made manifest unto him:
and it was his delight to be meditating therein;
whereby his experience was daily increased unto the conclusion of his days.
He was a man tender of God`'s glory,
and earnestly sought the spreading and propagating of the Truth.
The Lord made his travels successful, and he saw the fruit of his labour;
and the Lord blessed him with the fruits of his holy Spirit,
whereby he became well qualified for the work of the ministry, a nursing father,
lending a hand of help to the feeble of the flock, and comforting the mourners in Sion.
For his doctrine did drop as the dew, and his speech as the small rain.
He was a pattern of righteousness to the young generation, over whom he was very tender:
and to the aged he could give counsel;
so that God made him a strong pillar in his church, and clothed him with divine wisdom,
that he was capable of speaking a word in season to all,
which was as a nail fastened in a sure place.

He was one of the Lord`'s worthies in his day, of a quick sight and clear discerning;
of a strong arm and skillful hand, whose bow abode in strength,
and carried the arrows to the mark aimed at: like as the men of Benjamin,
that could sling stones to a hair`'s breadth;
so he fixed judgment upon the head of the transgressor.
And his arrows returned not in vain,
particularly against that wicked spirit of separation, wherever he met with it.

He was often concerned in testimony against
those that professed the Truth and way of God,
and yet did incline to suit themselves to the vain fashions and customs of the world,
as inlets to a wrong spirit, and became evil precedents to others,
especially young people,
that are too much employed in their minds with foolish dresses and fashions,
who never knew the weighty work of Truth and power of
God in their hearts to work a change there;
but were too apt to look out at others.
These things he did often testify against, as one having authority,
being himself redeemed out of those things by the power of God.

His innocent deportment and blameless conversation preached wherever he came.
Gravity and patience were with him; moderation in meat, drink,
and apparel--having laid aside all superfluity of naughtiness
and received with meekness the engrafted word;
all which were as ornaments upon him, and preached for the Truth abundantly:
as also did the many living testimonies he bore,
that flowed through him as showers upon the tender grass.

He was a true labourer, who spared not his life unto death,
and was willing to spend and be spent,
that he might gain upon the sons and daughters of men,
to turn them from darkness unto the true light, and from the power of Satan unto God.
Oh! what shall we say of him! he was a faithful preacher of the gospel,
not only in words, but in life and practice, and his memory shall live forever.
For his labour and travel both at home and abroad, in prison and at liberty,
have been such as cannot easily be forgotten by many,
who have reaped the benefit thereof.
For the Lord was pleased wonderfully to appear by him, and sound through him,
to the awakening many to righteousness,
and greatly encouraging all the faithful amongst God`'s people.
In deep exercises he was as a skillful physician,
to apply that which was suitable unto all; yea, he was quick and sharp,
on the one hand to search, as on the other hand to cure, heal, bind up and comfort:
but unto the hypocrites he was dreadful and terrible,
though he was a man of large compassion.
Many an untrodden path he travelled,
and passed through great dangers both by sea and land in visiting Friends,
not only in England, but also in Scotland, Ireland, Barbados, New England,
with the islands adjacent, passing through wilderness places and dangerous waters.
Through all which the Lord in a most wonderful manner preserved him,
with the rest of his servants, from the hands of wicked and unreasonable men,
and was ever near him for his preservation both inwardly and outwardly.

The Lord clothed him with humility before all, as became the gospel he preached,
which he preached freely, counting nothing near nor dear unto him to be parted with,
suffered, or to be done,
but a willingness was wrought in him through the mighty power of God,
who always strengthened him to do, to suffer,
and to undergo all things whatsoever for his worthy name`'s sake.
Although the Lord had bestowed eminent gifts on him,
yet he would condescend to the weak capacities of all, to reach to the good in all,
that he might lay a foundation to build upon.
He had the word of reconciliation committed unto him,
whereby he was made instrumental to reconcile many to God by Jesus Christ,
and one unto another.
And the Lord caused him to triumph in Christ,
and made manifest the savour of his knowledge in many places,
and his ministry is sealed in the hearts of many,
who are satisfied of his faithfulness unto God, who hath received him into his rest.

Now although his body be gone to the dust, yet his spirit lives; and that word of life,
which was his pleasure, remains for our comfort, who are yet behind in that pilgrimage,
which he hath passed through;
and may be attended with the temptations which he is delivered from;
who hath finished his day`'s-work:
whom the Lord raised up to shine forth as a star in
several parts of the northern and western world.
And his mild and grave deportment did so well become his deliberate ministry,
that it greatly heightened his esteem amongst his neighbours;
so that he was not without honour in his own country.
And when at any time he came into Cumberland, where he was born and educated,
his neighbours would abundantly flock to the meeting to hear him.
Yet he was far from glorying in his gift, or desiring to be popular;
but would rather restrain such, who would applaud him; having self in no reputation.
He may be truly numbered among the righteous,
who sought God`'s glory and the peace and unity,
flourishing and prosperity of his church, which Christ is the head of.
Much more might we say concerning him, but shall attribute nothing to him,
but to the Lord`'s power, that did support him.

And now, if Samuel had cause to mourn for Saul,
and the children of Israel wept thirty days for Moses,
much cause have many now to mourn for the loss of so dear a friend.
But though our loss be great, his gain is beyond utterance;
who hath received the blessed recompense of reward for his labours and travels,
for all his service and suffering.
And having finished his course and time in this world,
is entered into life and happiness everlasting in the world to come.
And we pray the Lord of the harvest, to raise up other labourers in his room,
and also in the place of others that have finished their testimonies for God and Christ,
that God over all through Jesus Christ may have the honour, glory and praise,
from generation to generation, who is blessed forever.
Amen!

[.small-break]
'''

_"`Mark the perfect man, and behold the upright, for the end of that man is peace.`"_ Psalms 37:37.

[.small-break]
'''

[.signed-section-signature]
Philip Burnyeat, John Tiffin, John Banks, Thomas Laythes, Thomas Dockwray,
Christopher Wilson, Thomas Fletcher, Richard Head, Christopher Story, Peter Fearon,
Jonathan Bowman, John Bowstead, Thomas Wilson, James Dickinson.

[.signed-section-context-close]
Broughton, in Cumberland, the 22nd of the Second month, 1691.
