[#testimony-women.style-blurb, short="Testimony of Cumberland Women Friends"]
== The Testimony of several women Friends in Cumberland.

In brokenness of heart and tenderness of our spirits we have this
testimony concerning our dear friend and brother John Burnyeat;
that he was one of the Lord`'s worthies,
chosen and fitted by him for his work and service,
and it was his whole delight to do the will of God;
so he came more and more to know of his doctrine,
whereby he was made a good instrument in the hand of God,
for the converting many from the error of their
ways to the way of truth and righteousness.
He was one on whom that prophecy came to be fulfilled,
that saviours shall come upon Mount Zion to judge the Mount of Esau,
and the kingdom shall be the Lord`'s. For he
well knew how to divide the word of God aright,
which dwelt plentifully in him as deep waters, and the well-spring of wisdom,
as a flowing brook; so that he was often as a cloud full of rain,
emptying himself at the Lord`'s command, causing the seed of life to spring;
whereby God`'s inheritance was confirmed.
He was a man of a thousand, clothed with innocency and beautified with humility;
words are too short to set forth the excellency of that spirit by which he was guided;
neither can we express fully, what is in our hearts concerning him.
Yet shall we attribute nothing to him, but to the Lord`'s power,
that wrought effectually in him, to the making him to shine.
For he was an instrument of good to many, making a difference; saving some with fear,
pulling them out of the fire, hating even the garment spotted by the flesh:
being found in that pure and undefiled religion of
visiting the fatherless and widows in their affliction;
and through the grace of our Lord Jesus Christ keeping himself unspotted from the world:
and therefore knew how to save upon Mount Zion, and judge upon Mount Esau.

Much might be written concerning him,
for we know the very desire of his heart and bent of his spirit was,
that God through his Son might reign in the house of Jacob,
and the kingdom might be the Lord`'s. He abhorred the appearance of gathering to himself,
and had self of no reputation; therefore the Lord honoured him with his divine presence,
and made his company, although dreadful to the backsliders, yet very desirable unto many,
especially those who knew his integrity and zeal
for the exaltation of the name and truth of God;
in whose hearts he was highly esteemed for his works`' sake, which shall follow him,
although he is at rest from his labour, being got to his desired haven,
where the wicked cease from troubling, and the weary are at rest.
And there the prisoners rest together; they hear not the voice of the oppressor,
for the accuser of the brethren is cast down, temptations cannot enter;
an overcoming is known by the blood of the Lamb, and by the word of their testimony,
who have not loved their lives unto death.
And to him that overcomes, saith Christ Jesus, will I grant to sit with me in my throne;
as I also overcame, and am set down with my Father in his throne:
he shall not be hurt of the second death, but with Abraham, Isaac and Jacob,
and with all the faithful in the kingdom of God, without ceasing sing praises unto Him,
who sits upon the throne, and to the Lamb forever and evermore; who is worthy!

O the great loss we have of him!
How can we but lament; yet it is his everlasting gain: for he shall never return to us,
but we may go to him.
And that word of life, in which his life was hid, yet remains for our support; which,
as we are careful to keep to, will preserve us, as it has done him,
to enter into that mansion of glory the Lord hath in store for all the faithful.

He was dear unto us in the Lord,
with whom our souls were bound up in God`'s everlasting covenant;
and though his body is gone to the dust, yet our souls rejoice with many more,
in that we enjoy his spirit,
and are come to the general assembly and church of the first-born,
and to God the Judge of all, and to the spirits of just men made perfect,
and to Jesus the Mediator of the new covenant, and to the blood of sprinkling,
that speaks better things than that of Abel; where our joy is full,
and our spirits bowed and subjected to the will of God,
where our peace flows and the life arises, that fills our hearts with praises,
that ascend as sweet incense to the Lord God and to the Lamb,
who is blessed forevermore!

[quote.scripture, , Ps. 37:23]
____
The steps of a good man are ordered by the Lord, and he delighteth in his way.
____

[quote.scripture, , Dan. 12:3]
____
And they that be wise, shall shine as the brightness of the firmament;
and they that turn many to righteousness, as the stars forever and ever.
____

[.signed-section-signature]
Margaret Fawcet, Mary Wilson, Jane Wilson, Mary Bowman, Margaret Head, Sarah Fallowfield,
Jane Hall.

[.signed-section-context-close]
Broughton, in Cumberland, the 22nd of the Second month, 1691.
