[#testimony-g-f.style-blurb, short="Testimony from George Fox"]
== A Testimony concerning the life and death of our dear friend and brother in the Lord, John Burnyeat, by George Fox.

He was a faithful friend and brother, and an able minister of Christ Jesus,
who freely preached the everlasting Gospel, and laboured to keep it without charge;
who was a true apostle of Jesus Christ, and preached him freely, both by sea and land.
He received the Truth in 1653, in Cumberland,
and died in the Lord in Ireland in the year 1690,
after he had stood those great troubles, storms and trials there.
He was a great strength to Friends in the time of their late great sufferings;
he stood it out, when many were ruined, and fled to England for succour, and he remained,
till after King William came in, and King James went out of Ireland.
And then he went up and down visiting Friends`' meetings,
that were gathered in the name of Jesus:
and afterwards he had intended to come for England; but there he died in the Lord,
and is blessed, and rests from his labours, and his works follow him.
He travelled and preached the Gospel in Ireland, Scotland, Barbados, Virginia, Maryland,
New Jersey, Long Island, Rhode Island, and up and down in New England,
and had many disputes with many priests and professors, that opposed the Truth:
but the Lord gave him dominion over all, and to stop the mouths of gainsayers;
and he turned many to the Lord, and was a peace-maker;
and he preached in his life and conversation, as well as his words.

He travelled with me from Maryland through the wilderness, and through many rivers,
and desperate bogs, where they said never Englishman or horse had travelled before;
where we lay out at nights, and sometimes in Indian houses,
and many times very hard put to it for provisions:
but the Lord by his eternal arm and power did support us,
and carry us through all dangers; blessed be his name forever.

He was an elder, and a pillar in the house of God:
and the name of the righteous shall be had in everlasting remembrance;
but the name of the wicked will rot.
He was a man endued much with the wisdom of God,
and in it had a care of the welfare of the Church of Christ, to keep in peace,
out of strife and contention:
and laboured with the apostates and backsliders
to turn them to Christ and his peaceable truth;
so that they might study to be quiet, and keep in the unity of the Spirit,
which is the bond of the peace of the King of kings, and Lord of lords.
Much more I might write concerning our dear
brother in the Lord,--I knowing him very well,
and his travels and service in the Lord`'s power and truth;
and so doth the Church of Christ, among whom he will be missed.

But he is gone to his rest;
and the Lord by his eternal arm and power is able to raise up others in his place.

[.signed-section-signature]
George Fox

[.signed-section-context-close]
The 13th of the 9th month, 1690.
