== An account by way of Testimony concerning our dear friend and brother John Burnyeat.

We will leave to others the account of his birth and convincement,
who were his neighbours and kindred; and shall speak of him only,
as some of us knew him from an intimate fellowship in
divers services for above twenty years.
He was a choice and seasoned vessel of Christ,
the special workmanship of his power and wisdom,
by which he was effectually qualified for the ministry of his everlasting Gospel,
thoroughly furnished, may we say, to every good word and work, +++[+++which]
God called him unto:--deep and large in his gift,
reaching what was seasonable to every state; in judgment sound, free in utterance,
zealous for holiness; severe against unsound and dividing spirits:
most tender to penitents and returning prodigals, affectionate to the brethren,
and careful over the flock of God, that they might answer their heavenly call,
and grow in the truth: of a grave and steady temper, yet sweet;
hardy in his constitution, and undaunted and unwearied in mind.
He was the father of many children in Christ,
who through his ministry were begotten again to a living hope;
and the builder up of more, through the same, in the precious faith of God`'s elect.
For this he often travelled through this nation, and sometimes Scotland,
and the plantations in America, but Ireland in a more peculiar manner,
both at his first entrance upon his ministry, and of latter years,
where he married and chiefly resided, and where he laid down his head in peace with God,
and love to his people, and good-will to all men;
being about the fifty-ninth year of his age; and is entered into eternal habitations,
to praise the God of his mercies in the living
family of the spirits of the just for ever.

He was indeed a man of an excellent spirit and divine understanding from God;
and deep in the knowledge of the heavenly mysteries of the kingdom of God,
and also of the depths, wiles and subtle workings of Satan,
wherein he lies in wait to beguile the children of men:
and the Lord many times opened him in his heavenly wisdom to declare of them,
that those who had regard to God, and the peace of their own souls,
might be preserved out of Satan`'s snares.
He was an able and powerful minister of the Gospel of salvation,
a strengthener of the weak, and an encourager of the upright and sincere-hearted,
to continue to the end.
But he was dreadful to the hypocrites and rebellious,
and all the opposers and gainsayers of the truth: a skilful marksman,
yea one of the Lord`'s worthies of Israel, a valiant man in the camp of the Lord,
and an undaunted warrior in his holy host; and his bow abode in strength,
and wisdom was given him to direct his arrows to the very mark;
so that the stu rdy were wounded, the meek were comforted,
the tender in spirit refreshed.
And he was by the Lord made instrumental to
wound that self-separating and dividing spirit,
that had,
for want of watchfulness in the divine light and faithfulness
to God`'s Spirit and truth in the inward parts,
prevailed over some; who, notwithstanding in a disguise and under specious pretences,
endeavoured to sow the seeds of dissension, discord,
separation and division among the gathered of God.
The Lord blessed his labours greatly, and so preserved him in a holy conversation,
and in a meek, tender, bearing, healing spirit;
that he promoted both by doctrine and practice that
holy truth he professed and was a preacher of,
and made full proofs of his ministry in many lands and countries:
and at the great city of London, where he was made instrumental to the good and comfort,
refreshment and edification of many;
and was valiant there (as in other places) in the time of trials, sufferings,
storms and persecution.

He was also a great encourager of the good in young and old,
and as a tender father and loving brother,
to those who were young in their testimonies for the Truth,
and would rather help a young branch to strengthen it in its growth,
than to bruise or hurt it in any measure.

This short testimony we dedicate to his memorial,
which shall be had in everlasting remembrance;
for his name is written in the Lamb`'s book of life,
where none can blot it out;--oiir brother, our friend,
and our beloved companion in the heavenly fellowship,
with whom some of us have sometimes travelled in England and
Ireland upon divers services for the Truth`'s sake;
and blessed was our labour of love together.
He was an apostle among the churches of Christ;
and he is a fixed and bright star in the firmament of
God`'s heavenly power and kingdom for ever.
O! Friends, you that knew him, know the loss of him in the Church of Christ,
with other faithful brethren since departed, and worthy of double honour;
concerning which sad providence we have this to say to you,--it points
plainly to us the evil that is to come upon the wicked and unfaithful,
and the great calamities that are at the door.
The Lord fit us all for them,
that we may find an interest and sanctuary in
the Truth above the reach of this evil world;
which they will want, that do not prefer it +++[+++the Truth]
above the chiefest joy.

[.signed-section-context-close]
London, the 10th of the eleventh month, 1690-1.

[.signed-section-signature]
Stephen Crisp.
Charles Marshall.
William Bingley.
John Field.
Francis Stamper.
Jasper Batt.
William Penn.
Benjamin Antrobus.
John Vaughton.
Benjamin Bangs.
Samuel Waldenfield.
John Butcher.

+++[+++Presumed to be issued from the Morning meeting of ministers and elders.]
