== Chapter IV.

[.chapter-synopsis]
* In 1670, again sails for Barbados with William Simpson
* Simpson`'s death
* Visits New England and other parts of the Colonial States
* Meets with George Fox
* His travels and service in those countries.

In the fifth month, all things being ready,
William Simpson and I went down to Gravesend with many Friends from London,
who accompanied us; and staying there but a few days,
we set sail from Gravesend the eighth day of the fifth month, 1670,
and came to the Downs, and stayed there some days,
and then set sail from the Downs the twentieth day of the same month:
and because of contrary winds we put in at Falmouth, and stayed two nights there;
and then put to sea again, and sailed for Barbados,
where we arrived the thirtieth day of the seventh month;
so that we were twelve weeks from Gravesend before we got to Barbados.

I stayed in Barbados six months,
and had great and weighty service in that Island before I could be clear.

[.embedded-content-document.epistle]
--

=== Epistle to Friends in Barbados.

[.signed-section-context-open]
Barbados, the 30th of the Eleventh month, 1670.

[.salutation]
Dear Friends,

I have a great exercise upon my spirit concerning the late observation of a day, or fast,
which was set forth and pretended to;
and seeing the pride and vanity that people were in, not like true mourners and fasters,
and such as would have the judgment removed;
and also seeing the bitter cruelty that appeared as a part of the fruits of it;
and the difference that did seem to appear in Friends`' minds,
about the owning or not owning of it, by submitting to their requirings,
or doing to the contrary as a testimony against it;
after I had passed under a deep exercise in spirit for some time,
at last the Lord God by his eternal Word raised up my spirit in the zeal thereof,
and did smite against all such mockeries.
And then in a heavenly revelation,
(my understanding being opened, and closing with the word) he showed me,
that it was to be witnessed against by all who stood in the testimony of God;
and that those,
that would weaken the spirits of any in their testimony in this or other things,
wherein Friends have a testimony for God, it was plainly showed me from the Lord,
how they would draw a veil over the pure in themselves and in others, and in a cowardly,
subtle spirit, by the corrupted, fallen wisdom,
would put the candle that God has lighted, under a bushel or under a bed,
and so cover it for a while, until at last it would be put out.
So that we, like other professors,
at last by this spirit would be led to yield to anything, rather than suffer;
and then the offense of the cross might cease.

And there was another thing, which had been very long under my consideration, of which,
I was not hasty to judge, wherein Friends have somewhat differed;
but at this time was not minded by me, because of the other, that was upon me.
But when the Lord had cleared the other to me, he brought up this also before my mind,
which is about sending men, horse, and arms to the training, trooping or playing,
which is folly as to us; for which many, that could not send,
have suffered the spoiling of their goods.
The Lord plainly satisfied me, that it was his testimony, wherein Friends were to stand;
and that they that bore another testimony either in words or action,
it was from that spirit, and in that wisdom,
that would put a bushel over the lighted candle, and by degrees would put it out,
and would lead us to crouch to the spirit of the world,
until its large wing of darkness would over-shadow us, and become our covering;
and then we should be like others, who have lost their testimony.

And when the Lord had thus done, oh!--how my soul was filled with heavenly,
divine love towards all the willing sufferers for the Lord`'s testimony!
So that I can say, it was with me as it was with Deborah, when she said,
her heart was towards the governors of Israel,
who offered themselves willingly among the people;
and then I could not but praise the Lord.
And this is the testimony that the Lord did put into my heart,
which I am moved of him to give forth,
for the comfort and satisfaction of all who desire to serve the Lord
in their generation and to keep their consciences pure,
and their garments unspotted.
And therefore Friends, keep in the first, for he is the last, and shall stand,
when all others shall fail.
Reason not with flesh and blood, but wait for the power, that it may open you;
and as you are kept open thereby,
the wonderful things of God in it will be made known unto you,
and the depths of Satan will be seen also; and there will be a growing in righteousness.
For in the power is the righteousness of God revealed
from faith to faith by which the just live;
which cannot be witnessed, where the testimony is let fall, and the light covered,
and the talent laid in the earth;
though it may be tied in a white napkin of fair profession.
For the gift or talent is neither to be hid in the earth, nor bound by any in anything,
but to have its liberty, until by its own power all be subjected unto itself,
that God may be all in us all.
This is the testimony, that I am to leave with you in these matters;
and so being eased in spirit, in the lasting love of God I remain your brother,

[.signed-section-signature]
John Burnyeat

--

My dear companion William Simpson, after he had been there,
was taken sick of a violent fever, which was very much among people at that time,
and very many died; he was sick but about six days, and then was taken away.

At his death, a very little before his departure, he gave a living,
heavenly testimony to the truth, with wholesome advice to them that were about him,
and departed in the peace and joy of the Lord:
an account whereof may be further seen in a book written by one,
who was with him from his beginning to be sick, until he departed.
I was with him very much,
but sometimes was constrained to leave him for the service sake that was upon me.
He was a very innocent man, and full of fear and reverence,
and ordinarily very open in his testimony, and very sweet and pleasant:
we walked in great love and unity together, for he was a humble man,
and had very low thoughts of himself, and always under dread.
He had gone through great sufferings, and afflictions,
and cruel persecutions for his testimony and service sake, unto which he was called.
He likewise met with hard buffetings from Satan`'s messengers, and sore temptations,
by which he had been wounded and sorely hurt,
through the wiles of Satan and his cunning stratagems;
of which he would be often speaking to me in our brotherly fellowship and communication,
wherein we would open our hearts and states one unto another.
In the remembrance of these things he was kept very low and tender, and near the Lord:
and he took great delight in his power, by which he had been redeemed,
and his soul delivered, and which was raised up into a good degree of dominion,
in which he reigned at the last, and with great triumph departed this life,
and is blessed forever.
My heart is well satisfied that it is even so: and when he was taken away from me,
my heart was broken within me,
and my spirit was bowed down greatly in the sense of my loss; and I could not but mourn,
though not as such that have no hope,
for my hope was firm concerning his well-being and gain that he had obtained.
But great was my loss, for I was left as one alone, as I had been often before,
to bear the burden myself, which was very weighty upon me at that time,
considering the state of the church in that island, and the care of it upon me:
but the Lord was with me, and his power did assist me to go through my charge,
and clear myself, and free myself from the blood of all men and women.
And all, being guided by his Spirit in his wisdom,
the Lord`'s children and people were comforted,
and my soul and spirit refreshed and revived; and in peace, clearness,
and gladness I came away, and took shipping for New England,
and set sail the first of the second month, 1671.
I arrived at New York the 27th day of the same month,
and from New York I went to Long Island, and visited Friends on the island,
and other places thereaway, and was with them at their half-year`'s meeting at Oyster Bay.

Being clear of those parts, I took shipping for Rhode Island;
and was at their Yearly meeting, in 1671,
which begins the ninth of the fourth month every year, and continues for much of a week,
and is a general meeting once a year for all Friends in New England.

After that meeting, when I was clear of those parts, I took my journey towards Sandwich,
and visited Friends all along at Tewkesbury, Marshfield, and Scituate,
and so on to Boston, where I had a meeting, and then to Salem, Hampton, and Piscataqua,
all along visiting Friends; and I had many precious meetings, and the Lord was with us,
and his power was over all.

[.offset]
+++[+++It does not appear to whom the following Epistle was addressed;
but probably from its tenor, to his suffering brethren in England.]

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
Salem, in New England, the 30th of Fourth month, 1671.

[.salutation]
Dear and well-beloved,

You whom the Lord has called to believe, and to be partakers of his divine nature,
and of his manifold mercies,
that through the strength thereof you might bear witness to his name,
and testify to his Truth in your day,
for which the God of wisdom permits you to be tried, and your faith to be proved,
as it has been his way in all ages for the proof of his people,
that their hearts might be tried,
and their love appear how weighty it is to him that has loved them;
whereby the glory of the Truth, and the excellency of it might be made manifest.

And now my friends, this is your day and hour of your trial,
wherein the Lord by you (I believe) shall be honored,
and you rewarded with that good reward,
which shall out-balance all the present sufferings,
unto which the glory of the present world is not to be compared.

And though it is my lot to be separated from you,
and so in the like kind not to suffer among you;
yet I cannot say but that I suffer with you--for my
spirit is not without a feeling of your sufferings.

O! You dear lambs of the Shepherd`'s fold, is it so, that the wolf seeks to devour,
and is the lion and devouring bear let loose, that would snatch up the lambs?
Fear not, though in his mouth.
We have a Shepherd that will deliver, and like David,
will save from the power of the destroyer,
so that your life shall not come under his power;
for God is on Israel`'s side to preserve, though they would swallow up quick.
And therefore let your trust be in the arm of his strength forever, and you shall know,
that he is able to make up all to you again.

Dearly beloved,
my very heart and soul salutes you all in that life
which by nothing that is visible can be stopped;
and in the sense and enjoyment of that I am spiritually with you, wherein I may say,
I do partake with you both of the sufferings and tribulations,
and also of the joy and consolation that abound in your souls,
as the reward of your obedience and faithfulness to the Lord,
who has called you thereunto, and raised you up for that purpose.

Let none look back, nor be dismayed, for the cause is the Lord`'s,
and he will stand by you, and will plead your cause with all that rise up against you,
and will bring your righteousness to light more and more, and show who are his,
and approved in his sight.
He will also discover and lay open the cruelty of such,
and manifest them who outwardly should show themselves to be sheep,
but are inwardly ravenous, and so ravening wolves;
and labor to lay waste the heritage of the Lord to spoil his flock.
They are such,
who would not have the lambs feed quietly in the green pasture of the Lord`'s pleasure,
nor to lie still in the fold of true rest.

But blessed be the Lord forever, he has brought many to the mountain of his holiness,
where they shall not hurt or destroy; even as he has promised.
Therefore let all mind their dwelling there, and be not moved,
and the treasure will be known, and the riches received,
which all the spoilers from Babylon, and men of war from Egypt shall not rob you of.

For it is from there they all come to spoil Zion, and to rob her of her glory.
But the Lord is her defender, and her King is in the midst of her,
and salvation is round about her for walls and bulwarks; glory, and honor, and praises,
to the Lord our God forever and ever!
For he has taken to himself his great power, and is going on conquering and to conquer;
and will effect his own purposes,
and bring to pass his own designs in despite of all his adversaries;
so that when they think to pull down, he is building up;
and in that way which they think to destroy, he will establish,
and so repair the streets of Zion in troublesome times, and build up her desolations,
and repair her breaches, as has been prophesied.
Seeing it is certainly thus, let us all trust in him, forever; and wait upon him,
that his power may be felt by us, and his love and virtue may be fed upon,
which nourishes up the soul to eternal life.

Dear Friends, the aboundings of the love of God which is in my heart towards you all,
I cannot but signify unto you,
among whom I have been a partaker of such precious mercy and rich blessings,
as we have enjoyed together,
and as I am satisfied still abound in your hearts from the God of our mercies.
This is a testimony of my love unto you all; do you receive it in particular,
as if I had written unto you all, one by one:
for this it is the Lord has made us one in his Son, and brought us into unity;
as we abide in him, there is no separation,
therefore cannot we be forgotten one by another.

By this you may understand, that I am very well every way; and going on in the service,
into which I am called.
The day before yesterday I had a meeting in Boston, but very few of the people came;
they are still under the fear of those who are like that generation,
unto whom Christ said they would neither enter in themselves, nor allow others.
However, we had a very comfortable and peaceable meeting, and Truth is over them,
and will bring them under, and confound their inventions.
From your friend and brother,

[.signed-section-signature]
John Burnyeat

--

From Piscataqua I returned back again the same way, and had blessed service;
and I came to Rhode Island again, where I spent some time,
and then went up to Providence, and visited Friends there, and so returned again.
When I was clear of those parts, I took shipping again for Long Island,
and landed at Oyster Bay, and had some meetings: I then went down to Flushing,
and so to Gravesend, and had some meetings.
From there I went over to East Jersey to visit Friends there, and had some meetings:
and I returned back again to Gravesend, and from there went again to Oyster Bay,
and was at their half-year`'s meeting,
which began about the eighth day of the eighth month, and had a blessed time.

But in our meeting for business, we had an exercise with several,
who rose up in a wrong spirit against the blessed order of the Truth,
which by the power of God Friends were gathered into, and sweetly settling in.
And chiefly their envy and bitterness were against George Fox,
and his papers of wholesome advice, which he in the love of God had sent among Friends;
and in that unruly, loose spirit and mind they were gone into,
some of them being filled with prejudice, that they had written a book,
which they brought in manuscript to the meeting, and urged to have it read.
But I told them, we had the papers there, and they might lay down their objections,
they being there, and we would answer them.
But that would not serve; but the book they would read:
and we sat in quietness till they had done.
When they had done, I reached for it, and by my memory I went over the heads thereof,
and cleared George Fox and Friends in our godly care and intents,
and opened the service and benefit of such things which they found fault with;
and I showed Friends the advantage that was therein, both to the Truth and them.

And withal I reprehended their slanders and falsehoods,
with which they had hurt the minds of several young and newly-convinced Friends;
and so opened to them,
that it was the same spirit which of old led those who opposed the apostles,
and endeavored to bring a slight,
and beget a disesteem in the minds of the believers against them,
who watched over them for their good,
and so endeavored to lead them into a fleshly liberty to shun the cross, etc.
When I had cleared myself, and informed Friends of the truth of things,
which then by them had been objected against.
Friends in general were satisfied,
and saw the mistakes which they had let into their minds,
through the insinuations of those three men,
who had been chiefly concerned in the writing of the book, and in the opposition.
The Lord`'s power broke in upon the meeting, and Friends`' hearts were broken,
and great meltings in the power there were among us;
and in the same we blessed the Lord, and praised him, and prayed unto him,
and they were bowed, and went away.
Thus Friends were comforted, and the seed and life reigned over all;--everlasting glory,
and honor,
and praise be given to him for all his mercies
and preservations for he is worthy forevermore.
When all our meetings were over, and Friends in the heavenly power and seed comforted,
and the bad spirits and their evil work confounded and brought under,
before the minds of the simple-hearted, who were likely to be hurt and betrayed by them,
and a coolness and calmness raised up among Friends, I was clear.
I then took my journey with some Friends accompanying me, and went to Flushing,
and down to Gravesend; and when I had visited Friends there, I went to New York,
and had a meeting; and then took shipping for Maryland,
setting sail the 23rd of the eighth month, 1671.

We met with a sore tempest from a west-north-west wind,
that blew so hard we could carry no sail for some days; but at last we got to Virginia,
and then sailed up the Bay,
and got to Patuxent River in Maryland the fifth day of the
ninth month and there I landed with my companion Daniel Gould,
who came with me from Rhode Island, and he travelled with me that winter.
We visited Friends in Maryland, and I went down to Virginia to visit Friends there,
and found a freshness among them; and many of them were restored,
and grown up to a degree of their former zeal and tenderness;
and I found a great openness in the country, and had several blessed meetings.
I advised them to have a men`'s-meeting,
and so to meet together to settle things in good order among them,
that they might be instrumental to the gathering of such as were yet scattered,
and stirring up of such as were cold and careless; and so keep things in order, sweet,
and well among them.

Thus having cleared myself in the love of God,
I committed them unto the Lord and to the word of his grace,
and took boat again for Maryland, and got well there at last;
but we met with strong winds and rough weather, and some danger;
and I spent some time more in Maryland, till the spring.
In the second month 1672, I appointed a meeting at West River in Maryland,
for all the Friends in the province, that I might see them together before I departed,
for I was determined to go as soon as I could after that meeting.
When the time appointed came, and Friends from all parts began to arrive,
George Fox with several brethren, came from Jamaica, and landed at Patuxent,
and from there came straight to the meeting.
There were Friends present from all parts of the province,
and we had a very large meeting, which continued for several days;
also a men`'s and women`'s meeting for the settling of things,
in order that men`'s and women`'s meetings might be established in the province,
according to the blessed order of the gospel of Christ Jesus,
into which Friends by the power thereof were gathered in most places.

George Fox did wonderfully open the service thereof to Friends,
and they with gladness of heart received advice in such necessary things,
as were then opened unto them; and all were comforted and edified.
When all was over, and we clear, and all sweet and pleasant among Friends, we departed,
and went down to the Clifts, some by water and some by land;
and there we had a large meeting of both Friends and other people.
And when that was over we departed; some went down to Virginia,
and some stayed in Maryland.

George Fox, Robert Withers, George Pattison, and I, with several Friends of the province,
took boat and went over to the eastern shore;
and there we had a meeting on the first-day,
and on the second-day we began our journey
through the woods to go over-land to New England.
We took horse at John Pitt`'s at the head of Tredaven Creek,
and went through the woods above the heads of Miles River and Wye River,
and also headed Chester River, and lay two nights in the woods, namely,
second and third-days.
On fourth-day we came to Sassafras River, and swam our horses,
and went over ourselves in boats or canoes.
We then rode on to Bohemia River, and there also caused our horses to swim,
and went over ourselves in canoes.
We then came to a plantation called Augustines, and there we stayed a little;
and about three in the afternoon, set forwards,
and some of us got to Delaware and so to Newcastle, and there got lodging;
for we were wet with the rain:
but Robert Withers and George Pattison lay in the woods all night,
their horses being tired: next morning they came to us at Newcastle.
We stayed there that day, and next day we got over the river.
When we were over, we could not get an Indian for a guide;
and the Dutchman we had hired would not go without an Indian,
so we were forced to stay there that day.
The next day he rode about to seek an Indian, but could get none to go;
but late in the evening there came some over from the other side to the town,
and we hired one: and so began our journey early next morning,
to travel through that country, which now is called New Jersey;
and we supposed that we travelled that day nearly forty miles.

In the evening we got to a few Indian wigwams, which are their houses;
we saw no man or woman, house or dwelling that day,
for there dwelt no English in that country then.

We lodged that night in an Indian wigwam, and lay upon the ground,
as the Indians themselves did: and next day we travelled through several of their towns,
and they were kind to us, and helped us over the creeks with their canoes;
we made our horses swim at the sides of the canoes, and so travelled on.
Towards evening we got to an Indian town; and when we had put our horses to grass,
we went up to the Indian king`'s house, who received us kindly,
and showed us very civil respect.
But, alas! He was so poorly provided, having got so little that day,
that most of us could neither get to eat nor drink in his wigwam; but it was,
because he had it not.
So we lay, as well as he, upon the ground; only a mat under us, and a piece of wood,
or any such thing under our heads.
Next morning early we took horse, and travelled through several Indian towns;
and that night we lodged in the woods.
And the next day, being the fourth-day, we got to an English plantation,
to a town called Middletown, in East Jersey, where there was a plantation of English,
and several Friends; and we came down with a Friend to his house near the water-side,
and he carried us over in his boat, and our horses also to Long Island.
We got to Friends at Gravesend that evening;
and next day we took our journey to Flushing on Long Island.
On the seventh-day of the week, we took our journey to Oyster Bay,
and came there that evening;
and several Friends from Gravesend and Flushing were with us,
for the next day their half year`'s meeting did begin,
which was the cause of our hard traveling.

We understood, that those who had been so troublesome at the half-year`'s meeting before,
when I was there, in opposing the order of truth, and reflecting so upon George Fox,
would then be an exercise to Friends;
therefore George Fox did endeavor the more to get to the meeting,
which we did very seasonably.

It was of great service to the truth, and great comfort to Friends;
for they of that party were greatly under, when we were come,
and some of the chief of them began to fawn upon George Fox.
So we had our meetings very comfortably; first and second-days were public for worship;
third-day our men`'s and women`'s meetings for business, about the affairs of the church,
as usually before.
On the fourth-day, we had a meeting with those dissatisfied people;
for George Fox would not allow the service of our men`'s
and women`'s meetings to be hindered by such a matter:
and so on the fourth-day, as many Friends as had a desire to be there, did come;
and the Lord`'s power went over them, and Friends were much satisfied.

He that was the chief instigator of that mischief, namely, George Dennis,
who came from London, and his wife, not being well owned there by Friends,
now began to disown the matter, and would have cast it upon others,
and willingly appeared clear to George Fox; but that I proved under his own hand,
that he was a chief actor at the half-year`'s meeting before,
and the one who read the book in our meeting, whether we would or no.
So things being fastened upon him, the Lord`'s power went over his deceitful spirit;
and they were all bowed, and the truth was exalted over all; glory to the Lord forever.
Amen.

After this we stayed a little upon the island, and went back to have some meetings,
and returned again to Oyster Bay;
and from there set sail for Rhode Island the twenty-ninth of the third month, 1672,
and arrived the thirtieth of the same, and there stayed till the yearly meeting,
which began the eighth day of the fourth month,
which was the sixth-day of the next week following.
At that general meeting there were many Friends from most places in New England,
where Friends dwelt, and abundance of other people came into our public meetings.
We had meetings for eight days together, every day a meeting,
some public and others men`'s and women`'s meetings,
for settling the affairs of the churches in the order of the truth;
that all things might be kept sweet, clean, and well.
When all was over, and the service of the meetings finished, I took my journey eastward,
to go through the meetings in the eastern parts of New England,
and with me went John Cartwright and George Pattison,
and several other Friends accompanied us: we left George Fox upon the island,
and we went to Providence and the Narraganset country.

So we took our journey towards Sandwich, where we had a blessed meeting,
and were comforted and richly refreshed in the blessed
presence of the Lord`'s holy and blessed power,
which was with us, and which opened and enlarged our hearts.
When we had spent some time with Friends there, we left them,
and travelled on by Plymouth and Duxbury, and had a meeting at Marshfield,
and another at Scituate; and the Lord was blessedly with us.

At Scituate some of the elders of their church came to our meeting,
where were abundance of people in an orchard, and stood up and made opposition;
so I ceased speaking to the people, and joined with them in dispute.
But the people were so displeased at the interruption they made,
that they signified their dislike, and would have them stay till I had done; upon which,
they said they would forbear and come again.
They went away; and after their own meeting was over, they came again,
and several Friends stayed with me, and a great company of people came with them.
Then we went into our meeting-house, which before would not hold the multitude,
and there began to dispute; and after some time spent,
they always endeavoring to make Friends appear to be in the error, I said to them,
before the people, "`If I must be disputed with as a heretic,
and your church esteemed as a true church,
I am willing we should come to the rule Christ has left, and thereby be tried,
and that is, by our fruits:
and if you can prove the fruits of your church to be agreeable
to the fruits of any ancient true Christian church,
I shall yield; otherwise I must hold my testimony against it as a false church,`" etc.
But they were mighty unwilling to join with me in that discourse.
I urged the proof of our practice by Scripture, especially in such a great point as that;
and so went on to reckon up the fruits of their church, which were,
to fine and take away goods for not coming to their worship, to imprison,
to whip with cruelty, to cut off ears, to burn in the hand, to banish upon pain of death,
and to hang; for they had hanged four of our Friends.
All which cruelties their church had executed upon us,
and only upon the account of religion.
And if they could prove these to be the fruits of a true Christian church,
then I told them I would own them, otherwise they were to be denied.

The proof of these things, or to dispute upon them, they would willingly have evaded;
but I stood upon its being necessary, that we might be known by our fruits,
and our practice proved by Scripture, which they pretended to be their rule:
or otherwise all was but vain words, and an idle notion,
and had nothing to do with Scripture, etc.
Then they were confounded, and knew not what to say;
but one of them fled to that decree made by Artaxerxes. Ezra 7:26.
But I showed, how inconsistent it was with the gospel dispensation,
Christ`'s command, and the Christian`'s practice: and further said,
I would prove the Indians better Christians than they, by practice.
I instanced the Indian king, who, when they had banished Nicholas Upshall (an ancient,
grave man, against whom they had nothing,
but that he was called a Quaker) from his wife and family, and out of their colony,
he being received by his Friends at Sandwich in Plymouth colony,
they stirred up the rulers of the colony to banish him out of their jurisdiction,
which they did:
and when the Indian king had inquired why they would send that ancient man
sixty miles through the woods in the cold winter to Rhode Island?--and
understood the matter, he desired him to go with him, and he would keep him,
and none should molest him, or to that purpose; and offered him land and kindness.
So, said I, here was one that would entertain a stranger, a Christian practice,
according to Heb. 13:2,
when your church banished neighbors from their own dwellings,--an act of cruelty, etc.

Much discourse we had, but at these things they were confounded;
some of themselves having been actors in persecution upon our Friends,
as Friends told me, after they were gone.
So the Lord`'s power went over them, they could not stand the trial;
and we parted in the peace and love of God.

Next day we came to Boston, where we had a meeting, and many people came in,
and several of note.
After a while, when I was speaking, came the marshal and a constable,
and many people followed them.
The marshal bid the constable do his office, the constable being a moderate man,
said so he did; he was to see the king`'s peace kept.
He stood awhile, and heard me; and went away, and told the deputy-governor,
he had been at our meeting, but he heard nothing but what was true, and no blasphemy,
or to this effect.
So the people stayed, and I had a blessed season to open things to them,
and clear the Truth of those scandals, which the priests and others had cast upon it;
and the people went away greatly satisfied,
and spoke well of the testimony they had heard.
When priest Thatcher heard this,
(for several of his children were there,) it appears he was displeased; and the angry,
persecuting spirit got up in him,
and next first-day he stirred up two magistrates in his preaching to the people,
and they sent and took Friends at their meeting, and committed several to prison.

We had appointed a meeting for John Stubbs and
James Lancaster the third-day of the next week,
who came after us through the country: and when they came, they were put in prison,
and banished out of the colony.
Thus their old fruits, like old corrupt trees, were brought forth again.

The next day we took our journey to Salem, and there had a meeting, and a blessed season;
but we met with some, who were gone into that foolish notion of John Ferret`'s,
keeping on their hats when Friends prayed, etc.
After meeting was over,
(where many people were in a barn,) we had a
meeting with several of the chief of Friends,
and such as were gone after that spirit; and a great discourse we had with them,
in which we labored to bring them to an understanding of that notion they were gone into,
and so labored to open and settle the minds of
Friends in the ancient Truth and blessed power,
which they had believed in, and received from Heaven;
and then appointed a meeting to be held the next week against our return.
We took our journey towards Piscataqua, and had a meeting at Hampton, as we went;
where several people came in, also some of the elders of their church,
and they were greatly satisfied; and they went away and gave a good report of the Truth,
insomuch that Seaborn Cotton, the priest, was greatly offended.

The first-day following, he called the chief of his people together,
and would have a church act made, that no members, or member`'s children,
should go to a Quaker`'s meeting;
and it was to be confirmed by their holding up their hands:
but those that were at the meeting, would not assent;
but one of them declared what he remembered of the heads of what he heard at the meeting,
and maintained it to be truth.
The priest was in a rage, and endeavored to stir up persecution.

After the meeting was over, we went along to Piscataqua,
with Friends who came from there to meet us; and stayed there till the first-day,
and had a blessed meeting, and also had a meeting with the chief of Friends,
both men and women, about settling men`'s and women`'s meetings.
Friends were very open, and all things were settled in sweet unity,
after we had opened things unto them, relating to the blessed order of the gospel.
So committing them to the Lord and the word of his grace, we returned back again,
and had another meeting at Hampton, where were several young people,
who after the meeting gave me a paper,
in which they signified their desire to be satisfied in
something that was as a scruple upon their minds:
to which I answered, and gave them great satisfaction.
When they saw my openness and willingness to answer, they asked me about several things,
wherein they desired to be informed, and to all I answered, and gave them satisfaction,
and so we parted.

Then I and Friends with me, took our journey towards Salem,
and came there against the time appointed; and we had the meeting which we had appointed,
with most of the chief of Friends;
it was about settling meetings to look after the affairs of the Church.
In this meeting it was upon me largely to open
the service of our men`'s and women`'s meetings,
and the duty and care of the faithful therein; and when I had done,
they confessed the service, etc. to be very good and right.
We desired, that they would come into the practice thereof;
but when we partly pressed it, they would answer little, but held back; some of them,
(like Diotrephes of old, who loved to have the pre-eminence,
and so withstood the apostle,) did keep off in their minds,
being of that spirit I wrote of before in Virginia, pretending to be against forms.
For a while we sat waiting upon the Lord, and staying to see what they would come to;
and George Pattison labored to bring them to a sense of the service,
in order that they might come into the practice,
and they not being willing to say anything, my spirit being very low,
the word of the Lord came unto me, and the dread of his power fell upon me.
After some time I opened my mouth with a lamentation, and said, --I was sorry,
or grieved, that I had that to say, which I must declare unto them, and that was,
that while they stood in that spirit they were in,
they could not act in unity with the body, and in honor to the Head, etc.,
and therefore our exhortation to them was to condemn that spirit,
by which they had been led aside, and to wait for the universal Spirit of life,
or to this effect; and so we left them, and they were greatly concerned.
The next day we had a public meeting among them,
and after meeting we came away towards Boston.
Then their consciences being troubled, we had to do with several of the chief of them,
who labored to have that reversed which I had spoken; and said, it was very hard, etc.

But I told them, I could not do it, the power had sealed it, and it must stand;
which was, that they must come to repentance, and condemn that spirit which had deceived,
or to that effect.
So we left it upon them according to the word of the Lord;
some of them have since seen it, and condemned that spirit,
and given a testimony in writing against it;--blessed be the Lord, who shows mercy,
and restores out of the snares of Satan.
