== Chapter V.

[.chapter-synopsis]
* The author travels with John Stubbs
* At Rhode Island, attends a long public dispute, and again at Hartford
* His other services
* In 1673, lands in Ireland
* Visits most of the meetings in that country: returns to England, visits Westmoreland Quarterly meeting
* Case of John Wilkinson and John Story, 1675
* Travels into other parts
* Troubles respecting John Wilkinson and John Story.

Being clear of all those parts of the country, we came away strait to Rhode Island,
and there we met with George Fox who was preparing to go westward towards Long Island;
so he went away, and Robert Withers, James Lancaster, and George Pattison with him.

From Long Island they went over to East Jersey, and so over land back again to Maryland;
and John Stubbs and I were left at Rhode Island: John Cartwright we left at Piscataqua;
he went further eastward,
and after sometime he came to John Stubbs and me at Rhode Island.
John Stubbs and I went up to Providence, had a meeting there; and as we returned,
we had a meeting at Warwick, where none had been before: and several were convinced,
and did own the truth.
And there we had to do with one Gorton and his company,
who were by other people there called Gortonians, but they called themselves Generalists;
they were of opinion all should be saved.
But they were in reality Ranters: for in our discourse they would maintain and say,
no creaturely actions could be sin, and would have no drunkenness, nor the like,
to be sin, but what was spiritual; the outward action was but creaturely.
Thus in their filthy, unclean spirits, like the old Ranters,
they made merry over the reproof of God`'s Spirit.

From there we came down again to Rhode Island; and there we spent some time,
and had a long dispute with one Roger Williams, who sent us a challenge from Providence,
with fourteen propositions, as he called them, but they were charges;
and he engaged to maintain them against all comers; the first seven to be disputed on,
at Rhode Island, and the latter seven, at Providence.
We spent three days in dispute with him at Rhode Island;
but he could not make any proof of his charges to the satisfaction of the auditory;
for there was a great congregation every day:
it would be tedious here to insert the discourse, if I were able;
but I cannot remember it.
There is a book in manuscript,
of what was taken in short-hand of the discourse at that time;
besides there is a book in print, entitled "`New England Firebrand Quenched,`" etc.,
which is an answer to a book of the said Roger Williams,
which gives a relation of some part of the dispute, to which I refer the reader.
William Edmundson came from Virginia, and was also with us at the same dispute;
William Edmundson and John Stubbs went up to Providence,
and spent one day with Williams there, about the latter seven charges,
and so cleared themselves to the people, and came away when they had done with him.

After being some time together upon the island, John Stubbs and I went over,
with several Friends that accompanied us, to Narraganset;
and there we had a meeting the four-and-twentieth of the sixth month,
at one Richard Smith`'s, and next day took our journey towards Hartford.
We came first to New London, and from there to Norwich, and so to Hartford,
and stayed there one day; and several of the professors came to us, to dispute with us.
The next day we rode nearly thirty miles to a town called Westfield,
which was within the Massachusetts colony: a man and his wife received us;
and we appointed a meeting.

But when they heard of it, some of their officers came to us,
and commanded that we should have no meeting; and so affrighted the people,
that none dared come to us.
We had a little discourse with their officers or elders who came to us;
but they would not stay, but cried out against our religion.
We asked them if they knew our principles, which they so condemned?
Some of them answered, and said, no, they knew them not, nor did they desire to know them.
We asked them, how then they could judge of them;
and withal we told the men they were such as the Scriptures did speak of,
who spoke evil of the things they knew not; and they were confounded, and went away;
but they so scared the people, that none dared come near us.

So we came away to Hartford again on the sixth-day of the week,
and on the seventh-day several came to us, and discoursed with us:
and we desired that we might speak with the priest,
and they had promised that we should but when we desired him to come,
he (or they for him,) made an excuse, that he could not that day come from his study.
The next day being the first-day of the week we went to their meeting,
and the forenoon stayed without, till they had done.
And when they had done, and came forth, we spoke to the people; but they got away,
as if they had been afraid of us; and none would stay.
So we returned to the inn, and stayed there till the afternoon;
and then we went into their meeting-house, and stayed till the priest had done.
Then I stood up, and called unto the people, and desired their patience a little to hear,
for I had a word of exhortation to them; and so began to speak.

But immediately the sexton came to me to interrupt me; and seeing he could not stop me,
he drove the people away.
When I saw most of the people gone, I stepped down,
and thought to have gone forth after them; but he got to the door,
and shut the door to keep me in.
Then I went round an alley to get to a second door,
but he got over the seats and shut that.
Then I made for a third door, he also got to that before me, and shut that,
and so made their meeting-house a prison, and kept us in,
with a very few people who got not away, till the people were gone,
and then let us forth; so we came to our inn again.

After some time several of their elders came to dispute with us,
on purpose to keep the younger people away, as some of them confessed;
and when we came to discourse with them,
they would seem to charge us with breach of the sabbath,
in coming to their meeting that day.
We took to the Bible and said, "`Come,
first prove a sabbath-day under the gospel dispensation,
and then prove our practice this day to be a breach of it, if you can;
and vindicate Paul, who disputed every sabbath-day in the synagogue,
etc. and then prove by Scripture your practice this day,
and show where any Christians drove the people away from hearing the truth,
(for they had granted, we spoke nothing but truth,)
and made their meeting-house a prison?
So we shut them behind the unbelieving Jews, who gave liberty to Paul and Silas:
and they were confounded, and could not tell how to vindicate their doings,
and went away.
Alter they were gone, many younger people came into our chamber,
and we opened many things to them relating to the way of truth,
and cleared up things from the Scriptures; and they were mightily satisfied.

When the old, dry professors saw that the younger people were affected;
they sent in a constable, to command all to depart; but they answered and said,
they were housekeepers many of them, and therefore he had nothing to do with them:
so they would not go.
So we continued still opening the Scriptures unto them; and they were affected.
The innkeeper, being one of their elders, came and took the candle away,
that we might not see to read in the Scriptures; and so left us in the dark:
then the people went away, being displeased.

The next morning, John Stubbs and I took our journey westward;
and our friends that had accompanied us, returned home to Rhode Island.
We went from Hartford to Newhaven, Milford, Stratford, Fairfield, Norwich, Stamford,
and so to Greenwich, where we met with Friends; and there we appointed a meeting.

The priest of that town in his pulpit had preached against Friends,
and often had boasted, how he would dispute with the Quakers, if any came there;
so when the meeting was appointed,
the people came with great expectation of what a priest would do.
But in the morning he rode away to Stamford to a magistrate,
and sent a constable with a warrant to apprehend us;
who came at the beginning of our meeting,
and took us and carried us away to the magistrate at Stamford.
The people being displeased, many of them followed after us to Stamford,
and our friends also, to see what they would do.
When we came there, many people were gathered about the house,
for it was but two miles between the towns;
but after a little time we were called into an inner room,
where the magistrate lay upon his bed, he not being very well.
When we came in, there were none with him but two priests, the priest of Greenwich,
and the priest of Stamford, and none were to be permitted to come in but the constable,
and one man of Stamford who was a merchant, as they said;
he went in and out when he pleased.
The magistrate asked us many questions, and we answered him;
and he discoursed with us long in many things, and we answered him;
for he was very moderate.

After a long time one of the priests put in a question; and I said,
if we must discourse of divine things, we did desire to be more public;
for the people were without, desirous to hear.
Then the magistrate said to the priests, "`Master Jones and Master Bishop,
I desire you to go into the public meeting-house with these men,
and there discourse with them before the people; for,`" said he, "`they are sober,
rational men.`"
So we accepted kindly of the proffer, and rose up, and went forth;
and the priests came after us displeased.
But when we were forth of the door among the people,
we called upon the priests to go with us, as they were desired; and so we went up,
and they and the people also.
When we were settled in the meeting-house, with many people,
the priests put it upon us to begin; and so we began with them first about their wages,
and then went on to our call, which they put upon us; and then about the light,
which they denied: also about the election and reprobation, and free grace.

They affirmed the grace of God had not appeared to all men,
and that Christ did not die for all men.
Several hours we spent; but the discourse is drawn up in a book in manuscript,
and therefore I shall forbear it here, for it is large.
The next day we had a meeting at Greenwich, but the priest came,
and we had a great discourse; which is in the said book.
On the first-day following we had a meeting about six miles from there; then,
being clear of these parts, we took boat and went over to Long Island, to Oyster-Bay,
and met with John Cartwright; and so visited Friends upon the Island.
John Cartwright and I went over to East Jersey, and visited Friends there,
arid had several blessed meetings; we returned back again to Long Island,
and had several meetings.
Being clear of those parts, John Cartwright and I came to New York,
in order to get a passage for Maryland;
we set sail from New York the first day of the ninth month 1672,
and from Sandy Hook out to the sea the third-day of the same, and met with rough weather;
but the sixth-day of the same we got in at the Capes of Virginia,
and on the ninth of the same month we came to anchor in
Patuxent River in the province of Maryland,
and so got up within a day or two to James Preston`'s;
for the north-west wind blew so hard, that we could not get up the first-day.

We then went among Friends in that province as the Lord made way.
George Fox and Friends that were with him, who came over land together,
were gone down to Virginia, and he also travelled over land to North Carolina,
and there found some Friends, and returned over land to Virginia,
and came up the bay again to Maryland;
and while they were below in Virginia and Carolina,
we travelled among Friends in Maryland, and had blessed service.

Upon the first-day of the eleventh month we had
a meeting at John Baldwin`'s at South-River;
where were many Friends, and other people,
who came together upon the occasion of a dispute
to which one Henry Pierpoint had challenged us,
who was a kind of fifth-monarchy man.
The first thing to prove, which he had assumed, was,
that the Scriptures were the only rule to try
all things by in matters of faith and doctrine;
about which we had a great discourse: and we proved,
that the patriarchs had faith and a rule for faith,
before any Scriptures which we have were written; and we showed what was their rule.
We spent several hours in dispute about the other three things, which he had affirmed;
but there is a book in manuscript, which is an answer to them all:
I therefore shall omit any further mentioning of it here.
Some time was spent in visiting Friends from meeting to meeting,
to which many people came at several places; and the Lord`'s power opened us,
and we were comforted, and the consciences of the people reached.
George Fox and the other Friends then returned,
and John Cartwright took shipping for Barbados.

George Fox and I were some time together; and we were up at an Indian town,
at the emperor`'s house, who had ordered the Indians, both men and women,
to be at his house, that is, all the ancient and grave;
and the young people were at another wigwam.
George Fox spoke to them by an interpreter for the space of four or five hours,
I suppose it was nigh five hours; and they were very still and quiet, and very attentive,
and delighted (as we did perceive) to hear.
When the time was over, and we clear, they showed us kindness,
and were going to hang a kettle on the fire to boil fish for us to eat, as they told us;
but we could not stay, having a great way to go by water, and it was late;
so we came away to the water-side, and some of them accompanied us till we took boat.

We came down the river again to Friends,
and spent some time more in travel and labor in that province.
James Lancaster, George Pattison, and I,
took a journey to visit some people that were convinced, up Potomac river;
we ferried over Patuxent river, and then travelled through the woods on foot,
till we came to them; we stayed a few days, and had a meeting or two,
and then returned back again to Patuxent, and to the Cliffs, where we left James,
being very weary.
Next day George and I travelled to West river, and were at their meeting:
and next week we got a boat, and went over the bay to the eastern shore,
and went up Miles River to Friends;
and from there we went to meet with George Fox to speak with him,
having some intentions to take shipping, and go for England with one John Ore a Friend,
a master of a ketch, which belonged to some Friends at London.

When we had been with George Fox a little time, we returned to Miles River to our boat;
and after a time we went over the bay towards West River,
and through some exercise with contrary winds, at last we got over;
and after a little time spent there with Friends, we departed,
and went down by the Clifts, where we met with George Fox come over the bay.
We stayed but little there, and went on towards Patuxent; where we took shipping,
and set sail the twenty-fifth day of the second month, 1673,
and came out at the Capes of Virginia to the sea
on the twenty-sixth day of the same month.
When we had sailed but a few days,
in a morning early we espied a fleet of ships behind us, about four-and-twenty;
then we stopped a little, supposing them to be an English fleet,
which sailed out of the Capes from James River, two or three days before us;
and when some of them came up to us, they told us, it was the same fleet.
So we stayed, and went in company with them,
till we came about the Banks of Newfoundland: and then we met with foul weather,
which parted us one from another, so that we no more got altogether again.
We were six that got together again in our company, and kept together,
until we came into the bay at Galway in Ireland,
where we arrived the twenty-fourth day of the third month 1673.
