== Chapter VII.

[.chapter-synopsis]
* An abstract of some of John Burnyeat`'s letters to his brother, T. A., of London, in continuation of his travels for the last eight years of his life, being all in his own hand-writing.

Dublin, the twenty-eighth of the eighth month,
1682.--I am arrived here safely from Cumberland,
and was at all those meetings I had appointed in Westmoreland.
I had a large meeting at Camsgill on the third-day of the week,
it being the general meeting; it was a most pleasant day,
the meeting out of doors very large, Friends so generally came in.
And indeed the Lord`'s power was with us; and my heart was greatly enlarged unto Friends.
The fourth-day following I was at Sedberg;
the meeting was without doors by the meetinghouse,
the doors being shut up by the officers, it was quiet and large.
The fifth-day I was at Grayrigg; sixth-day at the Height; first-day at Swarthmore;
and on the third-day at Hawkshead, and had a blessed meeting; my heart was comforted.
The fourth-day we had a great flood, which hindered me from getting home that day;
but I got to Keswick in Cumberland; and fifth-day got home to our meeting at Pardsay,
and was also there the first-day,
where the Lord enlarged my heart to clear myself heartily that day.
The third-day I was at the men`'s meeting, where the Lord was richly with us;
everlasting glory be to Him forever!
The fourth-day early I came down to Whitehaven; several Friends came with me,
but the ship being ready I could not stay.
So I went on board, and the next day in the evening arrived safely here at Dublin;
where all is well.

Dublin, the thirteenth of the ninth month,
1682.--It greatly pleases me to hear of Friends in England,
and how it is with them in this trying day.
For as we love the Truth, and one another therein,
we have a concern upon us for one another, and for the Truth in general:
and therefore I delight in the Truth`'s prevailing, and in Friends`' prospering therein.
The Lord stir up all concerned in their places, to be faithful,
that none may shrink in the day of trial, etc.

Last week was our half-year`'s meeting; many Friends were here,
and a blessed season we had, through the enriching virtue of the Lord`'s power;
and in love, peace, and concord, all was carried on among us:
and so all was sweet and comfortable.
There is a discourse of putting the laws in execution against Dissenters; however,
if the Lord permit such a thing to be, I believe,
it will be for his own glory at last--in manifesting the approved,
and trying the faith of his people.
But we are yet quiet, save some that are in prison for tithes.
Our meetings are large and full in this nation, and Friends tell me,
there is an openness in many places.
O!--that we may be found faithful,
that we may work with him in his vineyard and harvest.

Dublin, the sixth of the tenth month, 1682.
--The Lord preserve us all in the faith which gives the victory,
and faithful to God in this trying day; wherein it appears,
that the Lord sees it fit to try his people, both in their faith and patience,
that the approved may be made manifest.
We have large meetings in this city, and an openness in several places in the country.
I have been in the counties of Wicklow and Carlow, and the Queen`'s county,
and at the Moate, and Edenderry: and tomorrow I intend, if the Lord will,
to go forth again to the province meeting at Rosenallis.

[.small-break]
'''

[.emphasized.centered]
The following living Epistle is without a specific address.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Cork, the 25th of the Tenth month, 1682.

[.salutation]
Dear Friends,

In the everlasting covenant of life and peace,
and in the pure spring of divine love do I remember you, and very dearly salute you all,
who in the faith that gives the victory, remain and stand steadfast.

Keep your habitations and dwellings in the heavenly places,
in Christ Jesus your redeemer,
who has redeemed you out of the wickedness that is in the world, unto himself,
and so into his own power and nature, which is righteous;
that you might become the righteousness of God in him, and be restored into the image,
nature and state, in which man was created,
by him that made all things good and man in his own image, that he might delight in man,
and that man might honor and glorify him.
Now this work of restoration, you know,
God has sent his Son to effect and accomplish in man, and for man,
that again man might honor his Creator, and become the delight of his maker,
whose delight is to dwell in the habitable parts of the earth,
even among the sons of man.

Therefore, that you may be his delight, and that he may take pleasure in you,
keep in that which has renewed, or does renew and change the heart and spirit,
that in the newness thereof you may serve, and honor, and glorify him,
from whom the renewing power and word does come, that so the new creation,
the new heavens and earth may be known, wherein righteousness dwells;
and that you may have your citizenship there,
and shine as lights among this crooked and perverse generation,
in whose heaven and earth unrighteousness does dwell.
And, as the apostle said, the Lord will not only shake the earth, but the heavens, also,
that that which cannot be shaken, may remain.
I believe, that the heavens of many will be shaken, before this searching, winnowing,
trying day be over, that is growing upon the nations and people;
for the heavens of many are covered with darkness and thick clouds,
and the glory thereof is gone, and the brightness and steadfastness thereof is lost;
not a star to be seen, except a wanderer out of its course, out of the covenant,
that has greatly lost its light,
and so in the clouds of darkness driven to and fro by the variable, uncertain winds,
that are, and may be allowed to blow, to shake that which is shakeable,
and remove that which will not endure, that that which cannot be shaken may remain,
and the glory of that may appear which will endure.

Dear Friends, God has manifested that which is sure forever, and will stand,
and you have known the power of it; and as you keep in the holy sense thereof,
you will be steadfast, constant and firm in your minds, and not soon shaken,
nor removed from your habitation and steadfastness in
the gospel of Christ Jesus our Lord,
which is the power of God, which is above all powers, thrones and dominions,
and will stand, and cannot be shaken.
For the gospel power and kingdom, is above John`'s ministration,
and he that is least there, is greater than John;
and is come to that which is surer than a reed, that may be shaken with the wind;
though it be not broken, yet it may be shaken.
They that would dwell there, and not come on to Christ the Rock, that cannot be shaken,
their dwelling is not safe, their habitation will be thrown down,
and their houses made a desolation.
Methinks I see it so in our days,
upon such that have sat down short of the eternal substance that ended all shadows,
John`'s, as well as those that were before him.

Therefore, dearly beloved, you that have known the eternal substance,
the living power of the Lord Jesus Christ manifested in your hearts,
by which you have been quickened, raised up, and made alive unto God,
keep to the power in your souls, and mind its living in you,
that you therein may live unto God, and so abide a living people through your age,
God`'s living witnesses in your day, without alteration;
and be such as have not only been hearers of the word, but doers also;
whose house is built upon the rock Christ Jesus,
which by the storms and winds cannot be thrown down.
For the sure foundation being kept to, you will endure,
and the Lord will bless you with peace in your souls, and true pleasure in your hearts,
and you will enjoy the true riches and heavenly treasure, and learn,
as you keep to the power of God in your hearts, to lay up this true treasure in heaven,
through the true faith, where the thief cannot come to steal,
nor the moth to waste or corrupt.
Your riches and treasures, that you trust and delight in, being thus laid up in safety,
your hearts will be quiet, and settled in the kingdom, in heaven, where the treasure is;
and then Christ`'s words will be witnessed; where the treasure is,
there will the heart be also.

Oh, my dear Friends,
how true are these things! Happy are they that grow up into the experience thereof,
through the operation and openings of the heavenly power in their hearts;
such are kept free from that which would entangle, and their feet at liberty,
that they may run cheerfully the race that is set before them.

For the riches, the prize that their hearts are upon, being before them,
and the mark also that they look at, this draws them to press forward;
so that they are not of them that draw back to perdition.
And thus Friends, you may see where, and in what,
your profitable exercise is through your day, and where the lasting gain,
riches and treasure are to be got, that will endure, and be your portion,
when the enemy and all his instruments have done what they can.
This made David say, he would not fear what man could do unto him,
for the Lord was his Shepherd, and the Lord was the portion of his cup,
and the lot of his inheritance.

Therefore keep your hearts out of the world, and the riches thereof, which are uncertain;
and also above delighting in the glory thereof; and let your delight be in the Lord,
and in the sweet and pleasant enjoyment of his righteous,
peaceable power all the day long, that you may still feel a habitation therein,
and a place of safety to flee unto in every needful time.
Wait upon its holy springings in your hearts,
that your souls being thereby united unto God, you may dwell in his covenant,
and so in unity with him and his blessed Son, and feel the fellowship,
which is a mystery, held in a pure conscience.

And dearly beloved, live at peace among yourselves,
and wait for the spirit of love and concord to spring in all your souls,
that the true mark of Christ`'s disciples may appear among you.
Remember what he said unto his of old;
By this shall all men know that you are my disciples, if you love one another;
and what the apostle said, He that dwells in God dwells in love.
I entreat you, wait for the power of it in your hearts,
that you may therein serve one another, and the whole body may be edified,
the weak strengthened, the fainthearted encouraged,
and the lame not turned out of the way, but all helped forward on their way.

And all being thus in the righteous holy power, exercised for good,
which it will lead you unto, will be a strength and comfort,
and crown of rejoicing one to another,
and helpers forward of one another`'s joy in the Lord.
Surely this is needful in this day, wherein Zion has so many enemies;
she had need to be as a city that is at peace within herself.
So the God of peace keep you all in the dominion of his life,
that therein you may reign over every hurtful thing,
and dwell in the holy mount of safety, where the destroyer cannot come;
upon the holy hill of Zion,
around which he has appointed salvation for walls and bulwarks;
that you may all witness peace to be within her walls, and prosperity within her palaces.
And so every day high praises may be in your hearts and mouths unto her King,
who is King of kings, and reigns over all, who only has immortality,
and dwells in the light: to whom be glory and eternal praises, says my soul forevermore.
Amen.

[.signed-section-closing]
From your friend, and one that truly loves you in the Truth.

[.signed-section-signature]
John Burnyeat

--

[.embedded-content-document.epistle]
--

[.letter-heading]
Letter to Friends in Prison

[.signed-section-context-open]
Castle Salem, in the west of Ireland, the 30th of the Tenth month, 1682.

[.salutation]
Dear R. S.,

Unto you with your dear wife, C. H., R. V., and theirs,
with the rest of Friends there in prison with you,
does the living sincere love of my heart truly reach and livingly flow forth;
for I can say of a truth, that you are often near my soul, and livingly in my heart,
and that in my nearest approach unto the Lord, when my life opens,
and my spirit is let forth through the power thereof, and poured forth into his bosom,
(as blessed be his name,
he gives us access by his own Spirit) even then are you
many times fresh in my heart and livingly before me,
as if I were present in body with you;
and with great delight do I put up my supplications upon your account,
unto the Lord our God, rejoicing to feel the Lord so concerned for you,
that by his own Spirit he so often stirs up a remembrance of you in my soul,
and that upon such holy occasions.
Oh! Blessed be his name, he is the keeper of Israel, that neither slumbers nor sleeps,
but remembers his people, and his eye is open to see their afflictions,
and his ear is open to hear their complaints and tender groanings;
and no doubt but he will arise in his own due time, to work deliverance and salvation,
and they shall glorify him.
Oh! My dear Friends,
how is my soul overcome in the weighty love of God at this time unto you all, who suffer,
or are given up to suffer,
and value your testimony above all things for his name`'s sake that has loved you;
and so are of that number, that love not your lives unto death,
but are given up to follow the Lamb, wheresoever he goes.
My heart is affected with you in your testimony, and can say, as Deborah of old,
my heart is towards you, who offer yourselves willingly among the people,
now to suffer in the Lamb`'s battle (as they did to war in the outward
war) for that is the way the Lamb and his followers do overcome;
he was made perfect through suffering: and the promise still is,
the Lamb shall have the victory everlasting glory,
and honor and praise to the living God that sits upon the throne, and to the Lamb,
who is worthy forever more.

Therefore dear Friends, look not out, look not back;
but to the Lord your rock and strength look for help and for deliverance; for you know,
that it is from him that salvation comes,
and not from the hills and mountains for he is the God of the whole earth,
and the mountains shall melt at his presence, and before him shall the hills flee,
yes the sea also shall flee, and Jordan shall be driven back,
that his ransomed may pass on, his redeemed people may enter into their rest.
Oh! Therefore, let us cleave unto the Lord our Savior, and so follow Christ our redeemer,
who can cut a passage through the great deep; let us not be dismayed at anything,
that may rise up in our way to oppose us, so long as our Leader is with us,
and our blessed Rock attends us, and we feel our dwelling within the munition thereof,
our bread will be sure, and our water will not fail, and our hearts will not be barren,
our souls will not be faint; but we shall grow through the blessings of Israel`'s God,
and live,
when with all their cunning the enemies of the Truth have contrived our overthrow.
For there is nothing can hurt us more in the trying day,
than lack of faith in God`'s power and arm of strength,
which never failed them that put their trust therein.
And therefore, my dearly beloved, with whom my soul is bound up in the covenant of life,
wherein I have unity with you, and can say, although you bear the burden,
yet my heart is concerned for you, and also with you in your godly concern and testimony,
for which you suffer; and therefore cannot you be forgotten by me.
For as we love the Truth, and the holy testimony thereof,
for which you suffer and are in bonds, in spirit we are often as bound with you,
and fellow-feelers of your burdens.
And furthermore, we cannot propose to ourselves any other,
than before long to be sharers with you, to be partakers of the like sufferings,
trials and exercises; and therefore still it is our safety to be prepared in our hearts,
and into the will of God to be given up to do or suffer for his name`'s sake.

For our days do seem to be like the days of old, wherein the apostle said,
they were killed all the day long, and accounted as sheep for the slaughter.
If we look into the Scriptures, we have a cloud of witnesses;
and so through what was written aforetime, which was written for our learning,
we may have comfort, and our hope strengthened,
and so be encouraged to trust in the Lord our strength, and in whom our hope is.
And now it is still to be our care, as lambs or sheep, to live in innocency,
and so as lambs to suffer for our innocency, and for our testimony,
which we are called unto; and surely, I often consider,
what more innocent practice can we ever be found in, than in our peaceable meetings,
to wait upon the living God and to worship him, in his peaceable spirit,
by which our hearts come to be cleansed of all evil,
and our spirits gathered into the peace and love of God, in which we love God again;
and not only so, but have our hearts filled with love and goodwill towards all men,
in the peace and sweetness of which, we are enabled to pray for the good of all,
even our enemies.
And if this must be misinterpreted,
and our righteous and godly intentions counted a transgression of the law,
and a breach of the peace, I do not know what such who so do, can call innocency.
Surely, every one whose heart is rightly exercised in this godly duty,
which the living God calls us unto, must needs be innocent before God,
and in that frame of spirit, wherein we cannot, no, dare not, desire the hurt of any;
but as the Truth arises, pray for all men, both for rulers and people.
Thus I know, under the exercise of the righteous power of Christ in our meetings,
are our hearts qualified; and then if we must suffer for well doing,
under the name of evil doers, we shall be happy; and may satisfy ourselves,
with what Christ of old said, the servant is not greater than his Lord:
for if they accounted him a blasphemer, and said, he had a devil, and so persecuted him;
we may well look unto him, and comfort ourselves in following such an example.

Be comforted, you faithful sufferers with Christ and for him,
and comfort your hearts in the recompense of reward, which is with God for you;
and wait for the Spirit of God, and of glory, that it may rest upon you.

Never look out, for your cause is good; it is that which God has called you unto,
and you are happy in your nobility and valor;
and whosoever shrinks from their innocent testimony in this matter,
will suffer loss in their inward condition: for if any draw back,
such shall know the Lord will not go with them, nor have any pleasure in them,
nor be their comforter, but reprover.

My soul desires that all may be valiant for the Truth, and stand in the power thereof,
to what the Lord has called unto, that so you may be together as a city set on a hill,
that cannot be hid.
For though the foxes have holes, and the fowls of the air have nests,
yet remember what Christ said to the man who said he would follow him.

The Lord give you all valor and strength, and enrich you with true patience,
which tribulation works into the right exercise,
that you may all grow up into the true experience, and into the hope,
which makes not ashamed;
that the love of God may be shed abroad in your hearts every day, by his Spirit,
which he has given you: and then will you all feel a dwelling in his covenant,
and in his peace.

And so in this covenant, peace and love, I very dearly salute you all,
and in it do I still remain, your friend and brother.

[.signed-section-signature]
John Burnyeat

--

Cork, the eighth of the eleventh month,
1682.--I have been through these parts as far as Castlehaven,
and had a meeting there yesterday week, and so returned back again to Cork,
to the six-weeks meeting; where we had a blessed season,
the Lord`'s power was richly among us.
And after tomorrow, I think to go towards Youghal, and so into the county of Tipperary,
and then to Castle-dermot meeting; and then as far as I know, towards Dublin.
I am comforted in my service among Friends, who are generally glad of my coming,
and of what they have an expectation of in relation to my marriage:
but my heart is fully satisfied, in that I feel the Lord`'s goodness towards us,
and in his fear I do delight to wait upon him in this, as in other things,
and desire that we may be a good example.
And, therefore, I find it our way not to be hasty: the Lord give us wisdom to walk so,
as that he may be glorified, and Friends in us comforted.
This I desire above all earthly things.

Dublin, the thirtieth of the first month,
1683.--I am concerned to hear of the continued sufferings of our Friends in England:
we are yet at ease here, as from those things:
the Lord work our hearts more and more into thankfulness, and guide us in wisdom,
to walk worthy of these favors, that in displeasure he may never take them from us;
but whenever he is pleased to remove them, it may be in his love, for a trial unto us,
as I believe it is with many of his faithful ones,
whom my soul desires he may still preserve in the faith that gives the victory.

I have been in the north, and did pass among Friends, and had a blessed service.
I am intending to go forth of this city tomorrow towards Wicklow,
and so through the county of Wexford to visit Friends there.

Dublin, the tenth of the third month,
1683.--We have now accomplished that concern of marriage,
which we have for some time been under; and blessed be the Lord,
he has been unto us a comfortable director in our undertakings in this matter,
to the satisfaction of Friends in the general, who were with us.

And besides the Friends of this city,
we had many of the Friends of the south end of the nation,
who were come to be at the half-year`'s meeting, and some the sooner upon our account;
and abundance of other people.
We had a blessed meeting; several brethren were with us, and the Lord`'s power assisting,
all things were well, and we had peace and comfort, and the Truth was honored;
and not only Friends,
but many sober people were greatly affected with the management thereof. Well;
the Lord will honor his name and way and people, if we be but careful to honor him.

The Lord is good unto us: we have cause to mind his goodness unto us;
and truly that which is chiefly in both our hearts, is to seek his glory,
and above all things to desire preservation in his wisdom.

Dublin, the twenty-fourth of the fifth month.
--There is a report abroad, that meetings will be disturbed and broken up,
but nothing is done yet; it may be that Friends here, as well as in other parts,
must bear the burden, as to the right part in suffering; and I hope,
it will be Friends`' care to be given up in the innocency,
to suffer for that testimony the Lord has raised in their hearts,
by which we have been kept innocent and clear from the beginning under all governments:
and so we never could touch or join with that which did seek the hurt of any.

This must be our cloak or covering, and this gives boldness,
and is and will be the ease of the spirits of all the faithful,
and that which will answer the consciences of our adversaries.
I believe, if some suffering does come, it will work for good through trying our spirits,
faith and patience, so that many may come to know themselves, and the Lord,
and his power also, better thereby.

From the Marshalsea prison in Dublin,
the ninth of the sixth month.--We are very likely to partake in some
measure of suffering with our Friends and brethren in England.

The last first-day, the mayor sent the marshal to our meeting in the forenoon;
I was speaking, and he commanded me to go with him, which after some discourse I did.
He commanded the meeting to disperse, but Friends kept quiet in their places.
I was carried before the mayor, with whom I had some discourse to this effect:
He asked me, why we did act contrary to the government,
having been commanded not to meet?
I told him, we do nothing in contempt of the government.
But, said he, why do you not obey then?
I said, because it is matter of conscience to us,
and that which we believe to be our indispensable duty, to meet together to worship God.
To which he answered, you may be misled. I told him if we were misled,
we were willing to be informed, if any could do it.
Then it was urged, other dissenters had submitted, and why would not we?
I said, what they do, will be no plea for us before the judgment seat of the great God.
So after some other discourse, the mayor committed me to this prison.
The professors have left their public meeting-places: the bishop of Dublin sent for them,
and they consulted together, and with consent returned this answer,
that they would forbear.
The bishop also sent for A. S. and did to him require the same of Friends;
but A. S. told him, we could not forbear to meet to worship God, etc.
In the end the bishop said, if we would meet, we must take what did follow, etc.
However, I hope it will work for the honor of Truth.
The Lord preserve Friends faithful and valiant: I hope God has a remnant,
that will stand in the trial: though if sufferings do come hard,
it may cause some to turn their backs.
Let the Lord order, as He pleases; I know no better way,
than to endeavor to be prepared for suffering.

[.embedded-content-document.epistle]
--

[.letter-heading]
Epistle to Friends in Gloucester Prison.

[.salutation]
Dear Friends,

Unto you, who are faithful sufferers in that city,
with the rest of the faithful in that country,
who in your hearts are given up to suffer for the holy
name of the Lord Jesus Christ our Savior,
who has called and redeemed, chosen, and given you hearts not only to believe,
but also to suffer for his name`'s sake,
and thus had counted you worthy as vessels of his choice; unto you all, I say,
in the name and love of Christ Jesus our Lord, I send greeting,
and with all the tender salutation of my soul and
spirit in that near affection and holy union,
into which, by the power of the Holy Ghost we have been gathered and united:
so that as members of that one body, into which we have been baptized by that one Spirit,
wherein the true access unto God does stand, we have our fellowship together,
and so drink together into that one spirit,
and are refreshed with the water that flows from the living Rock,
that followed Israel of old, who is the Rock of our age,
the stay of the generation of the righteous in this day,
that upon which we have our sure standing, so that we cannot be easily moved.
Though the winds do blow, and the waters swell and toss,
and the unestablished be driven to and fro, and so afflicted in their spirits,
yet this Rock abides for a habitation and being
of safety unto all them that keep firm thereunto;
and as they abide near in their spirit unto the holy power thereof,
they find the living spring of that grace from the same in their souls,
that the world cannot take away, whose treasure the thief cannot steal,
nor the moth waste; for it is heavenly, and kept by a heavenly hand.
And such who mind this, will be ready to offer up their earthly substance,
and also themselves, into his hand and will, out of which no man is able to pluck.
And surely,
in this day there is no true rest or satisfaction to the souls or spirits of Friends,
except as they get here in the faith with their hearts and spirits:
and when we are here spiritually.
Oh, this holy shield, how does it defend!
Oh, the holy Rock, how do we sit under the shadow of it!
Oh, the holy joy, that the dwellers upon this do feel in their spirits,
though the tempest be great!
Oh, the God of heaven keep us all in the holy sense of this,
that our spirits may be borne up from sinking under our exercises in the trial;
that so we may all glorify him in our day.

Dearly beloved, you tender, suffering children, whose hearts are tender of God`'s glory,
and therefore are willing to give up yourselves and your all for his name`'s sake,
that you may be of that number, who following the Lamb wheresoever he goes,
and not loving your lives unto death, that you may stand with him upon Mount Zion:
my heart and soul is knit unto you, and you are near me,
and in the unity of the ancient life, I feeling love abundantly to flow unto you,
you have had a proof of the sincerity of my love of old unto you: and truly,
you that stand in your innocent testimony faithfully,
do engage my heart still more and more in the love unto you.
Oh the tender meltings of my spirit in the sweetness of the love of God,
in which I reach you, and rejoice with you in your joy,
which all the wrath of man cannot put a stop unto.
I know, your hearts are at ease, and your spirits free,
and the weights and burdens from off you who are freely given up to suffer,
though in these bonds outwardly;
but there can be no such spiritual portion received by any
that shrink from their testimony in this day of trial.
For the word is true forever, they that suffer with him, shall reign with him: He,
the Captain, was made perfect through sufferings,
he must be followed by all that come in the fulness, to partake with him of his glory.
And such who draw back,
and would find a place of safety for themselves
to escape their sufferings for their testimony,
though they should fly to the uttermost parts of the earth,
the Lord`'s hand will find them out,
and there will not only be a holding back of the portion,
but a spiritual pain will overtake, where the heart is tender; and because thereof,
uneasy will every place be unto their spirits.

And therefore, my dear Friends, keep in the faith and word that justifies,
and then will you reign in the seed that is heir forever; wherein you will overcome,
and inherit, and be conquerors, and so triumph with the Lamb that must have the victory,
before whose feet the crowns of all the mighty must be laid down;
unto whom the kings of the earth, and all flesh must bow; in him we trust,
his heavenly kingdom we wait for, and pray for the coming of,
that even such as are our enemies, by the power thereof may be converted unto God,
and so have an inheritance with us in that kingdom, that has no end.
That so mankind might rest together in that hope, that makes not ashamed;
where the love of God might be shed abroad in all hearts by his Spirit.
Thus God is filling the hearts of his children with good will towards all:
the Lord keep us therein forever!
Dear Friends, by this know that I am well,
and am now come to have a share with you of the
sufferings that attend for the gospel`'s sake.

I have been three weeks a prisoner here in the Marshalsea of Dublin.
So in the true fellowship of the gospel am a partaker with you both of the
sufferings and consolation that attend us for the testimony thereof.
I remain your brother.

[.signed-section-signature]
John Burnyeat

[.signed-section-context-close]
From the Marshalsea, in the city of Dublin, the 25th of the Sixth month, 1683

--

Dublin, the ninth of the seventh month.
--We are satisfied, that the Lord`'s hand is in all these things; and doubtless,
he has a purpose to magnify his arm,
and thereby to exalt his own name and precious Truth in the end; and in his so doing,
his people shall be comforted, and receive the reward,
even every one that endures unto the end.
And truly, as our eye is unto Him in our exercise,
we feel still a ground for a sure hope,
even that which abides as an anchor sure and steadfast; by which we are held,
that we cannot be driven away.
In this is our comfort, when we seem as to the outward, as if we had no surer place,
than upon the tossing waves of the troubled tempestuous sea; all is uncertain,
no steadfastness or stay for rest unto any in looking out.
And therefore I often think, I am satisfied it is God`'s way,
thus to blow upon the nations with the breath of his displeasure,
that all the waters (for the people are waters) may be tossed together,
and that they may be made restless, and driven on heaps, and into confusion;
and so become a sea into which Babylon, as a great millstone, must fall,
to make her perpetual end; even that mystery Babylon spoken of, of old,
that has so prevailed, and made the nations drink, and gone over peoples and languages;
--not one people only; and all that partake with her in her sins,
must partake with her in her plagues and judgments.
And therefore is the Lord calling out of her; but her sins, her delights and delicacies,
many are unwilling to part with: and that is the reason why many stay there,
that do not think themselves within her borders.
But the nations are drunk with her wine, and know not what they are doing;
for their understanding is lost.
O!--the sadness of that day! My soul often does view it but the
greatness of their sin does draw it down upon them,
which is come into the view and remembrance of the dreadful God.

And therefore may all the righteous rejoice, who truly feel redemption out of her,
and are come, through Christ the seed, to be sons and daughters of Zion;
and so heirs of the peaceable Jerusalem, which is built upon the rock and foundation,
which the gates of hell cannot prevail against.

We are here still detained prisoners, and have of late written to the mayor;
but he answered, he would not set us at liberty without an order from the deputy.^
footnote:[The Earl of Arran.]
Then we wrote to him, and A. S. and S. C. did go to him, and he was very kind to them,
and told them, he had a greater love for us, than any other dissenters,
because he believed that we did mean honestly.

Dublin, the fourth of the eighth month, 1683.--I have been a time in the country,
and came into the city again but yesterday.
I went to the province meetings at Rosenallis, and have visited many meetings:
I was comforted with Friends in the good presence of the power that did attend us.
Things are pretty well among Friends, and our meetings large and full.
We feel little of those sufferings which our
dear Friends in England have heavy upon them:
the Lord preserve us tender, low and humble,
that we may be worthy of such a mercy from the hand of the Lord.

Dublin, the sixteenth of the eighth month.--I am now cleared of my imprisonment;
we wrote to the deputy a few lines, which he carried to the council.
After which he sent his secretary to the recorder of
the city with his order for our release;
which was very full and clear, without anything demanded of us.

I have not heard that Friends in any part of this nation are meddled with.
We enjoy great favors at the hand of the Lord:
O!--that we may walk worthy thereof forever,
and be moved thereby to a sense of what our dear Friends in England still suffer;
and then will the mercies we live under, be rightly valued.

Dublin, the ninth of the twelfth month.--I have been through all the meetings in Ulster,
and returned home but the third-day this week.
I had a blessed time among Friends, and found things in the main very well.
I had large and peaceable meetings,
which is a mercy I desire the Lord may so sanctify unto us,
as that we may walk worthy of them, while they are afforded us:
and when he sees fit to order it otherwise, we may be prepared.
I have been but little at home of late,
and know nothing but that I may go next week forth of
town again towards the other end of the nation.

Dublin, the seventeenth of the first month, 1684.--I came home this day:
I have been through the most of the South and Western parts, and have had a good journey,
and found Friends generally well, and all our meetings peaceable.

Dublin, the twentieth of the first month.--In my last I hinted,
that I was but newly come home from visiting Friends in the Southend of the nation,
and so from the Province meeting at Castle-dermot, I came home on the second-day,
and an appointed marriage^
footnote:[This was Amos Strettel`'s marriage.]
was to be on the third-day, which took place accordingly;
and abundance of people there was, so that we had a good opportunity,
and the people generally well satisfied:
so that a very great report of recommendation is abroad
through the city concerning our order and method,
and the gravity and solemn manner of our accomplishing it.
It is greatly our comfort, when in all our ways we honor the Truth.

I have had a busy winter in traveling, and that prosperously; and now I see nothing,
but I shall have liberty to stay awhile at home.

The Lord is good to us, and orders things to our comfort; and we are comforted in him,
and one in another: blessed be his name forever!
Dublin, the ninth of the third month,--It is just the time of our half-year`'s meeting,
and there are many Friends in town.
We had a very large meeting, and very quiet and well,
and things in the general very well among Friends as relating to Truth.
We have cause to be thankful to the Lord for his mercies and comforts we enjoy;
who is the Author of all mercies and comforts,
sanctifying all things rightly to them that fear and love him,
through the sanctifying of their hearts by his word, that keeps, bears up, and upholds.
The Lord keep all our hearts stayed in this,
and then will all things work together for good, according to the ancient saying.

Crabtreebeck in Cumberland, the twelfth of the sixth month.--I left Dublin,
sixth-day was a week; I have some intent to go over into Scotland,
but am not yet certain of the time: but do hope, if the Lord preserve me in my liberty,
to return into this country again.

Graysouthen,
the nineteenth of the sixth month.--Between two or
three weeks`' time I hope to be as far as Edinburgh.

Leith,
the sixth of the eighth month.--I have had a very peaceable and prosperous journey,
since I came into Scotland hitherto.
I came to Edinburgh at the time appointed, and stayed here one first-day;
and then took my journey into the north, and J. H. and J. T. with me.
I spent about three weeks there, and in my journey: had meetings, while I was there,
almost every day, and a blessed open service, through the Lord`'s power, among Friends.
For there is an open, tender-hearted people, and they were glad of my coming;
for there had not been any English Friend among them of a long time.
And being clear, J. T. and I came away this day a week, and left J. H. there;
we got to this town the fourth-day of the last week,
and were at Edinburgh the fifth-day at their meeting,
and yesterday had a blessed meeting there in the forenoon, and here the afternoon.
Tomorrow we intend to take our journey for the west;
and do hope to be clear this day week to go for England,
and to be in Cumberland tomorrow week, if the Lord will.

Hitherto all has been very quiet where I have been; and I hear nothing,
but Friends`' meetings are quiet all over Scotland, and Friends are permitted to be quiet:
but in some places they are very busy with some other people.

Here has been much ado about a plot; but of these things we know nothing,
nor in such doings have any hand, and therefore about it desire not to meddle.
Though others`' doings may bring sufferings upon us; yet still our happiness is,
to be kept innocent, that if we suffer, it may not be for evil-doing;
and then it will be well.

Eaglesfield, the twelfth of the ninth month.
--Truly in this trying day,
wherein we are all of us like to have our faith and love to God tried,
our greatest concern always is, to be in our hearts truly and wisely given up,
and resigned to the will of God;
that we may therein rest in and under whatsoever the Lord may order for us,
or call us unto; and then may we have peace in every exercise,
and have dominion in our spirits over every opposition,
many of which the true travailing Israel of God meet with in this age.

I got very well through the west of Scotland, and met with no disturbance:
all was quiet when I was there.
Our meetings are quiet in Cumberland: I suppose, I may stay yet about two weeks here.

Stockton, the eleventh of the tenth month.--I came out of Cumberland about two weeks ago,
and was at Strickland-head, and then came on into Bishopric,
and thought I should but have touched at Darnton +++[+++Darlington]
and this town, and so on into Yorkshire; but when I was at Darnton,
it came upon me to give Friends a visit further in this county.
So I went to Durham, and had a blessed meeting there, and did visit the prisoners.
Then I went to Sunderland, had a meeting there, and then to Shields,
and to T. F.`'s and had a meeting there.
From there I returned to Shotton, and to this town,
and had a blessed meeting in the evening yesternight, it being their meeting time.
They are usually kept out of their meeting-house here; but yesternight we got in,
and the meeting was full and peaceable: and so have been all the meetings,
where I have been.
And now I am ready to go over into Yorkshire,
and do hope to be at York in about two weeks`' time.
I suppose I may be there first-day come two weeks.

Grayrigg, the twenty-sixth of the eleventh month,
1684.--I have had a very comfortable and peaceable journey,
and came through Cleveland and the Moors to Whitby, and from there up to Malton,
and to York: meetings have been quiet all along where I have been.

Yesterday fortnight a constable was at the meeting-house before I came,
and stood in the way to speak with the Friend that I came along with,
it being just before the sessions.
He had a warrant, and was to give his return at sessions; and therefore threatened,
that if we would not forbear to meet that day, he must carry us before a justice.
However, after we had reasoned awhile with him, we parted, and went into the meeting;
and he went away, and did not come into the meeting.
So we had a blessed meeting, and parted in peace; and the Lord`'s power was over all,
to our great joy.

This was all the appearance of molestation I have yet met with:
and I have had a very good season, and abundance of meetings, since I left York.
In Yorkshire I was at Robert Lodge`'s house,
and had his company a pretty time out of Yorkshire.
I went to Lancaster, and when I had visited Friends,
I came into Westmoreland to Preston meeting; and yesterday was at Sedberg:
we had a peaceable meeting, but out of the meeting-house in the street,
the meeting-house being locked up from Friends.
I intend some meetings in this county, and so down to Swarthmore,
and on into Cumberland, as the Lord makes way.

Eaglesfield, the twenty-fifth of the twelfth month.--I have had a very peaceable journey,
and visited Friends`' meetings very fully in Westmoreland, and all was quiet.
Since I came into Cumberland, I was at Carlisle and the Border;
now my service seems to be over, and I am preparing to go home.
I was at Workington this day, and tomorrow I intend to go to Whitehaven,
and to take the first opportunity for Dublin.
Thus far I have been preserved very well through all my travels;
and now I hope I shall get home.

Dublin, the 25th of the first month, 1685.-- I got well here last night,
but was put ashore in the north, in Strangford River, about seventy miles from Dublin,
and about four-and-twenty from Lisnagarvy: and being put ashore there,
I found an openness in my heart to give Friends a visit in the north;
so I spent near two weeks among them, and had many good meetings,
I am very glad and my heart is truly thankful to the Lord,
for his preservation through this last journey so safe and clear,
and that he ordered my way so comfortably home;
where I hope I may be of service in my place, and a comfort to Friends.
The Lord our God is to be minded by us in all things.

I find things among Friends generally pretty well, as formerly,
and meetings very large and peaceable here and in the north.
I am intending to go out of town to the province meeting.

Dublin,
the sixteenth of the third month.-- At this half-year`'s meeting we
had a very great appearance of Friends out of the country,
many say they have not seen so many ever before:
and to our public meetings abundance of other people came,
even far more than could get into our house: and they were very sober,
so that the Truth has a good place among sober people.
Though the professors, who shrink and hide, we are informed, do rail against Friends;
they seem as if they were given up to hardness of heart,
and so set in their blindness and hardness, that they go on,
till the rod comes upon them.
For they do not lay anything so to heart,
as thereby to be brought off from the evil error of their hard and prejudiced minds.
It does appear that they envy Friends`' good,
and are offended that we do not fly into holes as they do.
But as for Friends, they are very cheerful; and we have had a very blessed season,
and are kept in unity, peace, and concord in our meetings and concerns:
and the Lord`'s good presence is preciously with us, to our comfort and consolation.
And blessed be the Lord, he is not lacking to us, both to sanctify our hearts,
and also to fill them with his spiritual mercies,
and to contribute of his other mercies and blessings,
whereby he may make our days pleasant unto us;
that with gladness and joy of soul we may serve and praise him, who is worthy forever.
Amen.

Dublin, the fourth of the sixth month.--Yesterday I came home,
having been through the south end of the nation, and between six and seven weeks away;
and have had a very comfortable journey among Friends, and peaceable.

Blessed be the Lord for his mercies towards us.

[.embedded-content-document.letter]
--

[.letter-heading]
Epistle to John Banks

[.signed-section-context-open]
Dublin, the 19th of the Sixth month, 1685.

[.salutation]
Dear John Banks,

Unto you with your fellow-prisoners,
who suffer for the blessed testimony of that precious Truth, in which we have believed,
does the real and tender affection,
and love of my heart and soul flow forth at this time;
and in the sweetness and peaceableness of that which is our life, do I dearly salute you,
and in the unity thereof tenderly greet you all, whose hearts are kept up in that,
and under the holy conduct of it, for which you suffer.

In this we have our unity, which in itself lives and reigns over all,
and shall reign in its own pure dominion and dignity,
even the power of our Lord Jesus Christ, to whom principalities and thrones,
and dominions must be subject.

It is for His testimony, you know, that you suffer, namely, the testimony of Jesus,
which you have received from him by his Spirit,
and thereby have it sealed in your hearts.
Though many do not understand the weight and certainty of your testimony,
for which you suffer, and therefore may look lightly upon it; yet you,
who are enjoyers of the power, and have received the Spirit of Jesus,
which is the Spirit of prophecy, and so his testimony therein, you feel the weight of,
know the certainty of the testimony for which you suffer;
and so in your sufferings have your peace and justification.

My dearly beloved in the Lord,
see that you all hold that fast in your hearts in the rich possession of it,
for which you suffer, that you may feel your reward with you,
and your comforter in you to bear up your spirits over all your sufferings;
and so you will have a satisfaction in yourselves, that whatever others say,
or may think of your sufferings, and the reason thereof,
you know that it is for the Truth and its testimony that you suffer,
and for keeping of your consciences clear in the sight of God.
And so in the hidden man of the heart, you rest in quietness,
in that hidden life which you receive from Christ; and here is your peace and comfort,
which no man can take from you; or knows of it, but such as are in fellowship with you,
who live in, and love the same testimony.
Those who know not your reward, your crown, or your peace, cannot reach to take it away;
and that is our joy, that we have a crown and inheritance, that is out of their sight,
and so out of their reach.

Oh, therefore let all take heed, that through carelessness or looseness of spirit,
or any other thing, you be not beguiled or betrayed from that, to the losing of it,
while you are suffering for it!
You know, my Friends, it is possible; such things have been even in our age,
that while some have been suffering for the Truth,
they have been betrayed from the Truth,
and the innocency and simplicity of it in their hearts; and so have lost the Truth,
even that for which they were called to suffer.

For you know it is an inward thing,
and must be held in the inward unity of the mind in a
spiritual fellowship, and if there be not a care,
even while we are in one thing doing for the Truth in the outward,
in the inward we may lose it, and our justification by it;
and then where shall we go for our peace and recompense?
The God of my life give you all wisdom and fear, and fill you with holy reverence,
that you may still stand in awe before him, and be watchful over your spiritual path,
and the feet of your souls and minds,
that you may tread in the invisible way of peace and righteousness.

And dear Friends, live in peace and love together among yourselves, and in a holy,
solid life before all men, keeping out of the spirit of the world in all things;
that as it is upon a religious account you suffer,
you may appear in all other things to be religious men, or otherwise you know,
the Truth cannot be honored by your suffering.
For if men, who suffer for or upon the account of religion,
appear not to be religious men, this overthrows the glory and beauty of their religion,
and brings it into disesteem among men; and therefore did Christ command,
that our light should shine before men, by their seeing of our good works, etc.
And have a care of provoking one another unto anything that is evil;
but endeavor to stir up and provoke one another unto love and good works;
that you may build up one another therein, and so help to bear one another`'s burden,
and fulfill the law of Christ,
that you may all be kept up together in the justification and peace.
And so dear Friends, my heart`'s love being unto you,
I send these few lines as a testimony thereof, by which you may know,
you are in my remembrance in the love of God,
and my heart has an honorable esteem of your testimony,
and your sufferings in righteousness for the same.
I desire to be remembered to Friends in the country, both below Carlisle, and above,
and Friends in the city; to John Carlisle and family, with the rest.
My wife`'s dear love is to you all.
My love is with you.
Farewell!
From your friend,

[.signed-section-signature]
John Burnyeat

--

Dublin, the sixth of the seventh month.-- I am glad to hear,
that things are so still and quiet in England,
and that Friends have some little breathing time of ease from their sharp persecution.
It is the Lord`'s mercy towards us: but our innocency is that which must speak for us;
and if we lose that, our defense would depart from us;
and then there would be none to fly unto: for vain is all help from below.
Therefore it will be our happiness to rest quiet, with our faith in Him;
for he is able to preserve, who promised them of old,
he would give them favor in the eyes of the king of Babylon.
And it had been their safety to have trusted in His word;
but in their taking their own way, they brought ruin upon themselves;
and so will all do now, whose eye is not unto the Lord to stay their minds upon him,
but who look out to follow their own contrivances.

I know the Truth will keep out of all such things,
if Friends be careful to keep under the conduct thereof:
but if fleshly reasonings prevail in the unbelief, then the eye goes out,
and the mind falls into the haste; so the patience and long-suffering is lost,
and the hope and faith let fall.
Then the creature can neither trust in the Lord, nor stay rightly for His time and season.

Our meetings are very quiet and peaceable, which is a mercy we greatly value,
and our hearts in the Lord`'s Truth are at rest, and that is our comfort.
Both there and here, and wherever we are,
it will be our place to be prepared for suffering,
that is likely to be our portion for the Truth: and it is but as it was of old,
if any will live godly in Christ Jesus, he must suffer persecution.
I am ready to go out of town to visit Friends in the county of Wicklow.

Dublin, the nineteenth of the seventh month, 1685.--I am sorry,
that so much occasion of offense should be given to some Friends here,
by some that take liberty there,
(at London,) by running back into such things as the Truth condemns,
and so to be encouragers of pride and vanity, which will grow too fast,
to the drawing down of the displeasure of the Lord upon man.
Therefore I would have Friends to stand in that which is plain,
and keep to the cross in their trades and dealings, and clothes, and in all things,
that they may remain standing witnesses for God in righteousness against pride,
and all the vanity of the world; for therein will stand our safety forever.
I desire, that we may live up to the Truth in all things, that the blessing may attend us.
And indeed, we had need to be circumspect; for every lawful thing is not expedient;
because there may be an unlawful liberty strengthened thereby.
The Lord keep us all in his wisdom truly lowly and humble,
that we may still honor him in all things,
and remain a people through our day to his glory.
For if with us in our day we let the spirit of the
world prevail to the overthrowing of our own testimony,
what example and footsteps shall we leave to them that come after us?
I am full, and could say much, for my heart is concerned to hear those,
who themselves are not so good as they ought to be,
strengthen themselves by bad examples.
For though some may be slow to mind that which is good,
so as to learn good from the example thereof;
yet they are quick to take encouragement from the contrary.

[.embedded-content-document.epistle]
--

[.letter-heading]
Epistle to Friends

[.signed-section-context-open]
Dublin, the 12th of the Eighth month, 1685.

Dear Friends,--In the universal spirit of life and truth, and of righteousness and peace,
does the tender affection and pure love of my heart flow forth and reach unto you all,
who are true lovers of the power and the holiness of the same, wherein alone it is,
that we bear the image of him whose name is holiness, and his nature and being in purity;
so that in that only we do draw and may draw near unto him, and have fellowship with him,
and enjoy his presence, who is our God, our life and salvation.

In the unity of that, whereby we have been quickened,
and through which we live unto him who has quickened us, do I exhort and beseech you all,
to mind with reverence his secret and sweet visitations
by his holy power upon your spirits in your hearts;
that you feel that to appear there,
and so through the brightness of its appearing to destroy him,
whose coming is after the working of Satan with all power,
and with all deceivableness of unrighteousness in them that perish;
and not only to appear and destroy him and his works, but also to abide with you,
and dwell in you, and so make you his dwelling-place.
And you being watchful, shall not watch in vain, because the Lord will be your keeper;
and then, he keeping the city, the watchman wakes not in vain.

Thus you may see it fulfilled in your own hearts and so
have comfort and confidence with holy David,
and with him live above the fear of evil,
though you might walk through the shadow of death, because of the Lord`'s being with you.
Friends,
see that you all be mindful of him in his appearing by
his power and spirit of grace in your hearts,
and let him have room there, and not to be straitened, thronged or oppressed;
for he delights to dwell alone there, and have the whole heart to himself,
and at his own disposing, that he may fill it with that in which he takes pleasure,
and in which he only may be glorified and honored.
Therefore does he require the heart, saying, my son, give me your heart;
and Christ commands that we should love him with all our hearts.
So let him have room in your hearts, and take heed that with this world,
the spirit of it, nature of it, and love to the things therein,
your hearts be not filled, and so taken up, that there be not room for him,
whose coming is with such glory and fulness,
that he fills all who are rightly poor and empty, with that fulness, richness and glory,
that there can be no lack to them, who have him for their portion and inheritance;
and keep single in their hearts before him.
But where the heart is filled with delight in, or desire after other things,
out of the covenant of God, which is out of his favor,
there the Lord will not delight to dwell, there is not room; no,
he will not delight to appear there,
because it will be his grief and an oppression unto him.
Was it not so of old,
when he took up his complaint against both Judah and Israel?--as you may see in Amos 2.
how the Lord pleads with them, and threatens them,
what he would bring upon them for their sins, which he reckons up against them;
and withal to aggravate their crimes, as he might justly do, he also tells them,
what he had done for them, how he had destroyed the Amorites for their sakes,
brought them out of the land of Egypt, led them in the wilderness,
given them the land of the Amorites to possess, raised up of their sons to be prophets,
and their young men to be Nazarites.
But, says he unto them, you gave my Nazarites wine to drink, and commanded my prophets,
saying, prophesy not; behold I am pressed under you,
as a cart is pressed that is full of sheaves.

Hence it may be understood, that when he has been at work,
and has done good by his glorious power, who works wonderfully for them,
and now in them also who believe in his power; if there be a going from him,
and letting other things into the heart,
where he should rule and have his dwelling in man, and so with man,
it becomes a grief and an oppression to him, and a provocation,
that he will not always bear it, nor spare man, though he is long-suffering,
as may be seen very fully in that prophesy of Amos,
and more at large through the Scriptures, which were written for our learning,
that we might be warned, and thereby stirred up to that diligence,
care and watchfulness which may tend to our preservation.

And now considering these things that were of old, and observing,
how that in our age the Lord has made known his goodness to us,
even that which does far exceed the outward privileges of outward Israel;
for that which he blesses us withal,
is a possession and enjoyment of a degree of his own Life, who is the Creator,
by which he created all things, which is more than the enjoyment of the creature;
the loss of which was the great penalty laid upon Adam, if he broke the command,
which he having lost, is again restored unto us through Christ Jesus, the second Adam,
the Lord from heaven, which we having received, do thereby live unto God,
and therein serve him.

Dear Friends, the thing that is chiefly in my mind unto you is,
to entreat and beseech you all, to be tender in your hearts,
and careful over your spirits, that you may not let in, nor join with anything,
that will bring grief or oppression upon your life,
or lead you into the transgression of the law thereof.
Mind the exhortation of the apostle, grieve not the spirit, by which you are sealed, etc.
As you are careful,
watchful and wise to take heed to the holy conduct and blessed
leadings and direction of this spirit and the law thereof,
your souls will dwell in peace, and your feet will tread in a safe path,
even the path of peace, and your steps will not slide;
but you will witness what David said of old, to be true,
the righteous shall inherit the land, and dwell therein forever; for says he,
the mouth of the righteous speaks wisdom, and his tongue talks of judgment.
The law of his God is in his heart, none of his steps shall slide.
So here you see, what it is that keeps from sliding,
the law of God which is in the heart; this preserved David,
for it was as a lantern to his feet, and a light unto his paths.

Oh! My dear Friends, you may be happy; yes, we may all be happy,
if we be as careful as we ought, to walk by this rule.
Oh!--the sweetness, peace and glory, that he fills the hearts of all his people with,
who take heed unto his law: the Spirit is not grieved,
the life of the soul is not oppressed, the soul, life or spirit of man is at ease,
and so in the glorious liberty of the sons of God, and in that state,
where it can sing unto the Lord and praise him.

Therefore all of you mind your dwelling and inward liberty,
and spiritual freedom from all the corruptions of the world, and of the flesh,
both inwardly in yourselves, and all temptations from without,
that you may reign in the dominion of the Seed Christ Jesus forever,
and so with him be co-heirs of that heavenly inheritance and possession,
which he has purchased for you.
In the unity of that life, which reigns over all, do I very dearly salute you all,
who love the Truth; and in that do I desire,
that the God of life may bear up your spirits by his power,
over all that would defile or oppress;
that you may be preserved to remain the sons and daughters of God,
without rebuke in and among this crooked and perverse generation,
among whom you shine as lights,
to the glory of him who has called you out of darkness into his marvelous light;
who over all is worthy of glory and honor and dominion, world without end.
From your friend and brother in the Truth,

[.signed-section-signature]
John Burnyeat

[.signed-section-context-close]
Dublin, the eighteenth of the ninth month

--

We have had a comfortable season this half-year`'s meeting, quiet and peaceable,
and in love and unity among ourselves;
so that we have cause to be truly thankful unto the Lord for that mercy,
among all other mercies we enjoy from his blessed hand.

[.embedded-content-document.letter]
--

[.letter-heading]
Letter to Roger Roberts

[.signed-section-context-open]
Dublin, the 23rd of the Eleventh month, 1685.

[.salutation]
Dear Roger Roberts,

In the love and unity of the blessed Truth, which lives and abides forever,
do I very dearly salute you and your wife;
and therein is my heart`'s desire for you unto the Lord,
that by his blessed hand and power,
you may be supported under all exercises that may attend,
and in your minds preserved with an invisible eye unto the Lord,
taking notice of his orderings, as it is his hand that brings to pass what he sees good;
and then in his fear and love there will be a reverent submitting to
his will without murmuring or repining at what the Lord does.
Though nature in the true and natural affection,
which good men and women cannot be without, may be broken and greatly bowed down;
yet as long as the mind is preserved from murmuring at what the Lord does,
it will be well; there will be a heart capable of giving him his due, as it was with Job.

Dear Roger, I must needs say my heart is concerned for you, both upon your own account,
having heard of your great weakness, and affliction you have been under,
and also because of the loss of your dear and tender daughter,
who in your absence is taken away both from you and us.
But what shall I say?
It is so, and the Lord has done it; and it is not safe to dispute the case with him,
or say, why has he done so?--but tenderly submit to his will,
and bless Him that gives and takes away, as he sees good.
However, this I think I may say to you and your wife with safety, you need not sorrow,
as such who have no hope,
because of the ground God has given for a sure hope of her eternal well-being,
which is the mark we are all pressing towards; and they are happy who do obtain it.
For I was with her the day that she died, in the afternoon, and had a serious,
weighty season with her.
She sent for me, and told me, as soon as I came to her,
that now she was satisfied she must die;
and her heart was wholly set after her assurance of peace with the Lord;
and her desires to us, that is, her husband and me, were,
that the Doctor might not trouble her,
for she was not willing to be hindered from a quiet departure.

For her heart was set after a peaceable departure out of this world;
as was evident from her words several times.
She was very sensible, and spoke to me with a good understanding;
and seemed to be concerned for many (as she said) who came to meetings in Dublin,
who did not mind their conditions, or the stay of their minds,
whom she feared would scarcely be saved.
My heart, I must needs say, was greatly affected with her exercise and concern,
and was comforted in the sense of that living presence, that was with us at that season.

When we had spent some time together, and were refreshed, and I being about to go away,
she did most solemnly take her leave of me in great affection,
and signified how kind she took my visit; withal seriously saying, "`Farewell dear John,
if I never see you more.`"
And so I came away.
In a few hours after she was struck with death.

In the evening my wife and I went again to see her; we found her very ill,
but she lay quiet under the extremity of her pain.
We, with several other Friends sat by and waited on her, until she departed,
which was about the eleventh hour at night.
She went away in quietness, as I found before was her desire.

And we sitting and standing quietly by her, our hearts were broken;
and I felt a glorious melting power, which tendered my spirit,
and a brightness and a light that did shine; and it was sweetly in my heart,
when she was departed, She is not gone into darkness, but is in the light.
The sense whereof was a great satisfaction to me, because I know the glory is there,
in the light forever.
And now poor lamb, it is her gain, though your and our loss.

For considering her years, she was a modest and good example;
and as she said to me at that season, She was never inclined to vanity.
I perceived her care was sometimes greatly for you, fearing your exercise would be great.
Well, I must needs consider,
that the loss of such a dear child cannot but come very near tender parents;
yet you may be comforted in a satisfaction of her well-being, and so rest;
and even say with David, We may go to her, but she cannot come to us;
and so comfort your hearts in the Lord, and rest in his will.

And dear Roger, this may find you something better in health,
than we have of late heard however, I am sure my heart truly desires that it may be so:
and if the Lord give strength, I should be glad to see you here.
For methinks, all this while you have been absent, your place seems to be empty;
I cannot look upon it, that you should be from among us.
But if the Lord give strength, you should be here, bearing and having your share with us:
for I look upon you as one of us, and so methinks would not have you delay,
as the way opens.
My wife`'s very dear love is to you and your wife; and our love is dearly to Ellen Callow,
and Friends there.
For further account of things, I may leave to other hands.
We are all quiet and peaceable here.
So with my true and endeared love unto you, I conclude and remain your friend,

[.signed-section-signature]
John Burnyeat

--

Dublin, the twenty-ninth of the fourth month, 1686.--Though the world be full of tumults,
disquietness and amazements; yet, blessed be the God of our salvation,
who has brought us into a degree of that rest,
which the distresses that are from below cannot reach:
so that there is something known to retire unto for a sanctuary,
that the world knows not; neither can the destroyer come into it.
Therefore our safety is, always to keep our interest therein;
that we may have our privilege to our mansion there, and so rest in the time of trouble,
where no hurter nor destroyer can come.
The Lord`'s power is to be admired, loved and believed in forever,
who gives us blessed seasons, and calms, and quiets.
It is true forever, the winds and seas must obey him:
blessed are all that put their trust in him.
Fears and restlessness do possess the hearts of many; but for our parts,
we have an eye unto the Lord, and know he has a hand in ordering of,
or allowing all things, for ends best known unto himself; and therein we rest.

I desire that the Lord, by the indwelling of his power in our souls,
may still so keep and preserve us in that simplicity and godly sincerity,
wherein we may always know one another, and be a comfort one unto another,
in the plainness and simplicity of that blessed truth,
which saves and sanctifies from all unrighteousness, and unites unto God,
and brings into near fellowship one with another.
For this is that which sanctifies, fits,
and prepares the heart of man for every good virtue, and settles and composes his nature,
not only for heavenly mercies, and that he may receive and enjoy them,
but also for his station in this world, and the enjoyment of temporal favors;
that he may receive and enjoy them with a blessing, and in true comfort;
and also be a blessing and a comfort in his place unto all concerned.
This is the happiness and advantage,
which is to be witnessed through the working and indwelling of that eternal power,
which God Almighty has revealed in the hearts of his people in this day,
as there is a faithful minding of, and subjection unto it, in the true love of it.
And surely many there are, who if they knew the comfortable effects of it,
would not abide under its condemnation, as they do: but it is, as it was said of old.
They will not believe, though a man should tell it unto them.

Dublin, the sixth of the eleventh month,
1688.--The account of the death of my dear wife will be come to hand before this,
which is no small exercise to me.
But though my loss be great, in having her removed from me, yet I believe it is her gain.
For she has been under great weakness and exercise of body a long time; however,
this I can say, she bore her exercise beyond expectation; and told some Friends,
she believed she was kept the longer, because I was so unwilling to give her up.
And I must confess it was hard, that it could not easily be got to,
and that for several reasons: but when I saw that it must be so, I was made willing,
for her exercises took hold of my spirit.

The morning of the day she departed, she said to me,
she was afraid her passage would be hard: I told her, I did hope not.
She was under a great exercise of pain, but bore it with wonderful quietness,
and abode under it as one waiting for deliverance;
and very sensibly spoke to me a little before her departure.

So she went away like a lamb, without so much as a groan.
We lived comfortably together; her nature was good, kind, and courteous;
she was merciful, very considerate, and of good understanding:
she will be greatly missed in this place, for Friends had a good love and esteem for her;
and I have experience and know, that many who seemingly might exceed in appearance,
will come far behind.

Dublin, the seventh of the twelfth month.--We are pretty quiet here at present;
but people`'s hearts are like the troubled waters,--no stay or settlement,
who cannot tell what way to go to be satisfied, or be quiet in their minds:
only they who know the truth, may rest there and be quiet, under the covering of it;
otherwise it would be mighty uneasy.
I did intend for Cumberland, but at present Friends could not well bear my going away,
neither have I freedom in myself; so I rest in my place,
waiting the time and season for it.

Dublin, the thirteenth of the third month, 1689.--Our half-year`'s meeting is over,
at which were assembled many Friends and brethren from several parts of the nation,
according to our usual manner.
We enjoy our meetings peaceably and in quiet generally over the nation;
and in most places our meetings are large, and many people come in;
and all the people have now their liberty in the free
exercise of their consciences in matters of religion.

And as for Friends and truth, they are in good esteem, both with high and low.
The Lord`'s care and mercy over us has been largely manifest,
and Friends learn great experience of the preservation of the
mighty arm of the Lord in this great day of trial,
which is upon this nation; yet to our joy and comfort.

Friends are carried over it in the faith of the Son of God,
and have been preserved miraculously, even beyond our expectation in several places,
where their trials have been very great, and the dangers, as to appearance, dreadful;
yet Friends have kept to their habitations, trusting in the Lord,
and following their lawful concerns and business.

At this half-year`'s meeting our hearts were made more than ordinarily
glad to see one another`'s faces in such a time as this;
and the Lord`'s power and presence were with us, which crowns our meetings:
and in the sense and sweetness of the same are most of our Friends and
brethren this day gone towards their outward beings in the peace of God,
and in great love and unity, which did preciously abound among us in this our meeting,
throughout all our concerns and affairs.

The fourth-day next I am intending to go into the country towards our province meeting;
and think to visit Friends before I return.

Wexford, the fifth month.--I have had a very comfortable journey among Friends,
and for the most part very large meetings, beyond my expectation, and very peaceable,
on the third-day at Tipperary,
and fourth-day at John Fennel`'s. But at Tipperary I had
like to have been got hold of by the rapparees,
and lost my mare; but I got away and escaped, and rode back into the town.
Last first-day we had a very large meeting at Edward Gooding`'s;
it was their monthly meeting.
This day we have a meeting here, tomorrow at Samuel Watson`'s,
and the fifth-day at the meeting that belongs to Lambs-town.
I think Carlow monthly meeting is next first-day, I intend to be there.

Dublin, the twelfth of the eighth month.--Friends, as far as I can have account,
are in the general pretty well in health, and at liberty,
and our meetings quiet and peaceable; and so are all others, for all I know.
But many in the country are under sufferings, as respects the loss of their goods,
by reason of the wars this land is greatly attended with.
However, the eye of our Friends is to the Lord,
who doubtless permits not all these things to come to pass without a cause,
but to be a chastisement for the sinfulness of the children of men.

O!--that all would take warning, to keep out of that which provokes him to displeasure,
that his hand might be removed.
And truly, that which is our comfort and stay in the midst of all,
is the holy presence of his power, which attends our meetings;
from the evidence of which we receive our satisfaction,
that the Lord is well pleased with us.
And this is that which bears up our spirits in the time of exercise.

Dublin, the twenty-fifth of the first month,
1690.--I had the opportunity this last winter to go
among Friends throughout both Leinster and Munster,
which was a great satisfaction both to me and them.
Friends are generally well, and our meetings are full,
and we enjoy them in quietness as formerly:
and the Lord`'s presence is with us to our great comfort,
which is valued by all who are rightly sensible of it, as a great mercy.

Dublin, the twenty-first of the sixth month.-- I have been visiting Friends in the North,
and had an acceptable and comfortable season among them, and found them very cheerful.
It is still to be lamented, that sin and wickedness should so abound;
but the Lord doubtless will plead with all that grieve him, in his own way and time,
though he be long-suffering.

And therefore it will be our happiness,
to rest quiet under his disposing and ordering hand,
by which he will in his wisdom and power overrule all men and things,
who knows best how to execute justice and judgment upon all,
according to their works or deserts; for before him all things are naked and bare,
therefore he cannot miss in judgment.
We resting here, and waiting upon him, it quiets our spirits, and sweetens them:
and also I can say,
it makes many bitter things sweet and so sanctified
that we meet with comfort in tribulation.
And though it be natural unto and lawful for us in affliction,
reverently to pray for and desire deliverance, and also when obtained,
to rejoice therein, and bless the Lord for it; yet still our happiness is,
to mind his providences, and wise ordering of all things, and therewith to be content,
without either murmuring at, or struggling against, what he sees good to bring to pass.
And so here we shall all rest in one fold and covenant, and feed in one pasture together,
and so have a fellow-feeling of one another`'s joy or sufferings.
For our resting place is but one in the Truth, and our salvation stands therein forever;
and therefore we need look at no other.

[.signed-section-signature]
John Burnyeat.
