[#testimony-ireland.style-blurb, short="Testimony of Friends in Ireland"]
== A Testimony of several Friends in Ireland, in whose hearts it sprung, and who gave it forth in the behalf of our dear brother John Burnyeat

As for our dear friend and worthy brother in the Lord, John Burnyeat, late of Dublin,
deceased, whom some of us have known many years,
we have this testimony in the truth concerning him,
--that he has been steadfast in the Lord`'s work,
an able minister of the gospel and faithful laborer,
who had a word in season to minister to the several conditions of Friends and people,
dividing the word aright; a strengthener of the weak,
and a free feeder of Christ`'s lambs and sheep, with the food he had freely received,
to the comforting of many.

His testimony for the power of Truth and righteousness was clear,
and many were convinced by him.
His conduct was so heavenly, and becoming the principle of Truth he was a preacher of,
that we know no one that can truly charge him with
anything that might spot his profession or ministry.
He was a man excellently well qualified for the work whereunto he was called of God,
the Lord having endued him with a large measure of his spirit.
He had great openings and discoveries of the mysteries of God`'s kingdom:
he had also the tongue of the learned,
and was fitted for every good word and work the Lord employed him in.
His qualifications were beyond many; and though little in himself,
yet in the Lord a mighty man of valor.
In all times of suffering and exercise he failed not to be in the front;
he was a valiant in Israel, and a pillar in the house of God:
he did sympathize with the afflicted, seeking the good of others;
and above all the honor and prosperity of Truth were in his eye.

When he took his wife among us, how careful and circumspect was he of Truth`'s honor,
and the concord and unity of Friends and brethren!
And where he came among Friends, he would not be idle, but did often visit the sick,
and comfort those that were in distress or affliction.
For indeed, he was a true servant to all honest Friends, the poor as well as the rich;
and would freely administer of his outward substance to such as stood in need.
He was meek and gentle, and of a healing spirit;
and it was the love and mercy of God to us in this nation,
and particularly this city of Dublin,
to order his outward abode and settlement among us.
By whom many were convinced of the Truth, and turned from the evil of their ways;
and the peace of the church, the unity and fellowship of Friends increased.

He was one of the archers of Israel, who could shoot to a hairsbreadth,
to the wounding of the hairy scalp of the wicked one,
and the putting of the Lord`'s enemies to silence.

He was a messenger of glad tidings,
and directed us to the blessed light that God had caused to shine in our hearts,
when we were strangers to it?
Yes, then did it appear as a witness for the Lord against all ungodly practices.

It was a day of glad tidings to many, when the Lord made him one of his trumpets to us,
to sound his gospel to the reaching God`'s witness in our hearts:
Oh!--that it may not be forgotten by any of us who have been turned to God!
He had a true love for all tenderhearted Friends,
and travelled for their growth and prosperity in the blessed Truth,
not only in these three nations, but also in the western islands and America,
to the turning many to the blessed way of life and salvation, as by accounts appear.

He was a true pattern of godliness and piety, in a humble, meek, and inoffensive conduct,
apt to teach, ready to give heavenly advice and instruction:
a good example in all things.
An early comer to meetings, and a diligent waiter therein:
many times he would sit a pretty while in silence, not being forward to speak,
reverently waiting upon the opening of the heavenly life,
like the good householder spoken of,
to bring forth of his treasury things both new and old.
He was deeply experienced in the work and service of the Lord,
and was a great comfort and support to many in their great sufferings and hard exercises;
and did mightily strengthen and encourage Friends in their several places of abode.
Twice, during the late troubles,
he visited Friends in Munster and in this province of Leinster,
unto whom he was very open; and had large meetings:
for in many places the world`'s teachers were fled, and left their flocks.
Many times in the public meetings he would bear a faithful,
plain and clear testimony against superstition and idolatry, and against that loose,
wicked, blasphemous, and unclean spirit, that many gave up to be led by.
As soon as the way was open to the north, he visited Friends there.

Now after the death of his wife he had some intentions to go for England,
and sent his son there; but seeing the troubles of wars coming on,
and that many afflictions and exercises would attend us
and that many people being possessed with great fears,
fled for England; at which time many testimonies came from Friends of various meetings,
for all to mind the Lord`'s preserving power, and not to let fears take hold of them,
as it did of others, who knew not the Lord.
Our dear friend, though he had an opportunity, had no freedom to go for England;
but gave himself up to stay with Friends here,
and bear a part of the sufferings that might attend us.
In which time he was a precious instrument in the Lord`'s hand for the
comforting his people in the time of great afflictions and calamities;
for he was a cheerful encourager of us.
He was a dear friend, a true brother, a diligent overseer and tender father;
a perfect and upright man in his day, who feared God, and eschewed evil.
And though he sought the salvation of all,
yet could not bear with deceitful men and evil workers, who professed the Truth,
yet brought dishonor to it; against such he had a just indignation and godly zeal.
Oh! The remembrance of his fatherly care over
God`'s heritage in keeping things in good order,
is not to be forgotten:
for his care was great that the professors of Truth might walk
answerable to it in a chaste life and blameless conduct.

And in all his travels, into whose house he entered,
he was content with what things were set before him, were they ever so humble;
which was great satisfaction to many poor, honest Friends, among whom his lot was cast.
He would not usurp authority over his brethren,
but was of a healing spirit and lamb-like nature,
and of a good report in all his travels.

Our dear Friend and brother did greatly delight to read the holy Scriptures,
and would often and with great earnestness advise Friends frequently to read the same,
and the young and tender in years more especially; as also Friends`' books,
wherein the principles of Truth were treated of;
that so none might be ignorant of the principles of the true Christian religion,
now again preached and clearly held forth.

He was at our province meeting at Rosenallis a little before his decease,
where he bore a living, fresh testimony among Friends to our great comfort,
and exhorted Friends to faithfulness.
From there he went to Montroth, and had a meeting there; and from there to Ballinakill,
and had a meeting there.

So he came to the monthly meeting at New-Garden, where many heard him bear a living,
sweet testimony, in the opening of the word of life, to the refreshing of their souls.
After meeting he came home with our friend John Watson to his house;
and feeling himself not well, took his bed, and was visited with a fever;
and continued sick for the space of twelve days.

All which time he was preserved in his senses, and in a sweet frame of spirit;
and did often say he was finely at ease, and quiet in his spirit.

The Lord did attend him with his heavenly power and presence,
to his comfort and our great satisfaction.
He said to John Watson, that he ever loved the Lord,
and the Lord loved him from his youth, and that he felt his love.

He was wonderfully preserved in a sensible condition to the last;
and on the 11th day of the seventh month, 1690, about two of the clock in the afternoon,
he quietly and peaceably departed this life, about the fifty-ninth year of his age,
and is gone to his rest with the Lord, and his works follow him.

And as he honored the Lord in his day,
so he was honored with the company of many ancient
Friends from several parts of our province,
to accompany him to his grave at New-Garden,
where he was decently interred the 14th day of the same month;
and there we had a good meeting, to the great satisfaction of many Friends and others.

And now surely, if David did well in sorrowing for Absalom,
we have reason greatly to lament the loss of so dear, tender,
and upright-hearted a Friend, whose labor and travel was great both in body and spirit,
faithfully to serve the Lord, his church and people,
and to exalt his glorious name and propagate his living Truth in the earth,
and to preserve unity and peace in the churches of Christ.
But believing it is the Lord`'s will that is done concerning him,
in a holy and reverent resignation and submission thereunto, we ought to be content;
knowing it is his unspeakable gain to be absent from the body, and at home with Christ.

And thus, dear Friends,
we that yet remain do see how the Lord is pleased to remove from among us
many of our ancient Friends and faithful laborers in the gospel of peace,
who have been serviceable in this day for the
gathering and confirming of many in the Truth,
that we may walk therein.
And Friends, we that are yet behind,
are the more immediately concerned for to labor in the heavenly gift of his divine grace,
which the Lord in his love has bestowed upon us,
that so we may come up in this gospel day to succeed
them that are gone before us to their rest in the Lord,
in bearing a faithful testimony to the blessed Truth;
that our memorial may live to ages to come,
as this our dear friend and elder brother`'s does among God`'s people to this day:
who having faithfully finished his course here in great
patience and a humble and holy subjection to the will of God,
has now received a crown of immortal glory,
which is laid up for all the faithful followers of the Lamb,
and lovers of the appearance of our Lord Jesus Christ:
to whom and the Father through him be glory and honor both now and forever.
Amen.

[.signed-section-signature]
Anthony Sharp, Roger Roberts, Amos Strettel, John Watson, Henry Hillary, John Haukes.

[.signed-section-context-close]
Dated in Dublin, the 22nd of the Second month, 1691.
