[#to-barbadoes.style-blurb, short="To the Rulers, Ministers, and People of Barbados"]
== To the rulers, ministers, and people of the Island of Barbados, who see and take notice in any measure of the hand of the Lord that is upon them, and have desires in them to have his judgments removed.

[.salutation]
Friends,

It is sin that provokes the Lord, and causes his judgments in his wrath,
to come upon a nation, a people, or a particular;
for that does the Lord visit with his rod, and many times smite with his sore judgments.

While that is lived in, the Lord will not hear, though man may cry and make many prayers,
as you may see in the Scriptures of truth.

Read Isaiah the 1st, and see what the Lord said unto Israel, when they were revolted,
and become a sinful nation, a people laden with iniquity.
Though they offered sacrifices and burnt offerings, and called assemblies,
and observed the new moons and the appointed feasts,
the prophet called them the rulers of Sodom; and said,
"`Hear the word of the Lord you rulers of Sodom, give ear unto the law of our God,
you people of Gomorrah; to what purpose is the multitude of your sacrifices,
says the Lord,`" etc, And further told them, that though they spread forth their hands,
he would hide his eyes from them, and when they did make many prayers, he would not hear;
their hands were full of blood; and therefore commanded them to wash, make clean,
and put away the evil of their doings from before his eyes, and cease to do evil,
and learn to do well; seek judgment, relieve the oppressed, judge the fatherless,
plead for the widow, and then come and let us reason together, says the Lord.

So here you may see, this is the way for man to cease from doing evil,
and to learn to do well, whereby he may come into acquaintance with the Lord,
and to have his prayers heard and his requests answered,
and so the judgment to be removed.
And also Daniel`'s counsel to the king was,
that he should break off his sins by righteousness,
and his iniquities by showing mercy to the poor,
that it might be a lengthening of his tranquillity. Dan. 4:27.
All along in the Scriptures of truth,
you may see that sin was the cause why the Lord was angry with any people,
and why his wrath came upon any nation; and that the Lord,
though he spared long many times, would not be reconciled to them,
till they obeyed his call in turning from the evil of their ways;
and if they would not be turned,
at last he brought his judgments upon them to cut them off.

You may see concerning Israel many times, both in the wilderness,
where the unbelieving and disobedient were cut off and perished; and also,
after they were come into the land of promise, how often because of their sins,
he brought his judgments over them, and destruction upon them, after he had warned them,
and by his prophets called unto them to leave their wickedness,
and to learn to do righteously, and to amend their ways and their doings.
Because they would not hear, but continued in their sin,
the Lord brought his sore judgments upon them, and rejected them, and cut them off,
and laid the land desolate, notwithstanding the multitude of their sacrifices,
of their prayers, and of their observations.
So that he that killed an ox, was as if he slew a man, and he that sacrificed a lamb,
as if he cut off a dog`'s neck, and he that offered an oblation,
as if he offered swines`' blood, and he that burned incense, as if he blessed an idol;
and all this was because they chose their own ways,
and their souls did delight in their abominations, as you may read, Isaiah 66:3-4.
Therefore were all their performances rejected of the Lord,
and he brought their fear upon them; because when he called, they would not answer,
when he spoke, they would not hear, but did evil before his eyes,
and chose that in which he delighted not.
So that all along you may see in the Scripture, it was not that which people did,
as upon the account of the worship of God, that at all pleases him,
or appeased his wrath, while they did evil before him,
and chose that in which he delighted not;
as is very evident from the Scriptures of truth,
in several testimonies therein to this purpose.
Time would fail to mention all; and what was written aforetime,
was written for our learning, and that we should take warning by their example,
who sinned and continued therein till the day of mercy was over, Rom. 15:4.
1 Cor. 10:11.

Since the Lord has stirred in you to take notice of his judgments,
and of his hand upon the people of this island,
prepare your hearts to seek the Lord in his own way;
and before you pretend to draw nigh unto him that is holy, or to worship him,
or to offer an offering, or to keep a day unto him, forsake your sins,
put away the evil of your doing from before his eyes, and learn to do well,
that your prayers may be heard, and that you may keep the day holy unto the Lord.
Observe the fast which the Lord has chosen, which is, to loose the bands of wickedness,
to undo the heavy burdens, and to let the oppressed go free; and to break every yoke;
to deal your bread to the hungry, with such like works of righteousness.

And then the Lord has promised, that to such,
their light shall break forth as the morning,
and their health shall spring forth speedily,
and their righteousness shall go before them,
and the glory of the Lord shall be their reward.

Then may such cry, and the Lord will answer, and say.
Here am I; when there is a taking away from the midst of you the yoke,
the putting forth of the finger, and the speaking of vanity, etc., Isa. 58:6-9.
Therefore try your ways and your doings,
and let none think that the Lord is like a man,
that he will be satisfied with fair words or pretenses;
where his voice is not hearkened unto and obeyed, but sin lived in,
and the fast kept which the Scripture condemns, which the Lord has not chosen,
as you may read, Isa.
58: 2-5, verses; for you may see there, how that that people did seek him daily,
and had a delight to know his ways, as a nation that did righteousness,
and forsook not the ordinances of their God.

They asked of me the ordinances of justice, says the Lord,
and they take delight in approaching to God; and then cried.
Why have we fasted, and you see not?
Why have we afflicted our souls, and you take no knowledge?
The Lord gives the reason; Behold, says he, in the day of your fast you find pleasure,
and exact all your labors.

Behold, you fast for strife and debate, and to smite with the fist of wickedness;
you shall not fast as you do this day, to make your voice to be heard on high,
says the Lord.
Is it such a fast that I have chosen, a day for a man to afflict his soul,
and bow down his head as a bulrush, and to spread sackcloth and ashes under him?
Will you call this a fast, and an acceptable day to the Lord?
says the prophet.

No, as I have showed before, this is not it;
therefore let every one consider how they are
prepared to keep the fast that God has chosen,
that the fruits thereof may be brought forth by every one that pretends to it,
or else their cry will not be heard on high; for the Lord knows every one`'s intent,
and takes notice of their doings; so that it is not every one that says.

Lord, Lord, that shall enter and be accepted, but he that does the will of God.
Here you may see.
there are two fasts, the one chosen, and the other rejected;
and the fruits of both manifested, whereby they may be known, who are the true fasters,
and who are not, agreeably to what Christ has said;
every tree shall be known by its fruit.
Let all mind what they do, and what they bring forth;
for they that fast for strife and debate, and do smite with the fist of wickedness,
they do not fast to the Lord; their voice he will not hear, according to the Scripture.

And such who instead of setting the oppressed free, of undoing the heavy burdens,
and of breaking every yoke, do bring under oppression, and lay heavy burdens,
and make yokes instead of breaking them,
such are not the people the Lord will accept in their fasts,
nor whose prayers he will hear.
Because they walk not in the equal way of the Lord, but love to wander,
and have not restrained their feet, therefore says Jeremiah,
the Lord does not accept them, but will remember their iniquity and visit their sins;
and the Lord commanded the prophet,
that he should not pray for that people for their good; for said God, When they fast,
I will not hear their cry, and when they offer burnt-offerings and an oblation,
I will not accept them; but I will consume them by the sword, and by the famine,
and by the pestilence, Jer. 14:10-12. So you may see all along,
the Lord does not regard all that man can do, or may do, so long as he wanders from God,
and does not restrain his feet from walking in the evil way.

Thus has it been in all dispensations of the Scripture before,
and therefore much more under this last and most
glorious ministration of the gospel of Christ Jesus,
which is professed by you, wherein the former comes to be fulfilled and finished,
or perfected, where Christ himself is the great Lawgiver,
who gives out his ordinances and precepts unto all his people,
who according to the promise of the Father, gives unto them the Spirit,
and writes his law in the hearts of all the children of the new covenant, Jer. 31:33,
which they are to observe and to walk after; and if any one do otherwise,
he ought to be dealt withal, according to the command of this great Lawgiver, Matt. 28:15-17.
First to be spoken to, and see if he will hear, either a brother,
two or three, or the church.
And if he will not hear, nor be gained, then says Christ,
"`Let him be unto you as a heathen and a publican.`"

But he gives no commission to Christians to persecute, to put in prison,
to take away goods, to pull down their houses, to put their feet in the stocks,
to root them out of the world root and branch; no,
nor to wish it so to be done unto them.
But if any do, he will reprove such, as he did the disciples, when he told them.
They knew not what spirit they were of, when they desired fire to come from heaven;
for he came not to destroy, but to save, as you may read, Luke 9:54-56.
And you may see what the apostle Paul says,
who was a wise master builder; he says.
One man esteems one day above another, another esteems every day alike; but between them,
he says.
Let every man be fully persuaded in his own mind.
So you may see, here is no forcing upon any man,
in those things that appertain to the worship of God;
but as Christ overrules the conscience, and persuades the heart,
and brings man into a belief that it is according to the will of God,
so that it may be done in the faith, without which none can please God;
for says the apostle.
Whatsoever is not of faith, is sin, Rom. 14:5 and 23 verses.
Therefore as the gospel is professed, let Christ`'s commands be observed,
and the example of the primitive Christians followed, who were blessed in their day,
and had the witness of acceptance with God; who were persecuted,
but never persecuted any, nor sought to trouble any, as upon a bodily or outward account,
for their conscience; though they did reprove them sharply,
that turned away from the power of Truth, and became enemies to the cross of Christ,
whose belly was their God, who gloried in their shame, and minded earthly things,
and so served not the Lord Jesus Christ, but their own bellies, Phil. 3:18-19.

Now such the apostle did bear testimony against, or any others that did unrighteously;
but we do not read that he either did, or desired to have it so,
that they that did not serve the Lord Jesus Christ, should be put in prison,
or in the stocks, or any such bodily punishment,
but left them to the righteous judgments of the Lord at his coming, having warned them,
and so not to have fellowship with them as brethren; but according to Christ`'s command,
let them be as heathens or publicans.
And so all may see very clearly, who will read the Scripture with a single eye,
that it is not of Christ,
nor according to the primitive example of the church in her best state,
to enforce the conscience of any, to do anything as a duty to God,
which they themselves had not a persuasion unto, though they did very sharply reprove,
and very zealously bear testimony against all such,
who made shipwreck of faith and a good conscience,
and turned from the guidance and leading of the grace of God into lasciviousness,
wantonness, and fleshly liberty.

And therefore I cannot but desire that all who profess Christianity,
may follow the example of those who were the first and wisest builders of Christianity,
who laid the foundation so that another cannot be laid.
And he that would build upon this that is already laid, otherwise than they builded,
must suffer loss in the day when his works come to be tried.

And therefore if any see the Lord`'s rod,
and his judgments in these things that are upon the people of this island,
let all such humble themselves under the mighty hand of God,
and wait to feel his mighty power to subdue the man of sin,
and to bring under that which has oppressed the soul,
that through the power of the Lord Jesus Christ, the Son of God,
the oppressed may be set free, and every yoke may be broken,
that it may be witnessed which was spoken by him, John 8:36, If the Son make you free,
you shall be free indeed.
Then people come to the fast which the Lord has chosen,
and that fast cannot be accompanied with cruelty;
there is no smiting with the fist of wickedness, nor bringing oppression over the just,
where Christ is owned and followed, as the Lord has appointed, as a witness,
a leader and a commander, for which he is given to the people,
as you may read in Isaiah 55:4. But where these evils are brought forth,
as the fruits of any fast, by those that appoint or pretend to keep a fast,
is it not like unto Jezabel`'s fast,
that she caused the elders and nobles of the city to proclaim,
where the just man was witnessed against, condemned, and stoned to death for nothing,
but because he could not give or sell his inheritance away, which the Lord had given him?
So we desire the good of all men, and that every one may take notice of his own ways,
how he walks before the Lord, and do unto others as he would be done unto;
and that all may be free upon the account of things that appertain to God,
and so left to the judgment of him that knows all hearts,
that from him they may receive reward.

As for those things wherein man is concerned,
if any man do wrong or injury to another in person or estate, we say,
let such be punished according to the law, which was made for the transgressor,
and let judgment run down as waters, and righteousness as a mighty stream, Amos 5:4.
This is the way the Scripture largely testifies,
wherein man may come to be accepted, and the wrath of God appeased,
and his judgments removed, and so the right desire answered.

From a lover of peace and righteousness, who truly seeks the good of all men,

[.signed-section-signature]
John Burnyeat

[.signed-section-context-close]
Written in Barbados, about the 29th of the eleventh month, 1670,
upon the occasion of a fast, that was pretended to by the people of the island,
because of a great sickness that was upon them, whereof many died;
of which my companion William Simpson then died.
